/* Generated by Nim Compiler v0.12.0 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -g3 -O0  -I/media/marco/Research/Applications/aporia/Nim/lib -o /home/marco/.nimble/pkgs/Pythonize27-1.0.0/tests/nimcache/dynlib.o /home/marco/.nimble/pkgs/Pythonize27-1.0.0/tests/nimcache/dynlib.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#include <dlfcn.h>
typedef struct Libraryerror4035 Libraryerror4035;
typedef struct Oserror4033 Oserror4033;
typedef struct Systemerror4029 Systemerror4029;
typedef struct Exception Exception;
typedef struct TNimObject TNimObject;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct Cell49347 Cell49347;
typedef struct Cellseq49363 Cellseq49363;
typedef struct Gcheap51418 Gcheap51418;
typedef struct Gcstack51416 Gcstack51416;
typedef struct Cellset49359 Cellset49359;
typedef struct Pagedesc49355 Pagedesc49355;
typedef struct Memregion31291 Memregion31291;
typedef struct Smallchunk31243 Smallchunk31243;
typedef struct Llchunk31285 Llchunk31285;
typedef struct Bigchunk31245 Bigchunk31245;
typedef struct Intset31217 Intset31217;
typedef struct Trunk31213 Trunk31213;
typedef struct Avlnode31289 Avlnode31289;
typedef struct Gcstat51414 Gcstat51414;
typedef struct Basechunk31241 Basechunk31241;
typedef struct Freecell31233 Freecell31233;
typedef N_NIMCALL_PTR(void, TY3889) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3894) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3889 marker;
TY3894 deepcopy;
};
struct  TNimObject  {
TNimType* m_type;
};
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct  Exception  {
  TNimObject Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
NimStringDesc* trace;
};
struct  Systemerror4029  {
  Exception Sup;
};
struct  Oserror4033  {
  Systemerror4029 Sup;
NI32 errorcode;
};
struct  Libraryerror4035  {
  Oserror4033 Sup;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  Cell49347  {
NI refcount;
TNimType* typ;
};
struct  Cellseq49363  {
NI len;
NI cap;
Cell49347** d;
};
struct  Cellset49359  {
NI counter;
NI max;
Pagedesc49355* head;
Pagedesc49355** data;
};
typedef Smallchunk31243* TY31306[512];
typedef Trunk31213* Trunkbuckets31215[256];
struct  Intset31217  {
Trunkbuckets31215 data;
};
struct  Memregion31291  {
NI minlargeobj;
NI maxlargeobj;
TY31306 freesmallchunks;
Llchunk31285* llmem;
NI currmem;
NI maxmem;
NI freemem;
NI lastsize;
Bigchunk31245* freechunkslist;
Intset31217 chunkstarts;
Avlnode31289* root;
Avlnode31289* deleted;
Avlnode31289* last;
Avlnode31289* freeavlnodes;
};
struct  Gcstat51414  {
NI stackscans;
NI cyclecollections;
NI maxthreshold;
NI maxstacksize;
NI maxstackcells;
NI cycletablesize;
NI64 maxpause;
};
struct  Gcheap51418  {
Gcstack51416* stack;
void* stackbottom;
NI cyclethreshold;
Cellseq49363 zct;
Cellseq49363 decstack;
Cellset49359 cycleroots;
Cellseq49363 tempstack;
NI recgclock;
Memregion31291 region;
Gcstat51414 stat;
};
struct  Gcstack51416  {
Gcstack51416* prev;
Gcstack51416* next;
void* starts;
void* pos;
NI maxstacksize;
};
typedef NI TY31222[8];
struct  Pagedesc49355  {
Pagedesc49355* next;
NI key;
TY31222 bits;
};
struct  Basechunk31241  {
NI prevsize;
NI size;
NIM_BOOL used;
};
struct  Smallchunk31243  {
  Basechunk31241 Sup;
Smallchunk31243* next;
Smallchunk31243* prev;
Freecell31233* freelist;
NI free;
NI acc;
NF data;
};
struct  Llchunk31285  {
NI size;
NI acc;
Llchunk31285* next;
};
struct  Bigchunk31245  {
  Basechunk31241 Sup;
Bigchunk31245* next;
Bigchunk31245* prev;
NI align;
NF data;
};
struct  Trunk31213  {
Trunk31213* next;
NI key;
TY31222 bits;
};
typedef Avlnode31289* TY31296[2];
struct  Avlnode31289  {
TY31296 link;
NI key;
NI upperbound;
NI level;
};
struct  Freecell31233  {
Freecell31233* next;
NI zerofield;
};
N_NOINLINE(void, raiseinvalidlibrary_124041)(NCSTRING name) __attribute__((noreturn));
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
N_NIMCALL(NimStringDesc*, cstrToNimstr)(NCSTRING str);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
static N_INLINE(Cell49347*, usrtocell_53046)(void* usr);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_23601)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(void, rtladdzct_54604)(Cell49347* c);
N_NOINLINE(void, addzct_53017)(Cellseq49363* s, Cell49347* c);
N_NIMCALL(void, raiseException)(Exception* e, NCSTRING ename);
N_NIMCALL(void*, checkedsymaddr_124068)(void* lib, NCSTRING name);
N_NIMCALL(void*, loadlib_124023)(NimStringDesc* path, NIM_BOOL globalsymbols);
N_NIMCALL(void*, loadlib_124030)(void);
N_NIMCALL(void, unloadlib_124035)(void* lib);
N_NIMCALL(void*, symaddr_124061)(void* lib, NCSTRING name);
STRING_LITERAL(TMP466, "could not find symbol: ", 23);
extern TNimType NTI124044; /* ref LibraryError */
extern TNimType NTI4035; /* LibraryError */
extern TFrame* frameptr_20842;
extern Gcheap51418 gch_51459;

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	memcpy(((NCSTRING) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((NCSTRING) ((*src).data)), (NI)((*src).Sup.len + ((NI) 1)));
	(*dest).Sup.len += (*src).Sup.len;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_20842 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_20842).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_20842;
	frameptr_20842 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_23601();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_20842 = (*frameptr_20842).prev;
}

static N_INLINE(Cell49347*, usrtocell_53046)(void* usr) {
	Cell49347* result;
	nimfr("usrToCell", "gc.nim")
	result = 0;
	nimln(131, "gc.nim");
	result = ((Cell49347*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(Cell49347))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtladdzct_54604)(Cell49347* c) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(212, "gc.nim");
	addzct_53017((&gch_51459.zct), c);
	popFrame();
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr("asgnRefNoCycle", "gc.nim")
	nimln(264, "gc.nim");
	{
		Cell49347* c;
		nimln(349, "system.nim");
		if (!!((src == NIM_NIL))) goto LA3;
		nimln(265, "gc.nim");
		c = usrtocell_53046(src);
		nimln(182, "gc.nim");
		(*c).refcount += ((NI) 8);
	}
	LA3: ;
	nimln(267, "gc.nim");
	{
		Cell49347* c;
		nimln(349, "system.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA7;
		nimln(268, "gc.nim");
		c = usrtocell_53046((*dest));
		nimln(269, "gc.nim");
		{
			nimln(180, "gc.nim");
			(*c).refcount -= ((NI) 8);
			nimln(181, "gc.nim");
			if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA11;
			nimln(270, "gc.nim");
			rtladdzct_54604(c);
		}
		LA11: ;
	}
	LA7: ;
	nimln(271, "gc.nim");
	(*dest) = src;
	popFrame();
}

N_NOINLINE(void, raiseinvalidlibrary_124041)(NCSTRING name) {
	Libraryerror4035* e;
	NimStringDesc* LOC1;
	NimStringDesc* LOC2;
	nimfr("raiseInvalidLibrary", "dynlib.nim")
	e = 0;
	nimln(33, "dynlib.nim");
	e = (Libraryerror4035*) newObj((&NTI124044), sizeof(Libraryerror4035));
	(*e).Sup.Sup.Sup.Sup.m_type = (&NTI4035);
	nimln(34, "dynlib.nim");
	LOC1 = 0;
	LOC2 = 0;
	LOC2 = cstrToNimstr(name);
	LOC1 = rawNewString(LOC2->Sup.len + 23);
appendString(LOC1, ((NimStringDesc*) &TMP466));
appendString(LOC1, LOC2);
	asgnRefNoCycle((void**) (&(*e).Sup.Sup.Sup.message), LOC1);
	nimln(35, "dynlib.nim");
	raiseException((Exception*)e, "LibraryError");
	popFrame();
}

N_NIMCALL(void*, checkedsymaddr_124068)(void* lib, NCSTRING name) {
	void* result;
	nimfr("checkedSymAddr", "dynlib.nim")
	result = 0;
	nimln(44, "dynlib.nim");
	result = symaddr_124061(lib, name);
	nimln(45, "dynlib.nim");
	{
		if (!(result == NIM_NIL)) goto LA3;
		raiseinvalidlibrary_124041(name);
	}
	LA3: ;
	popFrame();
	return result;
}

N_NIMCALL(void*, loadlib_124023)(NimStringDesc* path, NIM_BOOL globalsymbols) {
	void* result;
	NI flags;
	nimfr("loadLib", "dynlib.nim")
{	result = 0;
	nimln(67, "dynlib.nim");
	flags = RTLD_NOW;
	nimln(68, "dynlib.nim");
	{
		if (!globalsymbols) goto LA3;
		flags = (NI)(flags | RTLD_GLOBAL);
	}
	LA3: ;
	nimln(69, "dynlib.nim");
	result = dlopen(path->data, flags);
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(void*, loadlib_124030)(void) {
	void* result;
	nimfr("loadLib", "dynlib.nim")
{	result = 0;
	nimln(70, "dynlib.nim");
	result = dlopen(NIM_NIL, RTLD_NOW);
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(void, unloadlib_124035)(void* lib) {
	nimfr("unloadLib", "dynlib.nim")
	nimln(71, "dynlib.nim");
	dlclose(lib);
	popFrame();
}

N_NIMCALL(void*, symaddr_124061)(void* lib, NCSTRING name) {
	void* result;
	nimfr("symAddr", "dynlib.nim")
{	result = 0;
	nimln(73, "dynlib.nim");
	result = dlsym(lib, name);
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, HEX00_dynlibInit000)(void) {
	nimfr("dynlib", "dynlib.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, HEX00_dynlibDatInit000)(void) {
}

