/* Generated by Nim Compiler v0.12.0 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -g3 -O0  -I/media/marco/Research/Applications/aporia/Nim/lib -o /home/marco/.nimble/pkgs/Pythonize27-1.0.0/tests/nimcache/parseutils.o /home/marco/.nimble/pkgs/Pythonize27-1.0.0/tests/nimcache/parseutils.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <stdio.h>
#include <stdlib.h>
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct Overflowerror4043 Overflowerror4043;
typedef struct Arithmeticerror4039 Arithmeticerror4039;
typedef struct Exception Exception;
typedef struct TNimObject TNimObject;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct Memregion31291 Memregion31291;
typedef struct Gcheap51418 Gcheap51418;
typedef struct Gcstack51416 Gcstack51416;
typedef struct Cellseq49363 Cellseq49363;
typedef struct Cell49347 Cell49347;
typedef struct Cellset49359 Cellset49359;
typedef struct Pagedesc49355 Pagedesc49355;
typedef struct Smallchunk31243 Smallchunk31243;
typedef struct Llchunk31285 Llchunk31285;
typedef struct Bigchunk31245 Bigchunk31245;
typedef struct Intset31217 Intset31217;
typedef struct Trunk31213 Trunk31213;
typedef struct Avlnode31289 Avlnode31289;
typedef struct Gcstat51414 Gcstat51414;
typedef struct Basechunk31241 Basechunk31241;
typedef struct Freecell31233 Freecell31233;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef N_NIMCALL_PTR(void, TY3889) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3894) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3889 marker;
TY3894 deepcopy;
};
struct  TNimObject  {
TNimType* m_type;
};
struct  Exception  {
  TNimObject Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
NimStringDesc* trace;
};
struct  Arithmeticerror4039  {
  Exception Sup;
};
struct  Overflowerror4043  {
  Arithmeticerror4039 Sup;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  Cellseq49363  {
NI len;
NI cap;
Cell49347** d;
};
struct  Cellset49359  {
NI counter;
NI max;
Pagedesc49355* head;
Pagedesc49355** data;
};
typedef Smallchunk31243* TY31306[512];
typedef Trunk31213* Trunkbuckets31215[256];
struct  Intset31217  {
Trunkbuckets31215 data;
};
struct  Memregion31291  {
NI minlargeobj;
NI maxlargeobj;
TY31306 freesmallchunks;
Llchunk31285* llmem;
NI currmem;
NI maxmem;
NI freemem;
NI lastsize;
Bigchunk31245* freechunkslist;
Intset31217 chunkstarts;
Avlnode31289* root;
Avlnode31289* deleted;
Avlnode31289* last;
Avlnode31289* freeavlnodes;
};
struct  Gcstat51414  {
NI stackscans;
NI cyclecollections;
NI maxthreshold;
NI maxstacksize;
NI maxstackcells;
NI cycletablesize;
NI64 maxpause;
};
struct  Gcheap51418  {
Gcstack51416* stack;
void* stackbottom;
NI cyclethreshold;
Cellseq49363 zct;
Cellseq49363 decstack;
Cellset49359 cycleroots;
Cellseq49363 tempstack;
NI recgclock;
Memregion31291 region;
Gcstat51414 stat;
};
struct  Cell49347  {
NI refcount;
TNimType* typ;
};
struct  Gcstack51416  {
Gcstack51416* prev;
Gcstack51416* next;
void* starts;
void* pos;
NI maxstacksize;
};
typedef NI TY31222[8];
struct  Pagedesc49355  {
Pagedesc49355* next;
NI key;
TY31222 bits;
};
struct  Basechunk31241  {
NI prevsize;
NI size;
NIM_BOOL used;
};
struct  Smallchunk31243  {
  Basechunk31241 Sup;
Smallchunk31243* next;
Smallchunk31243* prev;
Freecell31233* freelist;
NI free;
NI acc;
NF data;
};
struct  Llchunk31285  {
NI size;
NI acc;
Llchunk31285* next;
};
struct  Bigchunk31245  {
  Basechunk31241 Sup;
Bigchunk31245* next;
Bigchunk31245* prev;
NI align;
NF data;
};
struct  Trunk31213  {
Trunk31213* next;
NI key;
TY31222 bits;
};
typedef Avlnode31289* TY31296[2];
struct  Avlnode31289  {
TY31296 link;
NI key;
NI upperbound;
NI level;
};
struct  Freecell31233  {
Freecell31233* next;
NI zerofield;
};
N_NIMCALL(NI, npuParseBiggestInt)(NimStringDesc* s, NI64* number, NI start);
N_NIMCALL(NI, rawparseint_96914)(NimStringDesc* s, NI64* b, NI start);
N_NOINLINE(void, raiseIndexError)(void);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
N_NIMCALL(NI64, mulInt64)(NI64 a, NI64 b);
static N_INLINE(NI, subInt)(NI a, NI b);
static N_INLINE(NI64, subInt64)(NI64 a, NI64 b);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_23601)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
N_NIMCALL(NIM_BOOL, allocinv_38411)(Memregion31291* a);
static N_INLINE(Cell49347*, usrtocell_53046)(void* usr);
N_NIMCALL(NIM_BOOL, isallocatedptr_38407)(Memregion31291* a, void* p);
static N_INLINE(void, Gcdisable_11201)(void);
N_NIMCALL(void, writestacktrace_20207)(void);
static N_INLINE(void, rtladdzct_54604)(Cell49347* c);
N_NOINLINE(void, addzct_53017)(Cellseq49363* s, Cell49347* c);
N_NIMCALL(void, raiseException)(Exception* e, NCSTRING ename);
STRING_LITERAL(TMP392, "overflow", 8);
STRING_LITERAL(TMP393, "[SYSASSERT] ", 12);
STRING_LITERAL(TMP394, "begin nimGCunrefNoCycle", 23);
STRING_LITERAL(TMP395, "[GCASSERT] ", 11);
STRING_LITERAL(TMP396, "nimGCunrefNoCycle: isAllocatedPtr", 33);
STRING_LITERAL(TMP397, "end nimGCunrefNoCycle 2", 23);
STRING_LITERAL(TMP398, "end nimGCunrefNoCycle 5", 23);
extern TFrame* frameptr_20842;
extern TNimType NTI25717; /* ref OverflowError */
extern TNimType NTI4043; /* OverflowError */
extern Gcheap51418 gch_51459;

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = 0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (((NI) 0) <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result;
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = 0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (((NI) 0) <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result;
}

static N_INLINE(NI64, subInt64)(NI64 a, NI64 b) {
	NI64 result;
{	result = 0;
	result = (NI64)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (IL64(0) <= (NI64)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (IL64(0) <= (NI64)(result ^ (NI64)((NU64) ~(b))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_20842 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_20842).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_20842;
	frameptr_20842 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_23601();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_20842 = (*frameptr_20842).prev;
}

N_NIMCALL(NI, rawparseint_96914)(NimStringDesc* s, NI64* b, NI start) {
	NI result;
	NI64 sign;
	NI i;
	nimfr("rawParseInt", "parseutils.nim")
	result = 0;
	nimln(194, "parseutils.nim");
	sign = IL64(-1);
	nimln(195, "parseutils.nim");
	i = start;
	nimln(196, "parseutils.nim");
	{
		NI TMP383;
		if ((NU)(i) > (NU)(s->Sup.len)) raiseIndexError();
		if (!((NU8)(s->data[i]) == (NU8)(43))) goto LA3;
		TMP383 = addInt(i, ((NI) 1));
		i = (NI)(TMP383);
	}
	goto LA1;
	LA3: ;
	{
		NI TMP384;
		nimln(197, "parseutils.nim");
		if ((NU)(i) > (NU)(s->Sup.len)) raiseIndexError();
		if (!((NU8)(s->data[i]) == (NU8)(45))) goto LA6;
		nimln(198, "parseutils.nim");
		TMP384 = addInt(i, ((NI) 1));
		i = (NI)(TMP384);
		nimln(199, "parseutils.nim");
		sign = IL64(1);
	}
	goto LA1;
	LA6: ;
	LA1: ;
	nimln(200, "parseutils.nim");
	{
		NI64 TMP390;
		NI TMP391;
		nimln(1098, "system.nim");
		if ((NU)(i) > (NU)(s->Sup.len)) raiseIndexError();
		if (!(((NU8)(s->data[i])) >= ((NU8)(48)) && ((NU8)(s->data[i])) <= ((NU8)(57)))) goto LA10;
		nimln(201, "parseutils.nim");
		(*b) = IL64(0);
		{
			nimln(202, "parseutils.nim");
			while (1) {
				NI64 TMP385;
				NI TMP386;
				NI64 TMP387;
				NI TMP388;
				nimln(1098, "system.nim");
				if ((NU)(i) > (NU)(s->Sup.len)) raiseIndexError();
				if (!(((NU8)(s->data[i])) >= ((NU8)(48)) && ((NU8)(s->data[i])) <= ((NU8)(57)))) goto LA13;
				nimln(203, "parseutils.nim");
				TMP385 = mulInt64((*b), IL64(10));
				if ((NU)(i) > (NU)(s->Sup.len)) raiseIndexError();
				TMP386 = subInt(((NI) (((NU8)(s->data[i])))), ((NI) 48));
				TMP387 = subInt64((NI64)(TMP385), ((NI64) ((NI)(TMP386))));
				(*b) = (NI64)(TMP387);
				nimln(204, "parseutils.nim");
				TMP388 = addInt(i, ((NI) 1));
				i = (NI)(TMP388);
				{
					nimln(205, "parseutils.nim");
					while (1) {
						NI TMP389;
						if ((NU)(i) > (NU)(s->Sup.len)) raiseIndexError();
						if (!((NU8)(s->data[i]) == (NU8)(95))) goto LA15;
						TMP389 = addInt(i, ((NI) 1));
						i = (NI)(TMP389);
					} LA15: ;
				}
			} LA13: ;
		}
		nimln(206, "parseutils.nim");
		TMP390 = mulInt64((*b), sign);
		(*b) = (NI64)(TMP390);
		nimln(207, "parseutils.nim");
		TMP391 = subInt(i, start);
		result = (NI)(TMP391);
	}
	LA10: ;
	popFrame();
	return result;
}

N_NIMCALL(NI, npuParseBiggestInt)(NimStringDesc* s, NI64* number, NI start) {
	NI result;
	NI64 res;
	nimfr("parseBiggestInt", "parseutils.nim")
	result = 0;
	res = 0;
	nimln(218, "parseutils.nim");
	result = rawparseint_96914(s, (&res), start);
	nimln(219, "parseutils.nim");
	(*number) = res;
	popFrame();
	return result;
}

static N_INLINE(Cell49347*, usrtocell_53046)(void* usr) {
	Cell49347* result;
	nimfr("usrToCell", "gc.nim")
	result = 0;
	nimln(131, "gc.nim");
	result = ((Cell49347*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(Cell49347))))));
	popFrame();
	return result;
}

static N_INLINE(void, Gcdisable_11201)(void) {
	nimfr("GC_disable", "gc.nim")
	nimln(976, "gc.nim");
	gch_51459.recgclock += ((NI) 1);
	popFrame();
}

static N_INLINE(void, rtladdzct_54604)(Cell49347* c) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(212, "gc.nim");
	addzct_53017((&gch_51459.zct), c);
	popFrame();
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	Cell49347* c;
	nimfr("nimGCunrefNoCycle", "gc.nim")
	nimln(1365, "system.nim");
	{
		NIM_BOOL LOC3;
		nimln(245, "gc.nim");
		LOC3 = 0;
		LOC3 = allocinv_38411((&gch_51459.region));
		if (!!(LOC3)) goto LA4;
		nimln(1366, "system.nim");
		printf("%s%s\012", ((NimStringDesc*) &TMP393)? (((NimStringDesc*) &TMP393))->data:"nil", ((NimStringDesc*) &TMP394)? (((NimStringDesc*) &TMP394))->data:"nil");
		nimln(1367, "system.nim");
		exit(((NI) 1));
	}
	LA4: ;
	nimln(246, "gc.nim");
	c = usrtocell_53046(p);
	nimln(114, "gc.nim");
	{
		NIM_BOOL LOC8;
		nimln(247, "gc.nim");
		LOC8 = 0;
		LOC8 = isallocatedptr_38407((&gch_51459.region), ((void*) (c)));
		if (!!(LOC8)) goto LA9;
		nimln(115, "gc.nim");
		printf("%s%s\012", ((NimStringDesc*) &TMP395)? (((NimStringDesc*) &TMP395))->data:"nil", ((NimStringDesc*) &TMP396)? (((NimStringDesc*) &TMP396))->data:"nil");
		nimln(116, "gc.nim");
		Gcdisable_11201();
		nimln(117, "gc.nim");
		writestacktrace_20207();
		nimln(118, "gc.nim");
		exit(((NI) 1));
	}
	LA9: ;
	nimln(248, "gc.nim");
	{
		nimln(180, "gc.nim");
		(*c).refcount -= ((NI) 8);
		nimln(181, "gc.nim");
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA13;
		nimln(249, "gc.nim");
		rtladdzct_54604(c);
		nimln(1365, "system.nim");
		{
			NIM_BOOL LOC17;
			nimln(250, "gc.nim");
			LOC17 = 0;
			LOC17 = allocinv_38411((&gch_51459.region));
			if (!!(LOC17)) goto LA18;
			nimln(1366, "system.nim");
			printf("%s%s\012", ((NimStringDesc*) &TMP393)? (((NimStringDesc*) &TMP393))->data:"nil", ((NimStringDesc*) &TMP397)? (((NimStringDesc*) &TMP397))->data:"nil");
			nimln(1367, "system.nim");
			exit(((NI) 1));
		}
		LA18: ;
	}
	LA13: ;
	nimln(1365, "system.nim");
	{
		NIM_BOOL LOC22;
		nimln(251, "gc.nim");
		LOC22 = 0;
		LOC22 = allocinv_38411((&gch_51459.region));
		if (!!(LOC22)) goto LA23;
		nimln(1366, "system.nim");
		printf("%s%s\012", ((NimStringDesc*) &TMP393)? (((NimStringDesc*) &TMP393))->data:"nil", ((NimStringDesc*) &TMP398)? (((NimStringDesc*) &TMP398))->data:"nil");
		nimln(1367, "system.nim");
		exit(((NI) 1));
	}
	LA23: ;
	popFrame();
}

N_NIMCALL(NI, npuParseInt)(NimStringDesc* s, NI* number, NI start) {
	NI result;
	NI64 res;
	nimfr("parseInt", "parseutils.nim")
	result = 0;
	res = 0;
	nimln(227, "parseutils.nim");
	result = npuParseBiggestInt(s, (&res), start);
	nimln(228, "parseutils.nim");
	{
		NIM_BOOL LOC3;
		NIM_BOOL LOC5;
		Overflowerror4043* e_97055;
		NimStringDesc* LOC9;
		LOC3 = 0;
		LOC3 = NIM_FALSE;
		if (!(LOC3)) goto LA4;
		nimln(229, "parseutils.nim");
		LOC5 = 0;
		LOC5 = (res < (IL64(-9223372036854775807) - IL64(1)));
		if (LOC5) goto LA6;
		nimln(357, "system.nim");
		LOC5 = (IL64(9223372036854775807) < res);
		LA6: ;
		LOC3 = LOC5;
		LA4: ;
		if (!LOC3) goto LA7;
		e_97055 = 0;
		nimln(2507, "system.nim");
		e_97055 = (Overflowerror4043*) newObj((&NTI25717), sizeof(Overflowerror4043));
		(*e_97055).Sup.Sup.Sup.m_type = (&NTI4043);
		nimln(2508, "system.nim");
		LOC9 = 0;
		LOC9 = (*e_97055).Sup.Sup.message; (*e_97055).Sup.Sup.message = copyStringRC1(((NimStringDesc*) &TMP392));
		if (LOC9) nimGCunrefNoCycle(LOC9);
		nimln(230, "parseutils.nim");
		raiseException((Exception*)e_97055, "OverflowError");
	}
	goto LA1;
	LA7: ;
	{
		nimln(349, "system.nim");
		if (!!((result == ((NI) 0)))) goto LA11;
		nimln(232, "parseutils.nim");
		(*number) = ((NI) (res));
	}
	goto LA1;
	LA11: ;
	LA1: ;
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, HEX00_parseutilsInit000)(void) {
	nimfr("parseutils", "parseutils.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, HEX00_parseutilsDatInit000)(void) {
}

