/* Generated by Nim Compiler v0.12.0 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -g3 -O0  -I/media/marco/Research/Applications/aporia/Nim/lib -o /home/marco/.nimble/pkgs/Pythonize27-1.0.0/tests/nimcache/pythonize_function_tests.o /home/marco/.nimble/pkgs/Pythonize27-1.0.0/tests/nimcache/pythonize_function_tests.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <stdio.h>
#include <string.h>
typedef struct TY132605 TY132605;
typedef struct TGenericSeq TGenericSeq;
typedef struct NimStringDesc NimStringDesc;
typedef struct PythondictHEX3Aobjecttype130025 PythondictHEX3Aobjecttype130025;
typedef struct Tpyobject125574 Tpyobject125574;
typedef struct PythonlistHEX3Aobjecttype130011 PythonlistHEX3Aobjecttype130011;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct PythonobjectattrHEX3Aobjecttype130627 PythonobjectattrHEX3Aobjecttype130627;
typedef struct Tpytypeobject125626 Tpytypeobject125626;
typedef struct TY130058 TY130058;
typedef struct Tpynumbermethods125556 Tpynumbermethods125556;
typedef struct Tpysequencemethods125560 Tpysequencemethods125560;
typedef struct Tpymappingmethods125564 Tpymappingmethods125564;
typedef struct Tpybufferprocs125568 Tpybufferprocs125568;
typedef struct Tpymethoddef125586 Tpymethoddef125586;
typedef struct Tpymemberdef125590 Tpymemberdef125590;
typedef struct Tpygetsetdef125598 Tpygetsetdef125598;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef N_CDECL_PTR(NI, TY126655) (Tpyobject125574* dp, NCSTRING key, Tpyobject125574* item);
typedef N_CDECL_PTR(Tpyobject125574*, TY126833) (NF db);
typedef N_CDECL_PTR(Tpyobject125574*, TY126681) (NCSTRING str, NI start, Tpyobject125574* globals, Tpyobject125574* locals);
typedef N_CDECL_PTR(void, TY126509) (void);
typedef N_CDECL_PTR(NF, TY126827) (Tpyobject125574* ob);
typedef N_CDECL_PTR(Tpyobject125574*, TY126648) (Tpyobject125574* dp, NCSTRING key);
typedef N_CDECL_PTR(Tpyobject125574*, TY126953) (NI size);
typedef N_CDECL_PTR(NI, TY126965) (Tpyobject125574* dp, NI idx, Tpyobject125574* item);
typedef N_CDECL_PTR(Tpyobject125574*, TY127047) (NI64 val);
typedef N_CDECL_PTR(NI, TY126982) (Tpyobject125574* ob);
typedef N_CDECL_PTR(Tpyobject125574*, TY126930) (Tpyobject125574* ob, NI i);
typedef N_CDECL_PTR(NI32, TY127000) (Tpyobject125574* ob);
typedef N_CDECL_PTR(Tpyobject125574*, TY127018) (NCSTRING pc, NCSTRING* ppc, NI i);
typedef N_CDECL_PTR(NCSTRING, TY126696) (Tpyobject125574* ob);
typedef N_CDECL_PTR(Tpyobject125574*, TY127370) (Tpyobject125574* ob);
typedef N_NIMCALL_PTR(void, TY3889) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3894) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3889 marker;
TY3894 deepcopy;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef N_CDECL_PTR(Tpyobject125574*, TY126702) (NCSTRING str);
typedef N_CDECL_PTR(Tpyobject125574*, TY127324) (Tpyobject125574* ob, NCSTRING c);
struct  Tpyobject125574  {
NI obrefcnt;
Tpytypeobject125626* obtype;
};
struct  PythonobjectattrHEX3Aobjecttype130627  {
  Tpyobject125574 Sup;
};
typedef N_CDECL_PTR(NI, TY127384) (Tpyobject125574* ob, NCSTRING key, Tpyobject125574* value);
typedef N_CDECL_PTR(void, TY127892) (void);
struct  PythondictHEX3Aobjecttype130025  {
  Tpyobject125574 Sup;
};
struct  PythonlistHEX3Aobjecttype130011  {
  Tpyobject125574 Sup;
};
typedef N_CDECL_PTR(void, Tpydestructor125508) (Tpyobject125574* ob);
typedef N_CDECL_PTR(NI, Tprintfunc125510) (Tpyobject125574* ob, FILE* f, NI i);
typedef N_CDECL_PTR(Tpyobject125574*, Tgetattrfunc125512) (Tpyobject125574* ob1, NCSTRING name);
typedef N_CDECL_PTR(NI, Tsetattrfunc125514) (Tpyobject125574* ob1, NCSTRING name, Tpyobject125574* ob2);
typedef N_CDECL_PTR(NI, Tcmpfunc125516) (Tpyobject125574* ob1, Tpyobject125574* ob2);
typedef N_CDECL_PTR(Tpyobject125574*, Treprfunc125518) (Tpyobject125574* ob);
typedef N_CDECL_PTR(NI32, Thashfunc125520) (Tpyobject125574* ob);
typedef N_CDECL_PTR(Tpyobject125574*, Tternaryfunc125492) (Tpyobject125574* ob1, Tpyobject125574* ob2, Tpyobject125574* ob3);
typedef N_CDECL_PTR(Tpyobject125574*, Tgetattrofunc125522) (Tpyobject125574* ob1, Tpyobject125574* ob2);
typedef N_CDECL_PTR(NI, Tsetattrofunc125524) (Tpyobject125574* ob1, Tpyobject125574* ob2, Tpyobject125574* ob3);
typedef N_CDECL_PTR(NI, Tvisitproc125536) (Tpyobject125574* ob1, void* p);
typedef N_CDECL_PTR(NI, Ttraverseproc125538) (Tpyobject125574* ob1, Tvisitproc125536 prc, void* p);
typedef N_CDECL_PTR(NI, Tinquiry125494) (Tpyobject125574* ob1);
typedef N_CDECL_PTR(Tpyobject125574*, Trichcmpfunc125540) (Tpyobject125574* ob1, Tpyobject125574* ob2, NI i);
typedef N_CDECL_PTR(Tpyobject125574*, Tgetiterfunc125542) (Tpyobject125574* ob1);
typedef N_CDECL_PTR(Tpyobject125574*, Titernextfunc125544) (Tpyobject125574* ob1);
typedef N_CDECL_PTR(Tpyobject125574*, Tdescrgetfunc125546) (Tpyobject125574* ob1, Tpyobject125574* ob2, Tpyobject125574* ob3);
typedef N_CDECL_PTR(NI, Tdescrsetfunc125548) (Tpyobject125574* ob1, Tpyobject125574* ob2, Tpyobject125574* ob3);
typedef N_CDECL_PTR(NI, Tinitproc125550) (Tpyobject125574* self, Tpyobject125574* args, Tpyobject125574* kwds);
typedef N_CDECL_PTR(Tpyobject125574*, Tallocfunc125554) (Tpytypeobject125626* self, NI nitems);
typedef N_CDECL_PTR(Tpyobject125574*, Tnewfunc125552) (Tpytypeobject125626* subtype, Tpyobject125574* args, Tpyobject125574* kwds);
struct  Tpytypeobject125626  {
  Tpyobject125574 Sup;
NI obsize;
NCSTRING tpname;
NI tpbasicsize;
NI tpitemsize;
Tpydestructor125508 tpdealloc;
Tprintfunc125510 tpprint;
Tgetattrfunc125512 tpgetattr;
Tsetattrfunc125514 tpsetattr;
Tcmpfunc125516 tpcompare;
Treprfunc125518 tprepr;
Tpynumbermethods125556* tpasnumber;
Tpysequencemethods125560* tpassequence;
Tpymappingmethods125564* tpasmapping;
Thashfunc125520 tphash;
Tternaryfunc125492 tpcall;
Treprfunc125518 tpstr;
Tgetattrofunc125522 tpgetattro;
Tsetattrofunc125524 tpsetattro;
Tpybufferprocs125568* tpasbuffer;
NI32 tpflags;
NCSTRING tpdoc;
Ttraverseproc125538 tptraverse;
Tinquiry125494 tpclear;
Trichcmpfunc125540 tprichcompare;
NI32 tpweaklistoffset;
Tgetiterfunc125542 tpiter;
Titernextfunc125544 tpiternext;
Tpymethoddef125586* tpmethods;
Tpymemberdef125590* tpmembers;
Tpygetsetdef125598* tpgetset;
Tpytypeobject125626* tpbase;
Tpyobject125574* tpdict;
Tdescrgetfunc125546 tpdescrget;
Tdescrsetfunc125548 tpdescrset;
NI32 tpdictoffset;
Tinitproc125550 tpinit;
Tallocfunc125554 tpalloc;
Tnewfunc125552 tpnew;
Tpydestructor125508 tpfree;
Tinquiry125494 tpisgc;
Tpyobject125574* tpbases;
Tpyobject125574* tpmro;
Tpyobject125574* tpcache;
Tpyobject125574* tpsubclasses;
Tpyobject125574* tpweaklist;
void* tpxxx7;
void* tpxxx8;
};
typedef N_CDECL_PTR(Tpyobject125574*, Tbinaryfunc125490) (Tpyobject125574* ob1, Tpyobject125574* ob2);
typedef N_CDECL_PTR(Tpyobject125574*, Tunaryfunc125488) (Tpyobject125574* ob1);
typedef N_CDECL_PTR(NI, Tcoercion125496) (Tpyobject125574** ob1, Tpyobject125574** ob2);
struct  Tpynumbermethods125556  {
Tbinaryfunc125490 nbadd;
Tbinaryfunc125490 nbsubstract;
Tbinaryfunc125490 nbmultiply;
Tbinaryfunc125490 nbdivide;
Tbinaryfunc125490 nbremainder;
Tbinaryfunc125490 nbdivmod;
Tternaryfunc125492 nbpower;
Tunaryfunc125488 nbnegative;
Tunaryfunc125488 nbpositive;
Tunaryfunc125488 nbabsolute;
Tinquiry125494 nbnonzero;
Tunaryfunc125488 nbinvert;
Tbinaryfunc125490 nblshift;
Tbinaryfunc125490 nbrshift;
Tbinaryfunc125490 nband;
Tbinaryfunc125490 nbxor;
Tbinaryfunc125490 nbor;
Tcoercion125496 nbcoerce;
Tunaryfunc125488 nbint;
Tunaryfunc125488 nblong;
Tunaryfunc125488 nbfloat;
Tunaryfunc125488 nboct;
Tunaryfunc125488 nbhex;
Tbinaryfunc125490 nbinplaceadd;
Tbinaryfunc125490 nbinplacesubtract;
Tbinaryfunc125490 nbinplacemultiply;
Tbinaryfunc125490 nbinplacedivide;
Tbinaryfunc125490 nbinplaceremainder;
Tternaryfunc125492 nbinplacepower;
Tbinaryfunc125490 nbinplacelshift;
Tbinaryfunc125490 nbinplacershift;
Tbinaryfunc125490 nbinplaceand;
Tbinaryfunc125490 nbinplacexor;
Tbinaryfunc125490 nbinplaceor;
Tbinaryfunc125490 nbfloordivide;
Tbinaryfunc125490 nbtruedivide;
Tbinaryfunc125490 nbinplacefloordivide;
Tbinaryfunc125490 nbinplacetruedivide;
};
typedef N_CDECL_PTR(Tpyobject125574*, Tintargfunc125498) (Tpyobject125574* ob1, NI i);
typedef N_CDECL_PTR(Tpyobject125574*, Tintintargfunc125500) (Tpyobject125574* ob1, NI i1, NI i2);
typedef N_CDECL_PTR(NI, Tintobjargproc125502) (Tpyobject125574* ob1, NI i, Tpyobject125574* ob2);
typedef N_CDECL_PTR(NI, Tintintobjargproc125504) (Tpyobject125574* ob1, NI i1, NI i2, Tpyobject125574* ob2);
typedef N_CDECL_PTR(NI, Tobjobjproc125534) (Tpyobject125574* ob1, Tpyobject125574* ob2);
struct  Tpysequencemethods125560  {
Tinquiry125494 sqlength;
Tbinaryfunc125490 sqconcat;
Tintargfunc125498 sqrepeat;
Tintargfunc125498 sqitem;
Tintintargfunc125500 sqslice;
Tintobjargproc125502 sqassitem;
Tintintobjargproc125504 sqassslice;
Tobjobjproc125534 sqcontains;
Tbinaryfunc125490 sqinplaceconcat;
Tintargfunc125498 sqinplacerepeat;
};
typedef N_CDECL_PTR(NI, Tobjobjargproc125506) (Tpyobject125574* ob1, Tpyobject125574* ob2, Tpyobject125574* ob3);
struct  Tpymappingmethods125564  {
Tinquiry125494 mplength;
Tbinaryfunc125490 mpsubscript;
Tobjobjargproc125506 mpasssubscript;
};
typedef N_CDECL_PTR(NI, Tgetreadbufferproc125526) (Tpyobject125574* ob1, NI i, void* p);
typedef N_CDECL_PTR(NI, Tgetwritebufferproc125528) (Tpyobject125574* ob1, NI i, void* p);
typedef N_CDECL_PTR(NI, Tgetsegcountproc125530) (Tpyobject125574* ob1, NI i);
typedef N_CDECL_PTR(NI, Tgetcharbufferproc125532) (Tpyobject125574* ob1, NI i, NCSTRING pstr);
struct  Tpybufferprocs125568  {
Tgetreadbufferproc125526 bfgetreadbuffer;
Tgetwritebufferproc125528 bfgetwritebuffer;
Tgetsegcountproc125530 bfgetsegcount;
Tgetcharbufferproc125532 bfgetcharbuffer;
};
typedef N_CDECL_PTR(Tpyobject125574*, Tpycfunction125486) (Tpyobject125574* self, Tpyobject125574* args);
struct  Tpymethoddef125586  {
NCSTRING mlname;
Tpycfunction125486 mlmeth;
NI mlflags;
NCSTRING mldoc;
};
struct  Tpymemberdef125590  {
NCSTRING name;
NI thetype;
NI offset;
NI flags;
NCSTRING doc;
};
typedef N_CDECL_PTR(Tpyobject125574*, Tgetter125592) (Tpyobject125574* obj, void* context);
typedef N_CDECL_PTR(NI, Tsetter125594) (Tpyobject125574* obj, Tpyobject125574* value, void* context);
struct  Tpygetsetdef125598  {
NCSTRING name;
Tgetter125592 get;
Tsetter125594 setter;
NCSTRING doc;
void* closure;
};
struct TY132605 {
  TGenericSeq Sup;
  NI data[SEQ_DECL_SIZE];
};
struct TY130058 {
  TGenericSeq Sup;
  Tpyobject125574* data[SEQ_DECL_SIZE];
};
N_NIMCALL(TY132605*, newseq_132600)(NI len);
N_NIMCALL(void, testreadingwritingvars_132004)(void);
static N_INLINE(void, HEX5BHEX5DHEX3D_132007)(PythondictHEX3Aobjecttype130025* p, NimStringDesc* index, NF val);
static N_INLINE(void, setitem_132017)(PythondictHEX3Aobjecttype130025* p, NimStringDesc* index, NF val);
static N_INLINE(Tpyobject125574*, pythonify_130191)(NF x);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_23601)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(NF, asfloat_130354)(Tpyobject125574* x);
N_NIMCALL(NIM_BOOL, Pyfloatcheck_128102)(Tpyobject125574* obj);
static N_INLINE(Tpyobject125574*, HEX5BHEX5D_131477)(PythondictHEX3Aobjecttype130025* p, NimStringDesc* index);
static N_INLINE(Tpyobject125574*, getitem_131452)(PythondictHEX3Aobjecttype130025* p, NimStringDesc* index);
N_NIMCALL(void, failedassertimpl_91603)(NimStringDesc* msg);
N_NIMCALL(void, testreadingvars_132209)(void);
N_NIMCALL(void, testreadingwritingarrays_132408)(void);
static N_INLINE(void, HEX5BHEX5DHEX3D_132540)(PythondictHEX3Aobjecttype130025* p, NimStringDesc* index, PythonlistHEX3Aobjecttype130011* val);
static N_INLINE(void, setitem_132550)(PythondictHEX3Aobjecttype130025* p, NimStringDesc* index, PythonlistHEX3Aobjecttype130011* val);
static N_INLINE(PythonlistHEX3Aobjecttype130011*, pythonify_132560)(PythonlistHEX3Aobjecttype130011* x);
static N_INLINE(PythonlistHEX3Aobjecttype130011*, pythonify_132427)(NI* data, NI dataLen0);
static N_INLINE(PythonlistHEX3Aobjecttype130011*, newpythonlist_130742)(NI size);
N_NIMCALL(Tpyobject125574*, addreference_130098)(Tpyobject125574* obj);
N_NOINLINE(void, raiseIndexError)(void);
static N_INLINE(void, HEX5BHEX5DHEX3D_132485)(PythonlistHEX3Aobjecttype130011** p, NI index, Tpyobject125574* val);
static N_INLINE(void, setitem_132495)(PythonlistHEX3Aobjecttype130011** p, NI index, Tpyobject125574* val);
static N_INLINE(Tpyobject125574*, pythonify_132505)(Tpyobject125574* x);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
static N_INLINE(Tpyobject125574*, pythonify_130214)(NI x);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(TY132605*, aslist_132579)(Tpyobject125574* obj);
static N_INLINE(TY132605*, aslist_132590)(PythonlistHEX3Aobjecttype130011* obj);
static N_INLINE(NI, len_130837)(PythonlistHEX3Aobjecttype130011* p);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NIMCALL(NI, depythonify_132825)(Tpyobject125574* x);
static N_INLINE(Tpyobject125574*, HEX5BHEX5D_130880)(PythonlistHEX3Aobjecttype130011* p, NI index);
static N_INLINE(Tpyobject125574*, getitem_130868)(PythonlistHEX3Aobjecttype130011* p, NI index);
N_NIMCALL(TGenericSeq*, incrSeqV2)(TGenericSeq* seq, NI elemsize);
static N_INLINE(PythonlistHEX3Aobjecttype130011*, aspylist_130789)(Tpyobject125574* obj);
static N_INLINE(PythonlistHEX3Aobjecttype130011*, newpythonlist_130719)(Tpyobject125574* obj);
static N_INLINE(NI32, asint_130408)(Tpyobject125574* x);
N_NIMCALL(NIM_BOOL, Pylongcheck_128126)(Tpyobject125574* obj);
N_NIMCALL(NI, mulInt)(NI a, NI b);
N_NIMCALL(void, testreadingarrays_133614)(void);
N_NIMCALL(void, genericSeqAssign)(void* dest, void* src_86204, TNimType* mt);
static N_INLINE(PythonlistHEX3Aobjecttype130011*, pythonify_133634)(NI* data, NI dataLen0);
static N_INLINE(Tpyobject125574*, pythonify_130225)(NI* x);
static N_INLINE(void, HEX5BHEX5DHEX3D_133802)(PythonlistHEX3Aobjecttype130011** p, NI index, NimStringDesc* val);
static N_INLINE(void, setitem_133812)(PythonlistHEX3Aobjecttype130011** p, NI index, NimStringDesc* val);
static N_INLINE(Tpyobject125574*, pythonify_130283)(NimStringDesc* x);
static N_INLINE(Tpyobject125574*, HEX5BHEX5D_130904)(PythonlistHEX3Aobjecttype130011** p, NI index);
static N_INLINE(Tpyobject125574*, getitem_130891)(PythonlistHEX3Aobjecttype130011** p, NI index);
static N_INLINE(NimStringDesc*, asstring_130380)(Tpyobject125574* x);
N_NIMCALL(NIM_BOOL, Pystringcheck_128090)(Tpyobject125574* obj);
N_NIMCALL(NimStringDesc*, cstrToNimstr)(NCSTRING str);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b);
N_NIMCALL(void, testreadingattributes_134407)(void);
static N_INLINE(Tpyobject125574*, HEX5BHEX5D_130684)(PythonobjectattrHEX3Aobjecttype130627* obj, NimStringDesc* attr);
static N_INLINE(Tpyobject125574*, getitem_130671)(PythonobjectattrHEX3Aobjecttype130627* obj, NimStringDesc* attr);
static N_INLINE(PythonobjectattrHEX3Aobjecttype130627*, attrs_130652)(Tpyobject125574* obj);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_NIMCALL(void, testwritingattributes_134811)(void);
static N_INLINE(void, setitem_134867)(PythonobjectattrHEX3Aobjecttype130627* obj, NimStringDesc* attr, NimStringDesc* value);
static N_INLINE(void, HEX5BHEX5DHEX3D_134885)(PythonobjectattrHEX3Aobjecttype130627* obj, NimStringDesc* attr, NimStringDesc* value);
N_NIMCALL(void, release_135612)(Tpyobject125574* op);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_NOINLINE(void, setStackBottom)(void* thestackbottom);
NIM_EXTERNC N_NOINLINE(void, systemInit000)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_parseutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_parseutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_strutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_strutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_etcprivInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_etcprivDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_hashesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_hashesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_timesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_timesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_mathInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_mathDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_tablesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_tablesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_dynlibInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_dynlibDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, python_pythonInit000)(void);
NIM_EXTERNC N_NOINLINE(void, python_pythonDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, pythonize_pythonizeInit000)(void);
NIM_EXTERNC N_NOINLINE(void, pythonize_pythonizeDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, function_testsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, function_testsDatInit000)(void);
STRING_LITERAL(TMP512, "::testReadingWritingVars", 24);
STRING_LITERAL(TMP513, "testVar1", 8);
STRING_LITERAL(TMP514, "asFloat([](cast[PythonDict](pythonEnvironmentObject), \"testVar1"
"\")) == 48.0\'f64 ", 79);
STRING_LITERAL(TMP515, "::testReadingVars", 17);
STRING_LITERAL(TMP516, "asFloat([](cast[PythonDict](pythonEnvironmentObject), \"testVar1"
"\")) == 25.0\'f64 ", 79);
STRING_LITERAL(TMP517, "::testReadingWritingArrays", 26);
STRING_LITERAL(TMP518, "array1", 6);
NIM_CONST struct {
  TGenericSeq Sup;
  NI data[11];
} CNSTSEQ522 = {{11, 11}, {((NI) 1),
((NI) 2),
((NI) 3),
((NI) 4),
((NI) 5),
((NI) 11),
((NI) 7),
((NI) 8),
((NI) 9),
((NI) 10),
((NI) 11)}};
NIM_CONST TY132605* TMP520 = ((TY132605*)&CNSTSEQ522);
STRING_LITERAL(TMP524, "lenArray1", 9);
STRING_LITERAL(TMP525, "asInt([](cast[PythonDict](pythonEnvironmentObject), \"lenArray1\""
")) == len(array1) ", 81);
STRING_LITERAL(TMP526, "arrayPos3", 9);
STRING_LITERAL(TMP528, "asInt([](cast[PythonDict](pythonEnvironmentObject), \"arrayPos3\""
")) ==\012    array1[3] * array1[3] ", 95);
STRING_LITERAL(TMP529, "arrayPos5", 9);
STRING_LITERAL(TMP530, "asInt([](cast[PythonDict](pythonEnvironmentObject), \"arrayPos5\""
")) == array1[5] ", 79);
STRING_LITERAL(TMP531, "arrayLastPos", 12);
STRING_LITERAL(TMP533, "asInt([](cast[PythonDict](pythonEnvironmentObject), \"arrayLastP"
"os\")) ==\012    array1[len(array1) - 1] ", 100);
STRING_LITERAL(TMP534, "::testReadingArrays", 19);
STRING_LITERAL(TMP536, "len(array1) == len(array1) ", 27);
STRING_LITERAL(TMP537, "aaa", 3);
STRING_LITERAL(TMP538, "asInt([](array1, 5)) == innerArray1[5] ", 39);
STRING_LITERAL(TMP539, "true ", 5);
STRING_LITERAL(TMP540, "asString([](array1, 3)) == \"aaa\" ", 33);
STRING_LITERAL(TMP541, "::testReadingAttributes", 23);
STRING_LITERAL(TMP543, "Foo", 3);
STRING_LITERAL(TMP544, "myattribute1", 12);
STRING_LITERAL(TMP545, "1234 ==\012    asInt([](attrs([](cast[PythonDict](pythonEnvironmen"
"tObject), \"Foo\")),\012             \"myattribute1\")) ", 112);
STRING_LITERAL(TMP546, "myattribute2", 12);
STRING_LITERAL(TMP547, "4 ==\012    asList([](attrs([](cast[PythonDict](pythonEnvironmentO"
"bject), \"Foo\")),\012              \"myattribute2\"), int)[3] ", 119);
STRING_LITERAL(TMP548, "::testWritingAttributes", 23);
STRING_LITERAL(TMP549, "myattribute3", 12);
STRING_LITERAL(TMP550, "cdef", 4);
STRING_LITERAL(TMP551, "asFloat([](attrs([](cast[PythonDict](pythonEnvironmentObject), "
"\"Foo\")),\012           \"myattribute1\")) == 1234.5\'f64 ", 114);
STRING_LITERAL(TMP552, "asInt([](asPyList([](attrs([](cast[PythonDict](pythonEnvironmen"
"tObject), \"Foo\")),\012                     \"myattribute2\")), 2)) =="
" 3 ", 130);
STRING_LITERAL(TMP553, "asString([](attrs([](cast[PythonDict](pythonEnvironmentObject),"
" \"Foo\")),\012            \"myattribute3\")) == \"cdef\" ", 112);
STRING_LITERAL(TMP555, "len(a) == L seq modified while iterating over it", 48);
extern TY126655 Dl_126654;
extern TY126833 Dl_126832;
extern TFrame* frameptr_20842;
extern Tpyobject125574* pythonenvironmentobject_130069;
extern TY126681 Dl_126680;
extern TY126509 Dl_126508;
extern TY126827 Dl_126826;
extern TY126648 Dl_126647;
extern TY126953 Dl_126952;
extern TY126965 Dl_126964;
extern TY127047 Dl_127046;
extern TY126982 Dl_126981;
extern TY126930 Dl_126929;
extern TY127000 Dl_126999;
extern TY127018 Dl_127017;
extern TY126696 Dl_126695;
extern TY127370 Dl_127369;
extern TNimType NTI132605; /* seq[int] */
extern TY126702 Dl_126701;
extern TY127324 Dl_127323;
extern TNimType NTI130626; /* PythonObjectAttr */
extern TY127384 Dl_127383;
Tpyobject125574* pythonref_135426;
extern TY130058* pythonreferences_130059;
extern TY127892 Dl_127891;

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_20842 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_20842).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_20842;
	frameptr_20842 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_23601();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_20842 = (*frameptr_20842).prev;
}

static N_INLINE(Tpyobject125574*, pythonify_130191)(NF x) {
	Tpyobject125574* result;
	Tpyobject125574* LOC1;
	nimfr("pythonify", "pythonize.nim")
	result = 0;
	nimln(99, "pythonize.nim");
	LOC1 = 0;
	LOC1 = Dl_126832(x);
	result = ((Tpyobject125574*) (LOC1));
	popFrame();
	return result;
}

static N_INLINE(void, setitem_132017)(PythondictHEX3Aobjecttype130025* p, NimStringDesc* index, NF val) {
	Tpyobject125574* LOC1;
	NI LOC2;
	nimfr("setItem", "pythonize.nim")
	nimln(545, "pythonize.nim");
	LOC1 = 0;
	LOC1 = pythonify_130191(val);
	LOC2 = 0;
	LOC2 = Dl_126654(((Tpyobject125574*) (p)), index->data, ((Tpyobject125574*) (LOC1)));
	popFrame();
}

static N_INLINE(void, HEX5BHEX5DHEX3D_132007)(PythondictHEX3Aobjecttype130025* p, NimStringDesc* index, NF val) {
	nimfr("[]=", "pythonize.nim")
	nimln(548, "pythonize.nim");
	setitem_132017(p, index, val);
	popFrame();
}

static N_INLINE(NF, asfloat_130354)(Tpyobject125574* x) {
	NF result;
	nimfr("asFloat", "pythonize.nim")
{	result = 0;
	nimln(133, "pythonize.nim");
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = Pyfloatcheck_128102(((Tpyobject125574*) (x)));
		if (!LOC3) goto LA4;
		result = Dl_126826(((Tpyobject125574*) (x)));
		goto BeforeRet;
	}
	LA4: ;
	nimln(134, "pythonize.nim");
	result = NAN;
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result;
}

static N_INLINE(Tpyobject125574*, getitem_131452)(PythondictHEX3Aobjecttype130025* p, NimStringDesc* index) {
	Tpyobject125574* result;
	nimfr("getItem", "pythonize.nim")
	result = 0;
	nimln(530, "pythonize.nim");
	result = Dl_126647(((Tpyobject125574*) (p)), index->data);
	popFrame();
	return result;
}

static N_INLINE(Tpyobject125574*, HEX5BHEX5D_131477)(PythondictHEX3Aobjecttype130025* p, NimStringDesc* index) {
	Tpyobject125574* result;
	nimfr("[]", "pythonize.nim")
	result = 0;
	nimln(533, "pythonize.nim");
	result = getitem_131452(p, index);
	popFrame();
	return result;
}

N_NIMCALL(void, testreadingwritingvars_132004)(void) {
	nimfr("testReadingWritingVars", "function_tests.nim")
	nimln(5, "function_tests.nim");
	HEX5BHEX5DHEX3D_132007(((PythondictHEX3Aobjecttype130025*) (pythonenvironmentobject_130069)), ((NimStringDesc*) &TMP513), 1.2000000000000000e+01);
	nimln(70, "pythonize.nim");
	{
		Tpyobject125574* LOC3;
		LOC3 = 0;
		LOC3 = Dl_126680("testVar1 *= 4", ((NI) 257), pythonenvironmentobject_130069, pythonenvironmentobject_130069);
		if (!LOC3 == 0) goto LA4;
		nimln(71, "pythonize.nim");
		Dl_126508();
	}
	LA4: ;
	nimln(7, "function_tests.nim");
	{
		Tpyobject125574* LOC8;
		NF LOC9;
		LOC8 = 0;
		LOC8 = HEX5BHEX5D_131477(((PythondictHEX3Aobjecttype130025*) (pythonenvironmentobject_130069)), ((NimStringDesc*) &TMP513));
		LOC9 = 0;
		LOC9 = asfloat_130354(LOC8);
		if (!!((LOC9 == 4.8000000000000000e+01))) goto LA10;
		failedassertimpl_91603(((NimStringDesc*) &TMP514));
	}
	LA10: ;
	popFrame();
}

N_NIMCALL(void, testreadingvars_132209)(void) {
	nimfr("testReadingVars", "function_tests.nim")
	nimln(70, "pythonize.nim");
	{
		Tpyobject125574* LOC3;
		LOC3 = 0;
		LOC3 = Dl_126680("testVar1 = 25.0", ((NI) 257), pythonenvironmentobject_130069, pythonenvironmentobject_130069);
		if (!LOC3 == 0) goto LA4;
		nimln(71, "pythonize.nim");
		Dl_126508();
	}
	LA4: ;
	nimln(11, "function_tests.nim");
	{
		Tpyobject125574* LOC8;
		NF LOC9;
		LOC8 = 0;
		LOC8 = HEX5BHEX5D_131477(((PythondictHEX3Aobjecttype130025*) (pythonenvironmentobject_130069)), ((NimStringDesc*) &TMP513));
		LOC9 = 0;
		LOC9 = asfloat_130354(LOC8);
		if (!!((LOC9 == 2.5000000000000000e+01))) goto LA10;
		failedassertimpl_91603(((NimStringDesc*) &TMP516));
	}
	LA10: ;
	popFrame();
}

static N_INLINE(PythonlistHEX3Aobjecttype130011*, pythonify_132560)(PythonlistHEX3Aobjecttype130011* x) {
	PythonlistHEX3Aobjecttype130011* result;
	nimfr("pythonify", "pythonize.nim")
	result = 0;
	nimln(97, "pythonize.nim");
	result = x;
	popFrame();
	return result;
}

static N_INLINE(void, setitem_132550)(PythondictHEX3Aobjecttype130025* p, NimStringDesc* index, PythonlistHEX3Aobjecttype130011* val) {
	PythonlistHEX3Aobjecttype130011* LOC1;
	NI LOC2;
	nimfr("setItem", "pythonize.nim")
	nimln(545, "pythonize.nim");
	LOC1 = 0;
	LOC1 = pythonify_132560(val);
	LOC2 = 0;
	LOC2 = Dl_126654(((Tpyobject125574*) (p)), index->data, ((Tpyobject125574*) (LOC1)));
	popFrame();
}

static N_INLINE(void, HEX5BHEX5DHEX3D_132540)(PythondictHEX3Aobjecttype130025* p, NimStringDesc* index, PythonlistHEX3Aobjecttype130011* val) {
	nimfr("[]=", "pythonize.nim")
	nimln(548, "pythonize.nim");
	setitem_132550(p, index, val);
	popFrame();
}

static N_INLINE(PythonlistHEX3Aobjecttype130011*, newpythonlist_130742)(NI size) {
	PythonlistHEX3Aobjecttype130011* result;
	Tpyobject125574* LOC1;
	Tpyobject125574* LOC2;
	nimfr("newPythonList", "pythonize.nim")
	result = 0;
	nimln(276, "pythonize.nim");
	LOC1 = 0;
	LOC1 = Dl_126952(size);
	LOC2 = 0;
	LOC2 = addreference_130098(((Tpyobject125574*) (LOC1)));
	result = ((PythonlistHEX3Aobjecttype130011*) (LOC2));
	popFrame();
	return result;
}

static N_INLINE(Tpyobject125574*, pythonify_132505)(Tpyobject125574* x) {
	Tpyobject125574* result;
	nimfr("pythonify", "pythonize.nim")
	result = 0;
	nimln(97, "pythonize.nim");
	result = x;
	popFrame();
	return result;
}

static N_INLINE(void, setitem_132495)(PythonlistHEX3Aobjecttype130011** p, NI index, Tpyobject125574* val) {
	Tpyobject125574* LOC1;
	NI LOC2;
	nimfr("setItem", "pythonize.nim")
	nimln(340, "pythonize.nim");
	LOC1 = 0;
	LOC1 = pythonify_132505(val);
	LOC2 = 0;
	LOC2 = Dl_126964(((Tpyobject125574*) ((*p))), ((NI) (index)), ((Tpyobject125574*) (LOC1)));
	popFrame();
}

static N_INLINE(void, HEX5BHEX5DHEX3D_132485)(PythonlistHEX3Aobjecttype130011** p, NI index, Tpyobject125574* val) {
	nimfr("[]=", "pythonize.nim")
	nimln(342, "pythonize.nim");
	setitem_132495(p, index, val);
	popFrame();
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = 0;
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (a <= i);
		if (!(LOC3)) goto LA4;
		LOC3 = (i <= b);
		LA4: ;
		if (!LOC3) goto LA5;
		result = i;
		goto BeforeRet;
	}
	goto LA1;
	LA5: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1: ;
	}BeforeRet: ;
	return result;
}

static N_INLINE(Tpyobject125574*, pythonify_130214)(NI x) {
	Tpyobject125574* result;
	Tpyobject125574* LOC1;
	nimfr("pythonify", "pythonize.nim")
	result = 0;
	nimln(107, "pythonize.nim");
	LOC1 = 0;
	LOC1 = Dl_127046(((NI64) (x)));
	result = ((Tpyobject125574*) (LOC1));
	popFrame();
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = 0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (((NI) 0) <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result;
}

static N_INLINE(PythonlistHEX3Aobjecttype130011*, pythonify_132427)(NI* data, NI dataLen0) {
	PythonlistHEX3Aobjecttype130011* result;
	nimfr("pythonify", "pythonize.nim")
	result = 0;
	nimln(287, "pythonize.nim");
	result = newpythonlist_130742(dataLen0);
	{
		NI index_132482;
		NI value_132483;
		NI i_132526;
		index_132482 = 0;
		value_132483 = 0;
		nimln(2031, "system.nim");
		i_132526 = ((NI) 0);
		{
			nimln(2032, "system.nim");
			while (1) {
				Tpyobject125574* LOC4;
				NI TMP519;
				if (!(i_132526 < dataLen0)) goto LA3;
				nimln(2031, "system.nim");
				index_132482 = i_132526;
				nimln(2033, "system.nim");
				if ((NU)(i_132526) >= (NU)(dataLen0)) raiseIndexError();
				value_132483 = data[i_132526];
				nimln(289, "pythonize.nim");
				LOC4 = 0;
				LOC4 = pythonify_130214(value_132483);
				HEX5BHEX5DHEX3D_132485(&result, ((NI)chckRange(index_132482, ((NI) 0), ((NI) IL64(9223372036854775807)))), LOC4);
				nimln(2034, "system.nim");
				TMP519 = addInt(i_132526, ((NI) 1));
				i_132526 = (NI)(TMP519);
			} LA3: ;
		}
	}
	popFrame();
	return result;
}

static N_INLINE(NI, len_130837)(PythonlistHEX3Aobjecttype130011* p) {
	NI result;
	NI LOC1;
	nimfr("len", "pythonize.nim")
	result = 0;
	nimln(310, "pythonize.nim");
	LOC1 = 0;
	LOC1 = Dl_126981(((Tpyobject125574*) (p)));
	result = ((NI)chckRange(LOC1, ((NI) 0), ((NI) IL64(9223372036854775807))));
	popFrame();
	return result;
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = 0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (((NI) 0) <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result;
}

static N_INLINE(Tpyobject125574*, getitem_130868)(PythonlistHEX3Aobjecttype130011* p, NI index) {
	Tpyobject125574* result;
	nimfr("getItem", "pythonize.nim")
	result = 0;
	nimln(325, "pythonize.nim");
	result = Dl_126929(((Tpyobject125574*) (p)), ((NI) (index)));
	popFrame();
	return result;
}

static N_INLINE(Tpyobject125574*, HEX5BHEX5D_130880)(PythonlistHEX3Aobjecttype130011* p, NI index) {
	Tpyobject125574* result;
	nimfr("[]", "pythonize.nim")
	result = 0;
	nimln(327, "pythonize.nim");
	result = getitem_130868(p, index);
	popFrame();
	return result;
}

static N_INLINE(TY132605*, aslist_132590)(PythonlistHEX3Aobjecttype130011* obj) {
	TY132605* result;
	nimfr("asList", "pythonize.nim")
	result = 0;
	nimln(300, "pythonize.nim");
	result = newseq_132600(((NI) 0));
	{
		NI i_132823;
		NI HEX3Atmp_132849;
		NI LOC2;
		NI TMP522;
		NI res_132852;
		i_132823 = 0;
		HEX3Atmp_132849 = 0;
		nimln(301, "pythonize.nim");
		LOC2 = 0;
		LOC2 = len_130837(obj);
		TMP522 = subInt(((NI) (LOC2)), ((NI) 1));
		HEX3Atmp_132849 = (NI)(TMP522);
		nimln(1874, "system.nim");
		res_132852 = ((NI) 0);
		{
			nimln(1875, "system.nim");
			while (1) {
				Tpyobject125574* LOC5;
				NI LOC6;
				NI TMP523;
				if (!(res_132852 <= ((NI) (HEX3Atmp_132849)))) goto LA4;
				nimln(1876, "system.nim");
				i_132823 = ((NI)chckRange(res_132852, ((NI) -1), ((NI) IL64(9223372036854775806))));
				nimln(302, "pythonize.nim");
				LOC5 = 0;
				LOC5 = HEX5BHEX5D_130880(obj, ((NI)chckRange(i_132823, ((NI) 0), ((NI) IL64(9223372036854775807)))));
				LOC6 = 0;
				LOC6 = depythonify_132825(LOC5);
				result = (TY132605*) incrSeqV2(&(result)->Sup, sizeof(NI));
				result->data[result->Sup.len] = ((NI) (LOC6));
				++result->Sup.len;
				nimln(1890, "system.nim");
				TMP523 = addInt(res_132852, ((NI) 1));
				res_132852 = (NI)(TMP523);
			} LA4: ;
		}
	}
	popFrame();
	return result;
}

static N_INLINE(PythonlistHEX3Aobjecttype130011*, newpythonlist_130719)(Tpyobject125574* obj) {
	PythonlistHEX3Aobjecttype130011* result;
	Tpyobject125574* LOC1;
	nimfr("newPythonList", "pythonize.nim")
	result = 0;
	nimln(264, "pythonize.nim");
	LOC1 = 0;
	LOC1 = addreference_130098(obj);
	result = ((PythonlistHEX3Aobjecttype130011*) (LOC1));
	popFrame();
	return result;
}

static N_INLINE(PythonlistHEX3Aobjecttype130011*, aspylist_130789)(Tpyobject125574* obj) {
	PythonlistHEX3Aobjecttype130011* result;
	nimfr("asPyList", "pythonize.nim")
	result = 0;
	nimln(294, "pythonize.nim");
	result = newpythonlist_130719(obj);
	popFrame();
	return result;
}

static N_INLINE(TY132605*, aslist_132579)(Tpyobject125574* obj) {
	TY132605* result;
	PythonlistHEX3Aobjecttype130011* LOC1;
	nimfr("asList", "pythonize.nim")
	result = 0;
	nimln(305, "pythonize.nim");
	LOC1 = 0;
	LOC1 = aspylist_130789(obj);
	result = aslist_132590(LOC1);
	popFrame();
	return result;
}

static N_INLINE(NI32, asint_130408)(Tpyobject125574* x) {
	NI32 result;
	Tpyobject125574* LOC6;
	NCSTRING LOC7;
	Tpyobject125574* LOC8;
	nimfr("asInt", "pythonize.nim")
{	result = 0;
	nimln(149, "pythonize.nim");
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = Pylongcheck_128126(((Tpyobject125574*) (x)));
		if (!LOC3) goto LA4;
		result = Dl_126999(((Tpyobject125574*) (x)));
		goto BeforeRet;
	}
	LA4: ;
	nimln(150, "pythonize.nim");
	LOC6 = 0;
	LOC6 = Dl_127369(((Tpyobject125574*) (x)));
	LOC7 = 0;
	LOC7 = Dl_126695(LOC6);
	LOC8 = 0;
	LOC8 = Dl_127017(LOC7, ((NCSTRING*) (NIM_NIL)), ((NI) 10));
	result = Dl_126999(LOC8);
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(void, testreadingwritingarrays_132408)(void) {
	PythonlistHEX3Aobjecttype130011* LOC1;
	TY132605* array1;
	Tpyobject125574* LOC2;
	nimfr("testReadingWritingArrays", "function_tests.nim")
	nimln(14, "function_tests.nim");
	LOC1 = 0;
	LOC1 = pythonify_132427(TMP520->data, TMP520->Sup.len);
	HEX5BHEX5DHEX3D_132540(((PythondictHEX3Aobjecttype130025*) (pythonenvironmentobject_130069)), ((NimStringDesc*) &TMP518), LOC1);
	nimln(15, "function_tests.nim");
	LOC2 = 0;
	LOC2 = HEX5BHEX5D_131477(((PythondictHEX3Aobjecttype130025*) (pythonenvironmentobject_130069)), ((NimStringDesc*) &TMP518));
	array1 = aslist_132579(LOC2);
	nimln(70, "pythonize.nim");
	{
		Tpyobject125574* LOC5;
		LOC5 = 0;
		LOC5 = Dl_126680("lenArray1 = len(array1)", ((NI) 257), pythonenvironmentobject_130069, pythonenvironmentobject_130069);
		if (!LOC5 == 0) goto LA6;
		nimln(71, "pythonize.nim");
		Dl_126508();
	}
	LA6: ;
	nimln(70, "pythonize.nim");
	{
		Tpyobject125574* LOC10;
		LOC10 = 0;
		LOC10 = Dl_126680("array1[3] = array1[3]**2", ((NI) 257), pythonenvironmentobject_130069, pythonenvironmentobject_130069);
		if (!LOC10 == 0) goto LA11;
		nimln(71, "pythonize.nim");
		Dl_126508();
	}
	LA11: ;
	nimln(70, "pythonize.nim");
	{
		Tpyobject125574* LOC15;
		LOC15 = 0;
		LOC15 = Dl_126680("arrayPos5 = array1[5]", ((NI) 257), pythonenvironmentobject_130069, pythonenvironmentobject_130069);
		if (!LOC15 == 0) goto LA16;
		nimln(71, "pythonize.nim");
		Dl_126508();
	}
	LA16: ;
	nimln(70, "pythonize.nim");
	{
		Tpyobject125574* LOC20;
		LOC20 = 0;
		LOC20 = Dl_126680("arrayPos3 = array1[3]", ((NI) 257), pythonenvironmentobject_130069, pythonenvironmentobject_130069);
		if (!LOC20 == 0) goto LA21;
		nimln(71, "pythonize.nim");
		Dl_126508();
	}
	LA21: ;
	nimln(70, "pythonize.nim");
	{
		Tpyobject125574* LOC25;
		LOC25 = 0;
		LOC25 = Dl_126680("arrayLastPos = array1[-1]", ((NI) 257), pythonenvironmentobject_130069, pythonenvironmentobject_130069);
		if (!LOC25 == 0) goto LA26;
		nimln(71, "pythonize.nim");
		Dl_126508();
	}
	LA26: ;
	nimln(70, "pythonize.nim");
	{
		Tpyobject125574* LOC30;
		LOC30 = 0;
		LOC30 = Dl_126680("import math", ((NI) 257), pythonenvironmentobject_130069, pythonenvironmentobject_130069);
		if (!LOC30 == 0) goto LA31;
		nimln(71, "pythonize.nim");
		Dl_126508();
	}
	LA31: ;
	nimln(22, "function_tests.nim");
	{
		Tpyobject125574* LOC35;
		NI32 LOC36;
		LOC35 = 0;
		LOC35 = HEX5BHEX5D_131477(((PythondictHEX3Aobjecttype130025*) (pythonenvironmentobject_130069)), ((NimStringDesc*) &TMP524));
		LOC36 = 0;
		LOC36 = asint_130408(LOC35);
		if (!!((((NI) (LOC36)) == (array1 ? array1->Sup.len : 0)))) goto LA37;
		failedassertimpl_91603(((NimStringDesc*) &TMP525));
	}
	LA37: ;
	nimln(23, "function_tests.nim");
	{
		Tpyobject125574* LOC41;
		NI32 LOC42;
		NI TMP527;
		LOC41 = 0;
		LOC41 = HEX5BHEX5D_131477(((PythondictHEX3Aobjecttype130025*) (pythonenvironmentobject_130069)), ((NimStringDesc*) &TMP526));
		LOC42 = 0;
		LOC42 = asint_130408(LOC41);
		if ((NU)(((NI) 3)) >= (NU)(array1->Sup.len)) raiseIndexError();
		if ((NU)(((NI) 3)) >= (NU)(array1->Sup.len)) raiseIndexError();
		TMP527 = mulInt(array1->data[((NI) 3)], array1->data[((NI) 3)]);
		if (!!((((NI) (LOC42)) == (NI)(TMP527)))) goto LA43;
		failedassertimpl_91603(((NimStringDesc*) &TMP528));
	}
	LA43: ;
	nimln(24, "function_tests.nim");
	{
		Tpyobject125574* LOC47;
		NI32 LOC48;
		LOC47 = 0;
		LOC47 = HEX5BHEX5D_131477(((PythondictHEX3Aobjecttype130025*) (pythonenvironmentobject_130069)), ((NimStringDesc*) &TMP529));
		LOC48 = 0;
		LOC48 = asint_130408(LOC47);
		if ((NU)(((NI) 5)) >= (NU)(array1->Sup.len)) raiseIndexError();
		if (!!((((NI) (LOC48)) == array1->data[((NI) 5)]))) goto LA49;
		failedassertimpl_91603(((NimStringDesc*) &TMP530));
	}
	LA49: ;
	nimln(25, "function_tests.nim");
	{
		Tpyobject125574* LOC53;
		NI32 LOC54;
		NI TMP532;
		LOC53 = 0;
		LOC53 = HEX5BHEX5D_131477(((PythondictHEX3Aobjecttype130025*) (pythonenvironmentobject_130069)), ((NimStringDesc*) &TMP531));
		LOC54 = 0;
		LOC54 = asint_130408(LOC53);
		TMP532 = subInt((array1 ? array1->Sup.len : 0), ((NI) 1));
		if ((NU)((NI)(TMP532)) >= (NU)(array1->Sup.len)) raiseIndexError();
		if (!!((((NI) (LOC54)) == array1->data[(NI)(TMP532)]))) goto LA55;
		failedassertimpl_91603(((NimStringDesc*) &TMP533));
	}
	LA55: ;
	popFrame();
}

static N_INLINE(Tpyobject125574*, pythonify_130225)(NI* x) {
	Tpyobject125574* result;
	Tpyobject125574* LOC1;
	nimfr("pythonify", "pythonize.nim")
	result = 0;
	nimln(109, "pythonize.nim");
	LOC1 = 0;
	LOC1 = Dl_127046(((NI64) ((*x))));
	result = ((Tpyobject125574*) (LOC1));
	popFrame();
	return result;
}

static N_INLINE(PythonlistHEX3Aobjecttype130011*, pythonify_133634)(NI* data, NI dataLen0) {
	PythonlistHEX3Aobjecttype130011* result;
	nimfr("pythonify", "pythonize.nim")
	result = 0;
	nimln(282, "pythonize.nim");
	result = newpythonlist_130742(dataLen0);
	{
		NI index_133695;
		NI* value_133696;
		NI i_133711;
		index_133695 = 0;
		value_133696 = 0;
		nimln(2039, "system.nim");
		i_133711 = ((NI) 0);
		{
			nimln(2040, "system.nim");
			while (1) {
				Tpyobject125574* LOC4;
				NI TMP535;
				if (!(i_133711 < dataLen0)) goto LA3;
				nimln(2039, "system.nim");
				index_133695 = i_133711;
				nimln(2041, "system.nim");
				if ((NU)(i_133711) >= (NU)(dataLen0)) raiseIndexError();
				value_133696 = (&data[i_133711]);
				nimln(284, "pythonize.nim");
				LOC4 = 0;
				LOC4 = pythonify_130225(value_133696);
				HEX5BHEX5DHEX3D_132485(&result, ((NI)chckRange(index_133695, ((NI) 0), ((NI) IL64(9223372036854775807)))), LOC4);
				nimln(2042, "system.nim");
				TMP535 = addInt(i_133711, ((NI) 1));
				i_133711 = (NI)(TMP535);
			} LA3: ;
		}
	}
	popFrame();
	return result;
}

static N_INLINE(Tpyobject125574*, pythonify_130283)(NimStringDesc* x) {
	Tpyobject125574* result;
	Tpyobject125574* LOC1;
	nimfr("pythonify", "pythonize.nim")
	result = 0;
	nimln(119, "pythonize.nim");
	LOC1 = 0;
	LOC1 = Dl_126701(x->data);
	result = ((Tpyobject125574*) (LOC1));
	popFrame();
	return result;
}

static N_INLINE(void, setitem_133812)(PythonlistHEX3Aobjecttype130011** p, NI index, NimStringDesc* val) {
	Tpyobject125574* LOC1;
	NI LOC2;
	nimfr("setItem", "pythonize.nim")
	nimln(340, "pythonize.nim");
	LOC1 = 0;
	LOC1 = pythonify_130283(val);
	LOC2 = 0;
	LOC2 = Dl_126964(((Tpyobject125574*) ((*p))), ((NI) (index)), ((Tpyobject125574*) (LOC1)));
	popFrame();
}

static N_INLINE(void, HEX5BHEX5DHEX3D_133802)(PythonlistHEX3Aobjecttype130011** p, NI index, NimStringDesc* val) {
	nimfr("[]=", "pythonize.nim")
	nimln(342, "pythonize.nim");
	setitem_133812(p, index, val);
	popFrame();
}

static N_INLINE(Tpyobject125574*, getitem_130891)(PythonlistHEX3Aobjecttype130011** p, NI index) {
	Tpyobject125574* result;
	nimfr("getItem", "pythonize.nim")
	result = 0;
	nimln(329, "pythonize.nim");
	result = Dl_126929(((Tpyobject125574*) ((*p))), ((NI) (index)));
	popFrame();
	return result;
}

static N_INLINE(Tpyobject125574*, HEX5BHEX5D_130904)(PythonlistHEX3Aobjecttype130011** p, NI index) {
	Tpyobject125574* result;
	nimfr("[]", "pythonize.nim")
	result = 0;
	nimln(331, "pythonize.nim");
	result = getitem_130891(p, index);
	popFrame();
	return result;
}

static N_INLINE(NimStringDesc*, asstring_130380)(Tpyobject125574* x) {
	NimStringDesc* result;
	Tpyobject125574* LOC7;
	NCSTRING LOC8;
	nimfr("asString", "pythonize.nim")
{	result = 0;
	nimln(141, "pythonize.nim");
	{
		NIM_BOOL LOC3;
		NCSTRING LOC6;
		LOC3 = 0;
		LOC3 = Pystringcheck_128090(((Tpyobject125574*) (x)));
		if (!LOC3) goto LA4;
		LOC6 = 0;
		LOC6 = Dl_126695(((Tpyobject125574*) (x)));
		result = cstrToNimstr(LOC6);
		goto BeforeRet;
	}
	LA4: ;
	nimln(142, "pythonize.nim");
	LOC7 = 0;
	LOC7 = Dl_127369(((Tpyobject125574*) (x)));
	LOC8 = 0;
	LOC8 = Dl_126695(LOC7);
	result = cstrToNimstr(LOC8);
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result;
}

static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b) {
	NIM_BOOL result;
	NIM_BOOL LOC11;
	int LOC13;
{	result = 0;
	{
		if (!(a == b)) goto LA3;
		result = NIM_TRUE;
		goto BeforeRet;
	}
	LA3: ;
	{
		NIM_BOOL LOC7;
		LOC7 = 0;
		LOC7 = (a == NIM_NIL);
		if (LOC7) goto LA8;
		LOC7 = (b == NIM_NIL);
		LA8: ;
		if (!LOC7) goto LA9;
		result = NIM_FALSE;
		goto BeforeRet;
	}
	LA9: ;
	LOC11 = 0;
	LOC11 = ((*a).Sup.len == (*b).Sup.len);
	if (!(LOC11)) goto LA12;
	LOC13 = 0;
	LOC13 = memcmp(((NCSTRING) ((*a).data)), ((NCSTRING) ((*b).data)), (*a).Sup.len);
	LOC11 = (LOC13 == ((NI32) 0));
	LA12: ;
	result = LOC11;
	goto BeforeRet;
	}BeforeRet: ;
	return result;
}

N_NIMCALL(void, testreadingarrays_133614)(void) {
	TY132605* innerarray1;
	PythonlistHEX3Aobjecttype130011* array1;
	nimfr("testReadingArrays", "function_tests.nim")
	nimln(28, "function_tests.nim");
	genericSeqAssign((&innerarray1), TMP520, (&NTI132605));
	nimln(29, "function_tests.nim");
	array1 = pythonify_133634(innerarray1->data, innerarray1->Sup.len);
	nimln(30, "function_tests.nim");
	{
		NI LOC3;
		NI LOC4;
		LOC3 = 0;
		LOC3 = len_130837(array1);
		LOC4 = 0;
		LOC4 = len_130837(array1);
		if (!!((((NI) (LOC3)) == ((NI) (LOC4))))) goto LA5;
		failedassertimpl_91603(((NimStringDesc*) &TMP536));
	}
	LA5: ;
	nimln(31, "function_tests.nim");
	HEX5BHEX5DHEX3D_133802(&array1, ((NI) 3), ((NimStringDesc*) &TMP537));
	nimln(32, "function_tests.nim");
	{
		Tpyobject125574* LOC9;
		NI32 LOC10;
		LOC9 = 0;
		LOC9 = HEX5BHEX5D_130904(&array1, ((NI) 5));
		LOC10 = 0;
		LOC10 = asint_130408(LOC9);
		if ((NU)(((NI) 5)) >= (NU)(innerarray1->Sup.len)) raiseIndexError();
		if (!!((((NI) (LOC10)) == innerarray1->data[((NI) 5)]))) goto LA11;
		failedassertimpl_91603(((NimStringDesc*) &TMP538));
	}
	LA11: ;
	nimln(33, "function_tests.nim");
	{
		if (!NIM_FALSE) goto LA15;
		failedassertimpl_91603(((NimStringDesc*) &TMP539));
	}
	LA15: ;
	nimln(34, "function_tests.nim");
	{
		Tpyobject125574* LOC19;
		NimStringDesc* LOC20;
		LOC19 = 0;
		LOC19 = HEX5BHEX5D_130904(&array1, ((NI) 3));
		LOC20 = 0;
		LOC20 = asstring_130380(LOC19);
		if (!!(eqStrings(LOC20, ((NimStringDesc*) &TMP537)))) goto LA21;
		failedassertimpl_91603(((NimStringDesc*) &TMP540));
	}
	LA21: ;
	popFrame();
}

static N_INLINE(Tpyobject125574*, getitem_130671)(PythonobjectattrHEX3Aobjecttype130627* obj, NimStringDesc* attr) {
	Tpyobject125574* result;
	Tpyobject125574* LOC1;
	nimfr("getItem", "pythonize.nim")
	result = 0;
	nimln(233, "pythonize.nim");
	LOC1 = 0;
	LOC1 = Dl_127323(((Tpyobject125574*) (obj)), attr->data);
	result = ((Tpyobject125574*) (LOC1));
	popFrame();
	return result;
}

static N_INLINE(Tpyobject125574*, HEX5BHEX5D_130684)(PythonobjectattrHEX3Aobjecttype130627* obj, NimStringDesc* attr) {
	Tpyobject125574* result;
	nimfr("[]", "pythonize.nim")
	result = 0;
	nimln(235, "pythonize.nim");
	result = getitem_130671(obj, attr);
	popFrame();
	return result;
}

static N_INLINE(PythonobjectattrHEX3Aobjecttype130627*, attrs_130652)(Tpyobject125574* obj) {
	PythonobjectattrHEX3Aobjecttype130627* result;
	nimfr("attrs", "pythonize.nim")
	result = 0;
	nimln(227, "pythonize.nim");
	result = (PythonobjectattrHEX3Aobjecttype130627*) newObj((&NTI130626), sizeof(PythonobjectattrHEX3Aobjecttype130627));
	nimln(228, "pythonize.nim");
	result = ((PythonobjectattrHEX3Aobjecttype130627*) (obj));
	popFrame();
	return result;
}

N_NIMCALL(void, testreadingattributes_134407)(void) {
	TY132605* innerarray1;
	PythonlistHEX3Aobjecttype130011* array1;
	nimfr("testReadingAttributes", "function_tests.nim")
	nimln(37, "function_tests.nim");
	genericSeqAssign((&innerarray1), TMP520, (&NTI132605));
	nimln(38, "function_tests.nim");
	array1 = pythonify_133634(innerarray1->data, innerarray1->Sup.len);
	nimln(39, "function_tests.nim");
	HEX5BHEX5DHEX3D_132540(((PythondictHEX3Aobjecttype130025*) (pythonenvironmentobject_130069)), ((NimStringDesc*) &TMP518), array1);
	nimln(70, "pythonize.nim");
	{
		Tpyobject125574* LOC3;
		LOC3 = 0;
		LOC3 = Dl_126680("class Foo: myattribute1 = 1234 ", ((NI) 257), pythonenvironmentobject_130069, pythonenvironmentobject_130069);
		if (!LOC3 == 0) goto LA4;
		nimln(71, "pythonize.nim");
		Dl_126508();
	}
	LA4: ;
	nimln(70, "pythonize.nim");
	{
		Tpyobject125574* LOC8;
		LOC8 = 0;
		LOC8 = Dl_126680("Foo.myattribute2 = array1 ", ((NI) 257), pythonenvironmentobject_130069, pythonenvironmentobject_130069);
		if (!LOC8 == 0) goto LA9;
		nimln(71, "pythonize.nim");
		Dl_126508();
	}
	LA9: ;
	nimln(42, "function_tests.nim");
	{
		Tpyobject125574* LOC13;
		PythonobjectattrHEX3Aobjecttype130627* LOC14;
		Tpyobject125574* LOC15;
		NI32 LOC16;
		LOC13 = 0;
		LOC13 = HEX5BHEX5D_131477(((PythondictHEX3Aobjecttype130025*) (pythonenvironmentobject_130069)), ((NimStringDesc*) &TMP543));
		LOC14 = 0;
		LOC14 = attrs_130652(LOC13);
		LOC15 = 0;
		LOC15 = HEX5BHEX5D_130684(LOC14, ((NimStringDesc*) &TMP544));
		LOC16 = 0;
		LOC16 = asint_130408(LOC15);
		if (!!((((NI32) 1234) == LOC16))) goto LA17;
		failedassertimpl_91603(((NimStringDesc*) &TMP545));
	}
	LA17: ;
	nimln(43, "function_tests.nim");
	{
		Tpyobject125574* LOC21;
		PythonobjectattrHEX3Aobjecttype130627* LOC22;
		Tpyobject125574* LOC23;
		TY132605* LOC24;
		LOC21 = 0;
		LOC21 = HEX5BHEX5D_131477(((PythondictHEX3Aobjecttype130025*) (pythonenvironmentobject_130069)), ((NimStringDesc*) &TMP543));
		LOC22 = 0;
		LOC22 = attrs_130652(LOC21);
		LOC23 = 0;
		LOC23 = HEX5BHEX5D_130684(LOC22, ((NimStringDesc*) &TMP546));
		LOC24 = 0;
		LOC24 = aslist_132579(LOC23);
		if ((NU)(((NI) 3)) >= (NU)(LOC24->Sup.len)) raiseIndexError();
		if (!!((((NI) 4) == LOC24->data[((NI) 3)]))) goto LA25;
		failedassertimpl_91603(((NimStringDesc*) &TMP547));
	}
	LA25: ;
	popFrame();
}

static N_INLINE(void, setitem_134867)(PythonobjectattrHEX3Aobjecttype130627* obj, NimStringDesc* attr, NimStringDesc* value) {
	Tpyobject125574* LOC1;
	NI LOC2;
	nimfr("setItem", "pythonize.nim")
	nimln(237, "pythonize.nim");
	LOC1 = 0;
	LOC1 = pythonify_130283(value);
	LOC2 = 0;
	LOC2 = Dl_127383(((Tpyobject125574*) (obj)), attr->data, ((Tpyobject125574*) (LOC1)));
	popFrame();
}

static N_INLINE(void, HEX5BHEX5DHEX3D_134885)(PythonobjectattrHEX3Aobjecttype130627* obj, NimStringDesc* attr, NimStringDesc* value) {
	nimfr("[]=", "pythonize.nim")
	nimln(239, "pythonize.nim");
	setitem_134867(obj, attr, value);
	popFrame();
}

N_NIMCALL(void, testwritingattributes_134811)(void) {
	TY132605* innerarray1;
	PythonlistHEX3Aobjecttype130011* array1;
	Tpyobject125574* LOC11;
	PythonobjectattrHEX3Aobjecttype130627* LOC12;
	Tpyobject125574* LOC13;
	PythonobjectattrHEX3Aobjecttype130627* LOC14;
	nimfr("testWritingAttributes", "function_tests.nim")
	nimln(46, "function_tests.nim");
	genericSeqAssign((&innerarray1), TMP520, (&NTI132605));
	nimln(47, "function_tests.nim");
	array1 = pythonify_133634(innerarray1->data, innerarray1->Sup.len);
	nimln(48, "function_tests.nim");
	HEX5BHEX5DHEX3D_132540(((PythondictHEX3Aobjecttype130025*) (pythonenvironmentobject_130069)), ((NimStringDesc*) &TMP518), array1);
	nimln(70, "pythonize.nim");
	{
		Tpyobject125574* LOC3;
		LOC3 = 0;
		LOC3 = Dl_126680("class Foo: myattribute1 = 1234.5 ", ((NI) 257), pythonenvironmentobject_130069, pythonenvironmentobject_130069);
		if (!LOC3 == 0) goto LA4;
		nimln(71, "pythonize.nim");
		Dl_126508();
	}
	LA4: ;
	nimln(70, "pythonize.nim");
	{
		Tpyobject125574* LOC8;
		LOC8 = 0;
		LOC8 = Dl_126680("Foo.myattribute2 = array1 ", ((NI) 257), pythonenvironmentobject_130069, pythonenvironmentobject_130069);
		if (!LOC8 == 0) goto LA9;
		nimln(71, "pythonize.nim");
		Dl_126508();
	}
	LA9: ;
	nimln(51, "function_tests.nim");
	LOC11 = 0;
	LOC11 = HEX5BHEX5D_131477(((PythondictHEX3Aobjecttype130025*) (pythonenvironmentobject_130069)), ((NimStringDesc*) &TMP543));
	LOC12 = 0;
	LOC12 = attrs_130652(LOC11);
	setitem_134867(LOC12, ((NimStringDesc*) &TMP549), ((NimStringDesc*) &TMP550));
	nimln(52, "function_tests.nim");
	LOC13 = 0;
	LOC13 = HEX5BHEX5D_131477(((PythondictHEX3Aobjecttype130025*) (pythonenvironmentobject_130069)), ((NimStringDesc*) &TMP543));
	LOC14 = 0;
	LOC14 = attrs_130652(LOC13);
	HEX5BHEX5DHEX3D_134885(LOC14, ((NimStringDesc*) &TMP549), ((NimStringDesc*) &TMP550));
	nimln(53, "function_tests.nim");
	{
		Tpyobject125574* LOC17;
		PythonobjectattrHEX3Aobjecttype130627* LOC18;
		Tpyobject125574* LOC19;
		NF LOC20;
		LOC17 = 0;
		LOC17 = HEX5BHEX5D_131477(((PythondictHEX3Aobjecttype130025*) (pythonenvironmentobject_130069)), ((NimStringDesc*) &TMP543));
		LOC18 = 0;
		LOC18 = attrs_130652(LOC17);
		LOC19 = 0;
		LOC19 = HEX5BHEX5D_130684(LOC18, ((NimStringDesc*) &TMP544));
		LOC20 = 0;
		LOC20 = asfloat_130354(LOC19);
		if (!!((LOC20 == 1.2345000000000000e+03))) goto LA21;
		failedassertimpl_91603(((NimStringDesc*) &TMP551));
	}
	LA21: ;
	nimln(54, "function_tests.nim");
	{
		Tpyobject125574* LOC25;
		PythonobjectattrHEX3Aobjecttype130627* LOC26;
		Tpyobject125574* LOC27;
		PythonlistHEX3Aobjecttype130011* LOC28;
		Tpyobject125574* LOC29;
		NI32 LOC30;
		LOC25 = 0;
		LOC25 = HEX5BHEX5D_131477(((PythondictHEX3Aobjecttype130025*) (pythonenvironmentobject_130069)), ((NimStringDesc*) &TMP543));
		LOC26 = 0;
		LOC26 = attrs_130652(LOC25);
		LOC27 = 0;
		LOC27 = HEX5BHEX5D_130684(LOC26, ((NimStringDesc*) &TMP546));
		LOC28 = 0;
		LOC28 = aspylist_130789(LOC27);
		LOC29 = 0;
		LOC29 = HEX5BHEX5D_130880(LOC28, ((NI) 2));
		LOC30 = 0;
		LOC30 = asint_130408(LOC29);
		if (!!((LOC30 == ((NI32) 3)))) goto LA31;
		failedassertimpl_91603(((NimStringDesc*) &TMP552));
	}
	LA31: ;
	nimln(55, "function_tests.nim");
	{
		Tpyobject125574* LOC35;
		PythonobjectattrHEX3Aobjecttype130627* LOC36;
		Tpyobject125574* LOC37;
		NimStringDesc* LOC38;
		LOC35 = 0;
		LOC35 = HEX5BHEX5D_131477(((PythondictHEX3Aobjecttype130025*) (pythonenvironmentobject_130069)), ((NimStringDesc*) &TMP543));
		LOC36 = 0;
		LOC36 = attrs_130652(LOC35);
		LOC37 = 0;
		LOC37 = HEX5BHEX5D_130684(LOC36, ((NimStringDesc*) &TMP549));
		LOC38 = 0;
		LOC38 = asstring_130380(LOC37);
		if (!!(eqStrings(LOC38, ((NimStringDesc*) &TMP550)))) goto LA39;
		failedassertimpl_91603(((NimStringDesc*) &TMP553));
	}
	LA39: ;
	popFrame();
}

static N_INLINE(void, initStackBottomWith)(void* locals) {
	setStackBottom(locals);
}
void PreMainInner() {
	systemInit000();
	HEX00_parseutilsDatInit000();
	HEX00_strutilsDatInit000();
	HEX00_etcprivDatInit000();
	HEX00_hashesDatInit000();
	HEX00_timesDatInit000();
	HEX00_mathDatInit000();
	HEX00_tablesDatInit000();
	HEX00_dynlibDatInit000();
	python_pythonDatInit000();
	pythonize_pythonizeDatInit000();
	function_testsDatInit000();
	HEX00_parseutilsInit000();
	HEX00_strutilsInit000();
	HEX00_etcprivInit000();
	HEX00_hashesInit000();
	HEX00_timesInit000();
	HEX00_mathInit000();
	HEX00_tablesInit000();
	HEX00_dynlibInit000();
	python_pythonInit000();
	pythonize_pythonizeInit000();
}

void PreMain() {
	void (*volatile inner)();
	systemDatInit000();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	function_testsInit000();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)();
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

NIM_EXTERNC N_NOINLINE(void, function_testsInit000)(void) {
	nimfr("function_tests", "function_tests.nim")
	nimln(58, "function_tests.nim");
	{
		if (!NIM_TRUE) goto LA3;
		nimln(59, "function_tests.nim");
		printf("%s\012", ((NimStringDesc*) &TMP512)? (((NimStringDesc*) &TMP512))->data:"nil");
		nimln(60, "function_tests.nim");
		testreadingwritingvars_132004();
		nimln(61, "function_tests.nim");
		printf("%s\012", ((NimStringDesc*) &TMP515)? (((NimStringDesc*) &TMP515))->data:"nil");
		nimln(62, "function_tests.nim");
		testreadingvars_132209();
		nimln(63, "function_tests.nim");
		printf("%s\012", ((NimStringDesc*) &TMP517)? (((NimStringDesc*) &TMP517))->data:"nil");
		nimln(64, "function_tests.nim");
		testreadingwritingarrays_132408();
		nimln(65, "function_tests.nim");
		printf("%s\012", ((NimStringDesc*) &TMP534)? (((NimStringDesc*) &TMP534))->data:"nil");
		nimln(66, "function_tests.nim");
		testreadingarrays_133614();
		nimln(67, "function_tests.nim");
		printf("%s\012", ((NimStringDesc*) &TMP541)? (((NimStringDesc*) &TMP541))->data:"nil");
		nimln(68, "function_tests.nim");
		testreadingattributes_134407();
		nimln(69, "function_tests.nim");
		printf("%s\012", ((NimStringDesc*) &TMP548)? (((NimStringDesc*) &TMP548))->data:"nil");
		nimln(70, "function_tests.nim");
		testwritingattributes_134811();
		{
			NI i_135658;
			NI L_135660;
			nimln(3365, "system.nim");
			i_135658 = ((NI) 0);
			nimln(3366, "system.nim");
			L_135660 = (pythonreferences_130059 ? pythonreferences_130059->Sup.len : 0);
			{
				nimln(3367, "system.nim");
				while (1) {
					NI TMP554;
					if (!(i_135658 < L_135660)) goto LA7;
					nimln(3368, "system.nim");
					if ((NU)(i_135658) >= (NU)(pythonreferences_130059->Sup.len)) raiseIndexError();
					pythonref_135426 = pythonreferences_130059->data[i_135658];
					nimln(603, "pythonize.nim");
					release_135612(pythonref_135426);
					nimln(3369, "system.nim");
					TMP554 = addInt(i_135658, ((NI) 1));
					i_135658 = (NI)(TMP554);
					nimln(3370, "system.nim");
					{
						if (!!(((pythonreferences_130059 ? pythonreferences_130059->Sup.len : 0) == L_135660))) goto LA10;
						failedassertimpl_91603(((NimStringDesc*) &TMP555));
					}
					LA10: ;
				} LA7: ;
			}
		}
		nimln(604, "pythonize.nim");
		{
			if (!NIM_TRUE) goto LA14;
			nimln(596, "pythonize.nim");
			Dl_127891();
		}
		LA14: ;
	}
	LA3: ;
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, function_testsDatInit000)(void) {
}

