/* Generated by Nim Compiler v0.12.0 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -g3 -O0  -I/media/marco/Research/Applications/aporia/Nim/lib -o /home/marco/.nimble/pkgs/Pythonize27-1.0.0/tests/nimcache/pythonize_pythonize.o /home/marco/.nimble/pkgs/Pythonize27-1.0.0/tests/nimcache/pythonize_pythonize.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <stdio.h>
typedef struct TY130058 TY130058;
typedef struct Tpyobject125574 Tpyobject125574;
typedef struct TGenericSeq TGenericSeq;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct Cell49347 Cell49347;
typedef struct Cellseq49363 Cellseq49363;
typedef struct Gcheap51418 Gcheap51418;
typedef struct Gcstack51416 Gcstack51416;
typedef struct Cellset49359 Cellset49359;
typedef struct Pagedesc49355 Pagedesc49355;
typedef struct Memregion31291 Memregion31291;
typedef struct Smallchunk31243 Smallchunk31243;
typedef struct Llchunk31285 Llchunk31285;
typedef struct Bigchunk31245 Bigchunk31245;
typedef struct Intset31217 Intset31217;
typedef struct Trunk31213 Trunk31213;
typedef struct Avlnode31289 Avlnode31289;
typedef struct Gcstat51414 Gcstat51414;
typedef struct NimStringDesc NimStringDesc;
typedef struct PythondictHEX3Aobjecttype130025 PythondictHEX3Aobjecttype130025;
typedef struct PythonlistHEX3Aobjecttype130011 PythonlistHEX3Aobjecttype130011;
typedef struct Tpytypeobject125626 Tpytypeobject125626;
typedef struct Tpynumbermethods125556 Tpynumbermethods125556;
typedef struct Tpysequencemethods125560 Tpysequencemethods125560;
typedef struct Tpymappingmethods125564 Tpymappingmethods125564;
typedef struct Tpybufferprocs125568 Tpybufferprocs125568;
typedef struct Tpymethoddef125586 Tpymethoddef125586;
typedef struct Tpymemberdef125590 Tpymemberdef125590;
typedef struct Tpygetsetdef125598 Tpygetsetdef125598;
typedef struct Basechunk31241 Basechunk31241;
typedef struct Freecell31233 Freecell31233;
struct  TGenericSeq  {
NI len;
NI reserved;
};
typedef N_NIMCALL_PTR(void, TY3889) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3894) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3889 marker;
TY3894 deepcopy;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef N_CDECL_PTR(void, TY126559) (void);
struct  Cell49347  {
NI refcount;
TNimType* typ;
};
struct  Cellseq49363  {
NI len;
NI cap;
Cell49347** d;
};
struct  Cellset49359  {
NI counter;
NI max;
Pagedesc49355* head;
Pagedesc49355** data;
};
typedef Smallchunk31243* TY31306[512];
typedef Trunk31213* Trunkbuckets31215[256];
struct  Intset31217  {
Trunkbuckets31215 data;
};
struct  Memregion31291  {
NI minlargeobj;
NI maxlargeobj;
TY31306 freesmallchunks;
Llchunk31285* llmem;
NI currmem;
NI maxmem;
NI freemem;
NI lastsize;
Bigchunk31245* freechunkslist;
Intset31217 chunkstarts;
Avlnode31289* root;
Avlnode31289* deleted;
Avlnode31289* last;
Avlnode31289* freeavlnodes;
};
struct  Gcstat51414  {
NI stackscans;
NI cyclecollections;
NI maxthreshold;
NI maxstacksize;
NI maxstackcells;
NI cycletablesize;
NI64 maxpause;
};
struct  Gcheap51418  {
Gcstack51416* stack;
void* stackbottom;
NI cyclethreshold;
Cellseq49363 zct;
Cellseq49363 decstack;
Cellset49359 cycleroots;
Cellseq49363 tempstack;
NI recgclock;
Memregion31291 region;
Gcstat51414 stat;
};
typedef N_CDECL_PTR(Tpyobject125574*, TY126858) (NCSTRING name);
typedef N_CDECL_PTR(Tpyobject125574*, TY126669) (Tpyobject125574* module);
typedef N_CDECL_PTR(Tpyobject125574*, TY126681) (NCSTRING str, NI start, Tpyobject125574* globals, Tpyobject125574* locals);
typedef N_CDECL_PTR(void, TY126509) (void);
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef N_CDECL_PTR(NCSTRING, TY126696) (Tpyobject125574* ob);
typedef N_CDECL_PTR(Tpyobject125574*, TY127370) (Tpyobject125574* ob);
typedef N_CDECL_PTR(Tpyobject125574*, TY126648) (Tpyobject125574* dp, NCSTRING key);
typedef N_CDECL_PTR(Tpyobject125574*, TY126953) (NI size);
typedef N_CDECL_PTR(NI, TY126965) (Tpyobject125574* dp, NI idx, Tpyobject125574* item);
typedef N_CDECL_PTR(Tpyobject125574*, TY127047) (NI64 val);
struct  Tpyobject125574  {
NI obrefcnt;
Tpytypeobject125626* obtype;
};
struct  PythonlistHEX3Aobjecttype130011  {
  Tpyobject125574 Sup;
};
typedef N_CDECL_PTR(void, Tpydestructor125508) (Tpyobject125574* ob);
typedef N_CDECL_PTR(NI, Tprintfunc125510) (Tpyobject125574* ob, FILE* f, NI i);
typedef N_CDECL_PTR(Tpyobject125574*, Tgetattrfunc125512) (Tpyobject125574* ob1, NCSTRING name);
typedef N_CDECL_PTR(NI, Tsetattrfunc125514) (Tpyobject125574* ob1, NCSTRING name, Tpyobject125574* ob2);
typedef N_CDECL_PTR(NI, Tcmpfunc125516) (Tpyobject125574* ob1, Tpyobject125574* ob2);
typedef N_CDECL_PTR(Tpyobject125574*, Treprfunc125518) (Tpyobject125574* ob);
typedef N_CDECL_PTR(NI32, Thashfunc125520) (Tpyobject125574* ob);
typedef N_CDECL_PTR(Tpyobject125574*, Tternaryfunc125492) (Tpyobject125574* ob1, Tpyobject125574* ob2, Tpyobject125574* ob3);
typedef N_CDECL_PTR(Tpyobject125574*, Tgetattrofunc125522) (Tpyobject125574* ob1, Tpyobject125574* ob2);
typedef N_CDECL_PTR(NI, Tsetattrofunc125524) (Tpyobject125574* ob1, Tpyobject125574* ob2, Tpyobject125574* ob3);
typedef N_CDECL_PTR(NI, Tvisitproc125536) (Tpyobject125574* ob1, void* p);
typedef N_CDECL_PTR(NI, Ttraverseproc125538) (Tpyobject125574* ob1, Tvisitproc125536 prc, void* p);
typedef N_CDECL_PTR(NI, Tinquiry125494) (Tpyobject125574* ob1);
typedef N_CDECL_PTR(Tpyobject125574*, Trichcmpfunc125540) (Tpyobject125574* ob1, Tpyobject125574* ob2, NI i);
typedef N_CDECL_PTR(Tpyobject125574*, Tgetiterfunc125542) (Tpyobject125574* ob1);
typedef N_CDECL_PTR(Tpyobject125574*, Titernextfunc125544) (Tpyobject125574* ob1);
typedef N_CDECL_PTR(Tpyobject125574*, Tdescrgetfunc125546) (Tpyobject125574* ob1, Tpyobject125574* ob2, Tpyobject125574* ob3);
typedef N_CDECL_PTR(NI, Tdescrsetfunc125548) (Tpyobject125574* ob1, Tpyobject125574* ob2, Tpyobject125574* ob3);
typedef N_CDECL_PTR(NI, Tinitproc125550) (Tpyobject125574* self, Tpyobject125574* args, Tpyobject125574* kwds);
typedef N_CDECL_PTR(Tpyobject125574*, Tallocfunc125554) (Tpytypeobject125626* self, NI nitems);
typedef N_CDECL_PTR(Tpyobject125574*, Tnewfunc125552) (Tpytypeobject125626* subtype, Tpyobject125574* args, Tpyobject125574* kwds);
struct  Tpytypeobject125626  {
  Tpyobject125574 Sup;
NI obsize;
NCSTRING tpname;
NI tpbasicsize;
NI tpitemsize;
Tpydestructor125508 tpdealloc;
Tprintfunc125510 tpprint;
Tgetattrfunc125512 tpgetattr;
Tsetattrfunc125514 tpsetattr;
Tcmpfunc125516 tpcompare;
Treprfunc125518 tprepr;
Tpynumbermethods125556* tpasnumber;
Tpysequencemethods125560* tpassequence;
Tpymappingmethods125564* tpasmapping;
Thashfunc125520 tphash;
Tternaryfunc125492 tpcall;
Treprfunc125518 tpstr;
Tgetattrofunc125522 tpgetattro;
Tsetattrofunc125524 tpsetattro;
Tpybufferprocs125568* tpasbuffer;
NI32 tpflags;
NCSTRING tpdoc;
Ttraverseproc125538 tptraverse;
Tinquiry125494 tpclear;
Trichcmpfunc125540 tprichcompare;
NI32 tpweaklistoffset;
Tgetiterfunc125542 tpiter;
Titernextfunc125544 tpiternext;
Tpymethoddef125586* tpmethods;
Tpymemberdef125590* tpmembers;
Tpygetsetdef125598* tpgetset;
Tpytypeobject125626* tpbase;
Tpyobject125574* tpdict;
Tdescrgetfunc125546 tpdescrget;
Tdescrsetfunc125548 tpdescrset;
NI32 tpdictoffset;
Tinitproc125550 tpinit;
Tallocfunc125554 tpalloc;
Tnewfunc125552 tpnew;
Tpydestructor125508 tpfree;
Tinquiry125494 tpisgc;
Tpyobject125574* tpbases;
Tpyobject125574* tpmro;
Tpyobject125574* tpcache;
Tpyobject125574* tpsubclasses;
Tpyobject125574* tpweaklist;
void* tpxxx7;
void* tpxxx8;
};
typedef N_CDECL_PTR(void, TY127892) (void);
struct  Gcstack51416  {
Gcstack51416* prev;
Gcstack51416* next;
void* starts;
void* pos;
NI maxstacksize;
};
typedef NI TY31222[8];
struct  Pagedesc49355  {
Pagedesc49355* next;
NI key;
TY31222 bits;
};
struct  Basechunk31241  {
NI prevsize;
NI size;
NIM_BOOL used;
};
struct  Smallchunk31243  {
  Basechunk31241 Sup;
Smallchunk31243* next;
Smallchunk31243* prev;
Freecell31233* freelist;
NI free;
NI acc;
NF data;
};
struct  Llchunk31285  {
NI size;
NI acc;
Llchunk31285* next;
};
struct  Bigchunk31245  {
  Basechunk31241 Sup;
Bigchunk31245* next;
Bigchunk31245* prev;
NI align;
NF data;
};
struct  Trunk31213  {
Trunk31213* next;
NI key;
TY31222 bits;
};
typedef Avlnode31289* TY31296[2];
struct  Avlnode31289  {
TY31296 link;
NI key;
NI upperbound;
NI level;
};
struct  PythondictHEX3Aobjecttype130025  {
  Tpyobject125574 Sup;
};
typedef N_CDECL_PTR(Tpyobject125574*, Tbinaryfunc125490) (Tpyobject125574* ob1, Tpyobject125574* ob2);
typedef N_CDECL_PTR(Tpyobject125574*, Tunaryfunc125488) (Tpyobject125574* ob1);
typedef N_CDECL_PTR(NI, Tcoercion125496) (Tpyobject125574** ob1, Tpyobject125574** ob2);
struct  Tpynumbermethods125556  {
Tbinaryfunc125490 nbadd;
Tbinaryfunc125490 nbsubstract;
Tbinaryfunc125490 nbmultiply;
Tbinaryfunc125490 nbdivide;
Tbinaryfunc125490 nbremainder;
Tbinaryfunc125490 nbdivmod;
Tternaryfunc125492 nbpower;
Tunaryfunc125488 nbnegative;
Tunaryfunc125488 nbpositive;
Tunaryfunc125488 nbabsolute;
Tinquiry125494 nbnonzero;
Tunaryfunc125488 nbinvert;
Tbinaryfunc125490 nblshift;
Tbinaryfunc125490 nbrshift;
Tbinaryfunc125490 nband;
Tbinaryfunc125490 nbxor;
Tbinaryfunc125490 nbor;
Tcoercion125496 nbcoerce;
Tunaryfunc125488 nbint;
Tunaryfunc125488 nblong;
Tunaryfunc125488 nbfloat;
Tunaryfunc125488 nboct;
Tunaryfunc125488 nbhex;
Tbinaryfunc125490 nbinplaceadd;
Tbinaryfunc125490 nbinplacesubtract;
Tbinaryfunc125490 nbinplacemultiply;
Tbinaryfunc125490 nbinplacedivide;
Tbinaryfunc125490 nbinplaceremainder;
Tternaryfunc125492 nbinplacepower;
Tbinaryfunc125490 nbinplacelshift;
Tbinaryfunc125490 nbinplacershift;
Tbinaryfunc125490 nbinplaceand;
Tbinaryfunc125490 nbinplacexor;
Tbinaryfunc125490 nbinplaceor;
Tbinaryfunc125490 nbfloordivide;
Tbinaryfunc125490 nbtruedivide;
Tbinaryfunc125490 nbinplacefloordivide;
Tbinaryfunc125490 nbinplacetruedivide;
};
typedef N_CDECL_PTR(Tpyobject125574*, Tintargfunc125498) (Tpyobject125574* ob1, NI i);
typedef N_CDECL_PTR(Tpyobject125574*, Tintintargfunc125500) (Tpyobject125574* ob1, NI i1, NI i2);
typedef N_CDECL_PTR(NI, Tintobjargproc125502) (Tpyobject125574* ob1, NI i, Tpyobject125574* ob2);
typedef N_CDECL_PTR(NI, Tintintobjargproc125504) (Tpyobject125574* ob1, NI i1, NI i2, Tpyobject125574* ob2);
typedef N_CDECL_PTR(NI, Tobjobjproc125534) (Tpyobject125574* ob1, Tpyobject125574* ob2);
struct  Tpysequencemethods125560  {
Tinquiry125494 sqlength;
Tbinaryfunc125490 sqconcat;
Tintargfunc125498 sqrepeat;
Tintargfunc125498 sqitem;
Tintintargfunc125500 sqslice;
Tintobjargproc125502 sqassitem;
Tintintobjargproc125504 sqassslice;
Tobjobjproc125534 sqcontains;
Tbinaryfunc125490 sqinplaceconcat;
Tintargfunc125498 sqinplacerepeat;
};
typedef N_CDECL_PTR(NI, Tobjobjargproc125506) (Tpyobject125574* ob1, Tpyobject125574* ob2, Tpyobject125574* ob3);
struct  Tpymappingmethods125564  {
Tinquiry125494 mplength;
Tbinaryfunc125490 mpsubscript;
Tobjobjargproc125506 mpasssubscript;
};
typedef N_CDECL_PTR(NI, Tgetreadbufferproc125526) (Tpyobject125574* ob1, NI i, void* p);
typedef N_CDECL_PTR(NI, Tgetwritebufferproc125528) (Tpyobject125574* ob1, NI i, void* p);
typedef N_CDECL_PTR(NI, Tgetsegcountproc125530) (Tpyobject125574* ob1, NI i);
typedef N_CDECL_PTR(NI, Tgetcharbufferproc125532) (Tpyobject125574* ob1, NI i, NCSTRING pstr);
struct  Tpybufferprocs125568  {
Tgetreadbufferproc125526 bfgetreadbuffer;
Tgetwritebufferproc125528 bfgetwritebuffer;
Tgetsegcountproc125530 bfgetsegcount;
Tgetcharbufferproc125532 bfgetcharbuffer;
};
typedef N_CDECL_PTR(Tpyobject125574*, Tpycfunction125486) (Tpyobject125574* self, Tpyobject125574* args);
struct  Tpymethoddef125586  {
NCSTRING mlname;
Tpycfunction125486 mlmeth;
NI mlflags;
NCSTRING mldoc;
};
struct  Tpymemberdef125590  {
NCSTRING name;
NI thetype;
NI offset;
NI flags;
NCSTRING doc;
};
typedef N_CDECL_PTR(Tpyobject125574*, Tgetter125592) (Tpyobject125574* obj, void* context);
typedef N_CDECL_PTR(NI, Tsetter125594) (Tpyobject125574* obj, Tpyobject125574* value, void* context);
struct  Tpygetsetdef125598  {
NCSTRING name;
Tgetter125592 get;
Tsetter125594 setter;
NCSTRING doc;
void* closure;
};
struct  Freecell31233  {
Freecell31233* next;
NI zerofield;
};
struct TY130058 {
  TGenericSeq Sup;
  Tpyobject125574* data[SEQ_DECL_SIZE];
};
N_NIMCALL(TY130058*, newseq_131818)(NI len);
N_NIMCALL(void, TMP494)(void* p, NI op);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
static N_INLINE(Cell49347*, usrtocell_53046)(void* usr);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_23601)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(void, rtladdzct_54604)(Cell49347* c);
N_NOINLINE(void, addzct_53017)(Cellseq49363* s, Cell49347* c);
static N_INLINE(NimStringDesc*, HEX24_130423)(Tpyobject125574* x);
static N_INLINE(NimStringDesc*, asstring_130380)(Tpyobject125574* x);
N_NIMCALL(NIM_BOOL, Pystringcheck_128090)(Tpyobject125574* obj);
N_NIMCALL(NimStringDesc*, cstrToNimstr)(NCSTRING str);
static N_INLINE(Tpyobject125574*, HEX5BHEX5D_131477)(PythondictHEX3Aobjecttype130025* p, NimStringDesc* index);
static N_INLINE(Tpyobject125574*, getitem_131452)(PythondictHEX3Aobjecttype130025* p, NimStringDesc* index);
N_NIMCALL(void, proc1_131658)(void);
static N_INLINE(PythonlistHEX3Aobjecttype130011*, newpythonlist_130742)(NI size);
N_NIMCALL(Tpyobject125574*, addreference_130098)(Tpyobject125574* obj);
N_NIMCALL(TGenericSeq*, incrSeqV2)(TGenericSeq* seq, NI elemsize);
static N_INLINE(void, HEX5BHEX5DHEX3D_131678)(PythonlistHEX3Aobjecttype130011** p, NI index, NI val);
static N_INLINE(void, setitem_131688)(PythonlistHEX3Aobjecttype130011** p, NI index, NI val);
static N_INLINE(Tpyobject125574*, pythonify_130214)(NI x);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
N_NIMCALL(void, release_131707)(PythonlistHEX3Aobjecttype130011* op);
STRING_LITERAL(TMP507, "FROM PYTHON: ", 13);
STRING_LITERAL(TMP508, "a", 1);
STRING_LITERAL(TMP510, "---", 3);
TY130058* pythonreferences_130059;
Tpyobject125574* pythonenvironmentmodule_130064;
Tpyobject125574* pythonenvironmentobject_130069;
extern TNimType NTI125474; /* PPyObject */
TNimType NTI130058; /* seq[PythonObject] */
extern TY126559 Dl_126558;
extern TFrame* frameptr_20842;
extern Gcheap51418 gch_51459;
extern TY126858 Dl_126857;
extern TY126669 Dl_126668;
extern TY126681 Dl_126680;
extern TY126509 Dl_126508;
extern TY126696 Dl_126695;
extern TY127370 Dl_127369;
extern TY126648 Dl_126647;
extern TY126953 Dl_126952;
extern TY126965 Dl_126964;
extern TY127047 Dl_127046;
extern TY127892 Dl_127891;
N_NIMCALL(void, TMP494)(void* p, NI op) {
	TY130058* a;
	NI LOC1;
	a = (TY130058*)p;
	LOC1 = 0;
	for (LOC1 = 0; LOC1 < a->Sup.len; LOC1++) {
	}
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_20842 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_20842).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_20842;
	frameptr_20842 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_23601();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_20842 = (*frameptr_20842).prev;
}

static N_INLINE(Cell49347*, usrtocell_53046)(void* usr) {
	Cell49347* result;
	nimfr("usrToCell", "gc.nim")
	result = 0;
	nimln(131, "gc.nim");
	result = ((Cell49347*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(Cell49347))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtladdzct_54604)(Cell49347* c) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(212, "gc.nim");
	addzct_53017((&gch_51459.zct), c);
	popFrame();
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr("asgnRefNoCycle", "gc.nim")
	nimln(264, "gc.nim");
	{
		Cell49347* c;
		nimln(349, "system.nim");
		if (!!((src == NIM_NIL))) goto LA3;
		nimln(265, "gc.nim");
		c = usrtocell_53046(src);
		nimln(182, "gc.nim");
		(*c).refcount += ((NI) 8);
	}
	LA3: ;
	nimln(267, "gc.nim");
	{
		Cell49347* c;
		nimln(349, "system.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA7;
		nimln(268, "gc.nim");
		c = usrtocell_53046((*dest));
		nimln(269, "gc.nim");
		{
			nimln(180, "gc.nim");
			(*c).refcount -= ((NI) 8);
			nimln(181, "gc.nim");
			if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA11;
			nimln(270, "gc.nim");
			rtladdzct_54604(c);
		}
		LA11: ;
	}
	LA7: ;
	nimln(271, "gc.nim");
	(*dest) = src;
	popFrame();
}

static N_INLINE(NimStringDesc*, asstring_130380)(Tpyobject125574* x) {
	NimStringDesc* result;
	Tpyobject125574* LOC7;
	NCSTRING LOC8;
	nimfr("asString", "pythonize.nim")
{	result = 0;
	nimln(141, "pythonize.nim");
	{
		NIM_BOOL LOC3;
		NCSTRING LOC6;
		LOC3 = 0;
		LOC3 = Pystringcheck_128090(((Tpyobject125574*) (x)));
		if (!LOC3) goto LA4;
		LOC6 = 0;
		LOC6 = Dl_126695(((Tpyobject125574*) (x)));
		result = cstrToNimstr(LOC6);
		goto BeforeRet;
	}
	LA4: ;
	nimln(142, "pythonize.nim");
	LOC7 = 0;
	LOC7 = Dl_127369(((Tpyobject125574*) (x)));
	LOC8 = 0;
	LOC8 = Dl_126695(LOC7);
	result = cstrToNimstr(LOC8);
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result;
}

static N_INLINE(NimStringDesc*, HEX24_130423)(Tpyobject125574* x) {
	NimStringDesc* result;
	nimfr("$", "pythonize.nim")
	result = 0;
	nimln(152, "pythonize.nim");
	result = asstring_130380(x);
	popFrame();
	return result;
}

static N_INLINE(Tpyobject125574*, getitem_131452)(PythondictHEX3Aobjecttype130025* p, NimStringDesc* index) {
	Tpyobject125574* result;
	nimfr("getItem", "pythonize.nim")
	result = 0;
	nimln(530, "pythonize.nim");
	result = Dl_126647(((Tpyobject125574*) (p)), index->data);
	popFrame();
	return result;
}

static N_INLINE(Tpyobject125574*, HEX5BHEX5D_131477)(PythondictHEX3Aobjecttype130025* p, NimStringDesc* index) {
	Tpyobject125574* result;
	nimfr("[]", "pythonize.nim")
	result = 0;
	nimln(533, "pythonize.nim");
	result = getitem_131452(p, index);
	popFrame();
	return result;
}

N_NIMCALL(Tpyobject125574*, addreference_130098)(Tpyobject125574* obj) {
	Tpyobject125574* result;
	nimfr("addReference", "pythonize.nim")
{	result = 0;
	nimln(50, "pythonize.nim");
	pythonreferences_130059 = (TY130058*) incrSeqV2(&(pythonreferences_130059)->Sup, sizeof(Tpyobject125574*));
	pythonreferences_130059->data[pythonreferences_130059->Sup.len] = obj;
	++pythonreferences_130059->Sup.len;
	nimln(51, "pythonize.nim");
	result = obj;
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result;
}

static N_INLINE(PythonlistHEX3Aobjecttype130011*, newpythonlist_130742)(NI size) {
	PythonlistHEX3Aobjecttype130011* result;
	Tpyobject125574* LOC1;
	Tpyobject125574* LOC2;
	nimfr("newPythonList", "pythonize.nim")
	result = 0;
	nimln(276, "pythonize.nim");
	LOC1 = 0;
	LOC1 = Dl_126952(size);
	LOC2 = 0;
	LOC2 = addreference_130098(((Tpyobject125574*) (LOC1)));
	result = ((PythonlistHEX3Aobjecttype130011*) (LOC2));
	popFrame();
	return result;
}

static N_INLINE(Tpyobject125574*, pythonify_130214)(NI x) {
	Tpyobject125574* result;
	Tpyobject125574* LOC1;
	nimfr("pythonify", "pythonize.nim")
	result = 0;
	nimln(107, "pythonize.nim");
	LOC1 = 0;
	LOC1 = Dl_127046(((NI64) (x)));
	result = ((Tpyobject125574*) (LOC1));
	popFrame();
	return result;
}

static N_INLINE(void, setitem_131688)(PythonlistHEX3Aobjecttype130011** p, NI index, NI val) {
	Tpyobject125574* LOC1;
	NI LOC2;
	nimfr("setItem", "pythonize.nim")
	nimln(340, "pythonize.nim");
	LOC1 = 0;
	LOC1 = pythonify_130214(val);
	LOC2 = 0;
	LOC2 = Dl_126964(((Tpyobject125574*) ((*p))), ((NI) (index)), ((Tpyobject125574*) (LOC1)));
	popFrame();
}

static N_INLINE(void, HEX5BHEX5DHEX3D_131678)(PythonlistHEX3Aobjecttype130011** p, NI index, NI val) {
	nimfr("[]=", "pythonize.nim")
	nimln(342, "pythonize.nim");
	setitem_131688(p, index, val);
	popFrame();
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = 0;
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (a <= i);
		if (!(LOC3)) goto LA4;
		LOC3 = (i <= b);
		LA4: ;
		if (!LOC3) goto LA5;
		result = i;
		goto BeforeRet;
	}
	goto LA1;
	LA5: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1: ;
	}BeforeRet: ;
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = 0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (((NI) 0) <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result;
}

N_NIMCALL(void, release_131707)(PythonlistHEX3Aobjecttype130011* op) {
	nimfr("release", "pythonize.nim")
{	nimln(78, "pythonize.nim");
	{
		if (!(op == NIM_NIL)) goto LA3;
		goto BeforeRet;
	}
	LA3: ;
	nimln(79, "pythonize.nim");
	{
		NIM_BOOL LOC7;
		NIM_BOOL LOC8;
		LOC7 = 0;
		LOC8 = 0;
		LOC8 = ((*op).Sup.obrefcnt <= ((NI) 0));
		if (LOC8) goto LA9;
		LOC8 = ((*op).Sup.obtype == NIM_NIL);
		LA9: ;
		LOC7 = LOC8;
		if (LOC7) goto LA10;
		LOC7 = ((*(*op).Sup.obtype).tpdealloc == NIM_NIL);
		LA10: ;
		if (!LOC7) goto LA11;
		goto BeforeRet;
	}
	LA11: ;
	nimln(80, "pythonize.nim");
	(*op).Sup.obrefcnt = ((NI) 0);
	nimln(81, "pythonize.nim");
	(*(*op).Sup.obtype).tpdealloc(((Tpyobject125574*) (op)));
	}BeforeRet: ;
	popFrame();
}

N_NIMCALL(void, proc1_131658)(void) {
	PythonlistHEX3Aobjecttype130011* list1;
	nimfr("proc1", "pythonize.nim")
	nimln(563, "pythonize.nim");
	list1 = newpythonlist_130742(((NI) 10000000));
	{
		NI i_131676;
		NI res_131759;
		i_131676 = 0;
		nimln(1874, "system.nim");
		res_131759 = ((NI) 0);
		{
			nimln(1875, "system.nim");
			while (1) {
				NI TMP509;
				if (!(res_131759 <= ((NI) 9999999))) goto LA3;
				nimln(1876, "system.nim");
				i_131676 = res_131759;
				nimln(565, "pythonize.nim");
				HEX5BHEX5DHEX3D_131678(&list1, ((NI)chckRange(i_131676, ((NI) 0), ((NI) IL64(9223372036854775807)))), i_131676);
				nimln(1890, "system.nim");
				TMP509 = addInt(res_131759, ((NI) 1));
				res_131759 = (NI)(TMP509);
			} LA3: ;
		}
	}
	nimln(566, "pythonize.nim");
	release_131707(list1);
	nimln(567, "pythonize.nim");
	release_131707(list1);
	popFrame();
}

N_NIMCALL(NimStringDesc*, depythonify_132067)(Tpyobject125574* x) {
	NimStringDesc* result;
	NCSTRING LOC1;
	nimfr("depythonify", "pythonize.nim")
	result = 0;
	nimln(198, "pythonize.nim");
	LOC1 = 0;
	LOC1 = Dl_126695(x);
	result = cstrToNimstr(LOC1);
	popFrame();
	return result;
}

N_NIMCALL(void, release_132212)(Tpyobject125574* op) {
	nimfr("release", "pythonize.nim")
{	nimln(78, "pythonize.nim");
	{
		if (!(op == NIM_NIL)) goto LA3;
		goto BeforeRet;
	}
	LA3: ;
	nimln(79, "pythonize.nim");
	{
		NIM_BOOL LOC7;
		NIM_BOOL LOC8;
		LOC7 = 0;
		LOC8 = 0;
		LOC8 = ((*op).obrefcnt <= ((NI) 0));
		if (LOC8) goto LA9;
		LOC8 = ((*op).obtype == NIM_NIL);
		LA9: ;
		LOC7 = LOC8;
		if (LOC7) goto LA10;
		LOC7 = ((*(*op).obtype).tpdealloc == NIM_NIL);
		LA10: ;
		if (!LOC7) goto LA11;
		goto BeforeRet;
	}
	LA11: ;
	nimln(80, "pythonize.nim");
	(*op).obrefcnt = ((NI) 0);
	nimln(81, "pythonize.nim");
	(*(*op).obtype).tpdealloc(((Tpyobject125574*) (op)));
	}BeforeRet: ;
	popFrame();
}
NIM_EXTERNC N_NOINLINE(void, pythonize_pythonizeInit000)(void) {
	nimfr("pythonize", "pythonize.nim")
	nimln(586, "pythonize.nim");
	Dl_126558();
	nimln(587, "pythonize.nim");
	asgnRefNoCycle((void**) (&pythonreferences_130059), newseq_131818(((NI) 0)));
	nimln(588, "pythonize.nim");
	pythonenvironmentmodule_130064 = Dl_126857("__main__");
	nimln(589, "pythonize.nim");
	pythonenvironmentobject_130069 = Dl_126668(pythonenvironmentmodule_130064);
	nimln(616, "pythonize.nim");
	{
		Tpyobject125574* LOC20;
		NimStringDesc* LOC21;
		if (!NIM_FALSE) goto LA3;
		nimln(586, "pythonize.nim");
		Dl_126558();
		nimln(587, "pythonize.nim");
		asgnRefNoCycle((void**) (&pythonreferences_130059), newseq_131818(((NI) 0)));
		nimln(588, "pythonize.nim");
		pythonenvironmentmodule_130064 = Dl_126857("__main__");
		nimln(589, "pythonize.nim");
		pythonenvironmentobject_130069 = Dl_126668(pythonenvironmentmodule_130064);
		nimln(70, "pythonize.nim");
		{
			Tpyobject125574* LOC7;
			LOC7 = 0;
			LOC7 = Dl_126680("import os, sys, gc", ((NI) 257), pythonenvironmentobject_130069, pythonenvironmentobject_130069);
			if (!LOC7 == 0) goto LA8;
			nimln(71, "pythonize.nim");
			Dl_126508();
		}
		LA8: ;
		nimln(70, "pythonize.nim");
		{
			Tpyobject125574* LOC12;
			LOC12 = 0;
			LOC12 = Dl_126680("sys.path.insert(0, os.getcwd())", ((NI) 257), pythonenvironmentobject_130069, pythonenvironmentobject_130069);
			if (!LOC12 == 0) goto LA13;
			nimln(71, "pythonize.nim");
			Dl_126508();
		}
		LA13: ;
		nimln(70, "pythonize.nim");
		{
			Tpyobject125574* LOC17;
			LOC17 = 0;
			LOC17 = Dl_126680("a=1", ((NI) 257), pythonenvironmentobject_130069, pythonenvironmentobject_130069);
			if (!LOC17 == 0) goto LA18;
			nimln(71, "pythonize.nim");
			Dl_126508();
		}
		LA18: ;
		nimln(621, "pythonize.nim");
		LOC20 = 0;
		LOC20 = HEX5BHEX5D_131477(((PythondictHEX3Aobjecttype130025*) (pythonenvironmentobject_130069)), ((NimStringDesc*) &TMP508));
		LOC21 = 0;
		LOC21 = HEX24_130423(LOC20);
		printf("%s%s\012", ((NimStringDesc*) &TMP507)? (((NimStringDesc*) &TMP507))->data:"nil", LOC21? (LOC21)->data:"nil");
		nimln(70, "pythonize.nim");
		{
			Tpyobject125574* LOC24;
			LOC24 = 0;
			LOC24 = Dl_126680("print \'Hello world\'", ((NI) 257), pythonenvironmentobject_130069, pythonenvironmentobject_130069);
			if (!LOC24 == 0) goto LA25;
			nimln(71, "pythonize.nim");
			Dl_126508();
		}
		LA25: ;
		nimln(70, "pythonize.nim");
		{
			Tpyobject125574* LOC29;
			LOC29 = 0;
			LOC29 = Dl_126680("def examp(o):\012    print \'Hello world \' + str(o)\012", ((NI) 257), pythonenvironmentobject_130069, pythonenvironmentobject_130069);
			if (!LOC29 == 0) goto LA30;
			nimln(71, "pythonize.nim");
			Dl_126508();
		}
		LA30: ;
		nimln(70, "pythonize.nim");
		{
			Tpyobject125574* LOC34;
			LOC34 = 0;
			LOC34 = Dl_126680("examp(2)", ((NI) 257), pythonenvironmentobject_130069, pythonenvironmentobject_130069);
			if (!LOC34 == 0) goto LA35;
			nimln(71, "pythonize.nim");
			Dl_126508();
		}
		LA35: ;
		nimln(70, "pythonize.nim");
		{
			Tpyobject125574* LOC39;
			LOC39 = 0;
			LOC39 = Dl_126680("examp(\'again\')", ((NI) 257), pythonenvironmentobject_130069, pythonenvironmentobject_130069);
			if (!LOC39 == 0) goto LA40;
			nimln(71, "pythonize.nim");
			Dl_126508();
		}
		LA40: ;
		nimln(629, "pythonize.nim");
		proc1_131658();
		nimln(630, "pythonize.nim");
		printf("%s\012", ((NimStringDesc*) &TMP510)? (((NimStringDesc*) &TMP510))->data:"nil");
		nimln(631, "pythonize.nim");
		proc1_131658();
		nimln(632, "pythonize.nim");
		printf("%s\012", ((NimStringDesc*) &TMP510)? (((NimStringDesc*) &TMP510))->data:"nil");
		nimln(633, "pythonize.nim");
		proc1_131658();
		nimln(634, "pythonize.nim");
		printf("%s\012", ((NimStringDesc*) &TMP510)? (((NimStringDesc*) &TMP510))->data:"nil");
		nimln(635, "pythonize.nim");
		proc1_131658();
		nimln(636, "pythonize.nim");
		printf("%s\012", ((NimStringDesc*) &TMP510)? (((NimStringDesc*) &TMP510))->data:"nil");
		nimln(637, "pythonize.nim");
		proc1_131658();
		nimln(638, "pythonize.nim");
		printf("%s\012", ((NimStringDesc*) &TMP510)? (((NimStringDesc*) &TMP510))->data:"nil");
		nimln(639, "pythonize.nim");
		proc1_131658();
		nimln(640, "pythonize.nim");
		printf("%s\012", ((NimStringDesc*) &TMP510)? (((NimStringDesc*) &TMP510))->data:"nil");
		nimln(641, "pythonize.nim");
		proc1_131658();
		nimln(642, "pythonize.nim");
		printf("%s\012", ((NimStringDesc*) &TMP510)? (((NimStringDesc*) &TMP510))->data:"nil");
		nimln(643, "pythonize.nim");
		proc1_131658();
		nimln(644, "pythonize.nim");
		printf("%s\012", ((NimStringDesc*) &TMP510)? (((NimStringDesc*) &TMP510))->data:"nil");
		nimln(645, "pythonize.nim");
		proc1_131658();
		nimln(646, "pythonize.nim");
		printf("%s\012", ((NimStringDesc*) &TMP510)? (((NimStringDesc*) &TMP510))->data:"nil");
		nimln(647, "pythonize.nim");
		proc1_131658();
		nimln(648, "pythonize.nim");
		printf("%s\012", ((NimStringDesc*) &TMP510)? (((NimStringDesc*) &TMP510))->data:"nil");
		nimln(649, "pythonize.nim");
		proc1_131658();
		nimln(596, "pythonize.nim");
		Dl_127891();
	}
	LA3: ;
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, pythonize_pythonizeDatInit000)(void) {
NTI130058.size = sizeof(TY130058*);
NTI130058.kind = 24;
NTI130058.base = (&NTI125474);
NTI130058.flags = 2;
NTI130058.marker = TMP494;
}

