/* Generated by Nim Compiler v0.12.0 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -g3 -O0  -I/media/marco/Research/Applications/aporia/Nim/lib -o /home/marco/.nimble/pkgs/Pythonize27-1.0.0/tests/nimcache/pythonize_plotting.o /home/marco/.nimble/pkgs/Pythonize27-1.0.0/tests/nimcache/pythonize_plotting.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <stdio.h>
typedef struct PythondictHEX3Aobjecttype130025 PythondictHEX3Aobjecttype130025;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct PythonlistHEX3Aobjecttype130011 PythonlistHEX3Aobjecttype130011;
typedef struct Tpyobject125574 Tpyobject125574;
typedef struct TY132027 TY132027;
typedef struct TY130058 TY130058;
typedef struct Tpytypeobject125626 Tpytypeobject125626;
typedef struct Tpynumbermethods125556 Tpynumbermethods125556;
typedef struct Tpysequencemethods125560 Tpysequencemethods125560;
typedef struct Tpymappingmethods125564 Tpymappingmethods125564;
typedef struct Tpybufferprocs125568 Tpybufferprocs125568;
typedef struct Tpymethoddef125586 Tpymethoddef125586;
typedef struct Tpymemberdef125590 Tpymemberdef125590;
typedef struct Tpygetsetdef125598 Tpygetsetdef125598;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef N_CDECL_PTR(NI, TY126655) (Tpyobject125574* dp, NCSTRING key, Tpyobject125574* item);
typedef N_CDECL_PTR(Tpyobject125574*, TY126953) (NI size);
typedef N_CDECL_PTR(NI, TY126965) (Tpyobject125574* dp, NI idx, Tpyobject125574* item);
typedef N_CDECL_PTR(Tpyobject125574*, TY127047) (NI64 val);
typedef N_CDECL_PTR(Tpyobject125574*, TY126681) (NCSTRING str, NI start, Tpyobject125574* globals, Tpyobject125574* locals);
typedef N_CDECL_PTR(void, TY126509) (void);
typedef N_CDECL_PTR(void, TY127892) (void);
struct  Tpyobject125574  {
NI obrefcnt;
Tpytypeobject125626* obtype;
};
struct  PythondictHEX3Aobjecttype130025  {
  Tpyobject125574 Sup;
};
struct  PythonlistHEX3Aobjecttype130011  {
  Tpyobject125574 Sup;
};
typedef N_CDECL_PTR(void, Tpydestructor125508) (Tpyobject125574* ob);
typedef N_CDECL_PTR(NI, Tprintfunc125510) (Tpyobject125574* ob, FILE* f, NI i);
typedef N_CDECL_PTR(Tpyobject125574*, Tgetattrfunc125512) (Tpyobject125574* ob1, NCSTRING name);
typedef N_CDECL_PTR(NI, Tsetattrfunc125514) (Tpyobject125574* ob1, NCSTRING name, Tpyobject125574* ob2);
typedef N_CDECL_PTR(NI, Tcmpfunc125516) (Tpyobject125574* ob1, Tpyobject125574* ob2);
typedef N_CDECL_PTR(Tpyobject125574*, Treprfunc125518) (Tpyobject125574* ob);
typedef N_CDECL_PTR(NI32, Thashfunc125520) (Tpyobject125574* ob);
typedef N_CDECL_PTR(Tpyobject125574*, Tternaryfunc125492) (Tpyobject125574* ob1, Tpyobject125574* ob2, Tpyobject125574* ob3);
typedef N_CDECL_PTR(Tpyobject125574*, Tgetattrofunc125522) (Tpyobject125574* ob1, Tpyobject125574* ob2);
typedef N_CDECL_PTR(NI, Tsetattrofunc125524) (Tpyobject125574* ob1, Tpyobject125574* ob2, Tpyobject125574* ob3);
typedef N_CDECL_PTR(NI, Tvisitproc125536) (Tpyobject125574* ob1, void* p);
typedef N_CDECL_PTR(NI, Ttraverseproc125538) (Tpyobject125574* ob1, Tvisitproc125536 prc, void* p);
typedef N_CDECL_PTR(NI, Tinquiry125494) (Tpyobject125574* ob1);
typedef N_CDECL_PTR(Tpyobject125574*, Trichcmpfunc125540) (Tpyobject125574* ob1, Tpyobject125574* ob2, NI i);
typedef N_CDECL_PTR(Tpyobject125574*, Tgetiterfunc125542) (Tpyobject125574* ob1);
typedef N_CDECL_PTR(Tpyobject125574*, Titernextfunc125544) (Tpyobject125574* ob1);
typedef N_CDECL_PTR(Tpyobject125574*, Tdescrgetfunc125546) (Tpyobject125574* ob1, Tpyobject125574* ob2, Tpyobject125574* ob3);
typedef N_CDECL_PTR(NI, Tdescrsetfunc125548) (Tpyobject125574* ob1, Tpyobject125574* ob2, Tpyobject125574* ob3);
typedef N_CDECL_PTR(NI, Tinitproc125550) (Tpyobject125574* self, Tpyobject125574* args, Tpyobject125574* kwds);
typedef N_CDECL_PTR(Tpyobject125574*, Tallocfunc125554) (Tpytypeobject125626* self, NI nitems);
typedef N_CDECL_PTR(Tpyobject125574*, Tnewfunc125552) (Tpytypeobject125626* subtype, Tpyobject125574* args, Tpyobject125574* kwds);
struct  Tpytypeobject125626  {
  Tpyobject125574 Sup;
NI obsize;
NCSTRING tpname;
NI tpbasicsize;
NI tpitemsize;
Tpydestructor125508 tpdealloc;
Tprintfunc125510 tpprint;
Tgetattrfunc125512 tpgetattr;
Tsetattrfunc125514 tpsetattr;
Tcmpfunc125516 tpcompare;
Treprfunc125518 tprepr;
Tpynumbermethods125556* tpasnumber;
Tpysequencemethods125560* tpassequence;
Tpymappingmethods125564* tpasmapping;
Thashfunc125520 tphash;
Tternaryfunc125492 tpcall;
Treprfunc125518 tpstr;
Tgetattrofunc125522 tpgetattro;
Tsetattrofunc125524 tpsetattro;
Tpybufferprocs125568* tpasbuffer;
NI32 tpflags;
NCSTRING tpdoc;
Ttraverseproc125538 tptraverse;
Tinquiry125494 tpclear;
Trichcmpfunc125540 tprichcompare;
NI32 tpweaklistoffset;
Tgetiterfunc125542 tpiter;
Titernextfunc125544 tpiternext;
Tpymethoddef125586* tpmethods;
Tpymemberdef125590* tpmembers;
Tpygetsetdef125598* tpgetset;
Tpytypeobject125626* tpbase;
Tpyobject125574* tpdict;
Tdescrgetfunc125546 tpdescrget;
Tdescrsetfunc125548 tpdescrset;
NI32 tpdictoffset;
Tinitproc125550 tpinit;
Tallocfunc125554 tpalloc;
Tnewfunc125552 tpnew;
Tpydestructor125508 tpfree;
Tinquiry125494 tpisgc;
Tpyobject125574* tpbases;
Tpyobject125574* tpmro;
Tpyobject125574* tpcache;
Tpyobject125574* tpsubclasses;
Tpyobject125574* tpweaklist;
void* tpxxx7;
void* tpxxx8;
};
typedef N_CDECL_PTR(Tpyobject125574*, Tbinaryfunc125490) (Tpyobject125574* ob1, Tpyobject125574* ob2);
typedef N_CDECL_PTR(Tpyobject125574*, Tunaryfunc125488) (Tpyobject125574* ob1);
typedef N_CDECL_PTR(NI, Tcoercion125496) (Tpyobject125574** ob1, Tpyobject125574** ob2);
struct  Tpynumbermethods125556  {
Tbinaryfunc125490 nbadd;
Tbinaryfunc125490 nbsubstract;
Tbinaryfunc125490 nbmultiply;
Tbinaryfunc125490 nbdivide;
Tbinaryfunc125490 nbremainder;
Tbinaryfunc125490 nbdivmod;
Tternaryfunc125492 nbpower;
Tunaryfunc125488 nbnegative;
Tunaryfunc125488 nbpositive;
Tunaryfunc125488 nbabsolute;
Tinquiry125494 nbnonzero;
Tunaryfunc125488 nbinvert;
Tbinaryfunc125490 nblshift;
Tbinaryfunc125490 nbrshift;
Tbinaryfunc125490 nband;
Tbinaryfunc125490 nbxor;
Tbinaryfunc125490 nbor;
Tcoercion125496 nbcoerce;
Tunaryfunc125488 nbint;
Tunaryfunc125488 nblong;
Tunaryfunc125488 nbfloat;
Tunaryfunc125488 nboct;
Tunaryfunc125488 nbhex;
Tbinaryfunc125490 nbinplaceadd;
Tbinaryfunc125490 nbinplacesubtract;
Tbinaryfunc125490 nbinplacemultiply;
Tbinaryfunc125490 nbinplacedivide;
Tbinaryfunc125490 nbinplaceremainder;
Tternaryfunc125492 nbinplacepower;
Tbinaryfunc125490 nbinplacelshift;
Tbinaryfunc125490 nbinplacershift;
Tbinaryfunc125490 nbinplaceand;
Tbinaryfunc125490 nbinplacexor;
Tbinaryfunc125490 nbinplaceor;
Tbinaryfunc125490 nbfloordivide;
Tbinaryfunc125490 nbtruedivide;
Tbinaryfunc125490 nbinplacefloordivide;
Tbinaryfunc125490 nbinplacetruedivide;
};
typedef N_CDECL_PTR(Tpyobject125574*, Tintargfunc125498) (Tpyobject125574* ob1, NI i);
typedef N_CDECL_PTR(Tpyobject125574*, Tintintargfunc125500) (Tpyobject125574* ob1, NI i1, NI i2);
typedef N_CDECL_PTR(NI, Tintobjargproc125502) (Tpyobject125574* ob1, NI i, Tpyobject125574* ob2);
typedef N_CDECL_PTR(NI, Tintintobjargproc125504) (Tpyobject125574* ob1, NI i1, NI i2, Tpyobject125574* ob2);
typedef N_CDECL_PTR(NI, Tobjobjproc125534) (Tpyobject125574* ob1, Tpyobject125574* ob2);
struct  Tpysequencemethods125560  {
Tinquiry125494 sqlength;
Tbinaryfunc125490 sqconcat;
Tintargfunc125498 sqrepeat;
Tintargfunc125498 sqitem;
Tintintargfunc125500 sqslice;
Tintobjargproc125502 sqassitem;
Tintintobjargproc125504 sqassslice;
Tobjobjproc125534 sqcontains;
Tbinaryfunc125490 sqinplaceconcat;
Tintargfunc125498 sqinplacerepeat;
};
typedef N_CDECL_PTR(NI, Tobjobjargproc125506) (Tpyobject125574* ob1, Tpyobject125574* ob2, Tpyobject125574* ob3);
struct  Tpymappingmethods125564  {
Tinquiry125494 mplength;
Tbinaryfunc125490 mpsubscript;
Tobjobjargproc125506 mpasssubscript;
};
typedef N_CDECL_PTR(NI, Tgetreadbufferproc125526) (Tpyobject125574* ob1, NI i, void* p);
typedef N_CDECL_PTR(NI, Tgetwritebufferproc125528) (Tpyobject125574* ob1, NI i, void* p);
typedef N_CDECL_PTR(NI, Tgetsegcountproc125530) (Tpyobject125574* ob1, NI i);
typedef N_CDECL_PTR(NI, Tgetcharbufferproc125532) (Tpyobject125574* ob1, NI i, NCSTRING pstr);
struct  Tpybufferprocs125568  {
Tgetreadbufferproc125526 bfgetreadbuffer;
Tgetwritebufferproc125528 bfgetwritebuffer;
Tgetsegcountproc125530 bfgetsegcount;
Tgetcharbufferproc125532 bfgetcharbuffer;
};
typedef N_CDECL_PTR(Tpyobject125574*, Tpycfunction125486) (Tpyobject125574* self, Tpyobject125574* args);
struct  Tpymethoddef125586  {
NCSTRING mlname;
Tpycfunction125486 mlmeth;
NI mlflags;
NCSTRING mldoc;
};
struct  Tpymemberdef125590  {
NCSTRING name;
NI thetype;
NI offset;
NI flags;
NCSTRING doc;
};
typedef N_CDECL_PTR(Tpyobject125574*, Tgetter125592) (Tpyobject125574* obj, void* context);
typedef N_CDECL_PTR(NI, Tsetter125594) (Tpyobject125574* obj, Tpyobject125574* value, void* context);
struct  Tpygetsetdef125598  {
NCSTRING name;
Tgetter125592 get;
Tsetter125594 setter;
NCSTRING doc;
void* closure;
};
struct TY132027 {
  TGenericSeq Sup;
  NI data[SEQ_DECL_SIZE];
};
struct TY130058 {
  TGenericSeq Sup;
  Tpyobject125574* data[SEQ_DECL_SIZE];
};
static N_INLINE(void, HEX5BHEX5DHEX3D_132146)(PythondictHEX3Aobjecttype130025* p, NimStringDesc* index, PythonlistHEX3Aobjecttype130011* val);
static N_INLINE(void, setitem_132156)(PythondictHEX3Aobjecttype130025* p, NimStringDesc* index, PythonlistHEX3Aobjecttype130011* val);
static N_INLINE(PythonlistHEX3Aobjecttype130011*, pythonify_132166)(PythonlistHEX3Aobjecttype130011* x);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_23601)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(PythonlistHEX3Aobjecttype130011*, pythonify_132033)(NI* data, NI dataLen0);
static N_INLINE(PythonlistHEX3Aobjecttype130011*, newpythonlist_130742)(NI size);
N_NIMCALL(Tpyobject125574*, addreference_130098)(Tpyobject125574* obj);
N_NOINLINE(void, raiseIndexError)(void);
static N_INLINE(void, HEX5BHEX5DHEX3D_132091)(PythonlistHEX3Aobjecttype130011** p, NI index, Tpyobject125574* val);
static N_INLINE(void, setitem_132101)(PythonlistHEX3Aobjecttype130011** p, NI index, Tpyobject125574* val);
static N_INLINE(Tpyobject125574*, pythonify_132111)(Tpyobject125574* x);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
static N_INLINE(Tpyobject125574*, pythonify_130214)(NI x);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
N_NIMCALL(void, release_132412)(Tpyobject125574* op);
N_NIMCALL(void, failedassertimpl_91603)(NimStringDesc* msg);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_NOINLINE(void, setStackBottom)(void* thestackbottom);
NIM_EXTERNC N_NOINLINE(void, systemInit000)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_parseutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_parseutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_strutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_strutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_etcprivInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_etcprivDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_hashesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_hashesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_timesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_timesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_mathInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_mathDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_tablesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_tablesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_dynlibInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_dynlibDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, python_pythonInit000)(void);
NIM_EXTERNC N_NOINLINE(void, python_pythonDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, pythonize_pythonizeInit000)(void);
NIM_EXTERNC N_NOINLINE(void, pythonize_pythonizeDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, plottingInit000)(void);
NIM_EXTERNC N_NOINLINE(void, plottingDatInit000)(void);
STRING_LITERAL(TMP511, "signal", 6);
NIM_CONST struct {
  TGenericSeq Sup;
  NI data[14];
} CNSTSEQ515 = {{14, 14}, {((NI) 0),
((NI) 2290),
((NI) 4001),
((NI) 5122),
((NI) 5686),
((NI) 5756),
((NI) 5419),
((NI) 4773),
((NI) 3919),
((NI) 2955),
((NI) 1966),
((NI) 1026),
((NI) 188),
((NI) 0)}};
NIM_CONST TY132027* TMP513 = ((TY132027*)&CNSTSEQ515);
STRING_LITERAL(TMP516, "len(a) == L seq modified while iterating over it", 48);
extern TY126655 Dl_126654;
extern TFrame* frameptr_20842;
extern Tpyobject125574* pythonenvironmentobject_130069;
extern TY126953 Dl_126952;
extern TY126965 Dl_126964;
extern TY127047 Dl_127046;
extern TY126681 Dl_126680;
extern TY126509 Dl_126508;
Tpyobject125574* pythonref_132221;
extern TY130058* pythonreferences_130059;
extern TY127892 Dl_127891;

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_20842 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_20842).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_20842;
	frameptr_20842 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_23601();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_20842 = (*frameptr_20842).prev;
}

static N_INLINE(PythonlistHEX3Aobjecttype130011*, pythonify_132166)(PythonlistHEX3Aobjecttype130011* x) {
	PythonlistHEX3Aobjecttype130011* result;
	nimfr("pythonify", "pythonize.nim")
	result = 0;
	nimln(97, "pythonize.nim");
	result = x;
	popFrame();
	return result;
}

static N_INLINE(void, setitem_132156)(PythondictHEX3Aobjecttype130025* p, NimStringDesc* index, PythonlistHEX3Aobjecttype130011* val) {
	PythonlistHEX3Aobjecttype130011* LOC1;
	NI LOC2;
	nimfr("setItem", "pythonize.nim")
	nimln(545, "pythonize.nim");
	LOC1 = 0;
	LOC1 = pythonify_132166(val);
	LOC2 = 0;
	LOC2 = Dl_126654(((Tpyobject125574*) (p)), index->data, ((Tpyobject125574*) (LOC1)));
	popFrame();
}

static N_INLINE(void, HEX5BHEX5DHEX3D_132146)(PythondictHEX3Aobjecttype130025* p, NimStringDesc* index, PythonlistHEX3Aobjecttype130011* val) {
	nimfr("[]=", "pythonize.nim")
	nimln(548, "pythonize.nim");
	setitem_132156(p, index, val);
	popFrame();
}

static N_INLINE(PythonlistHEX3Aobjecttype130011*, newpythonlist_130742)(NI size) {
	PythonlistHEX3Aobjecttype130011* result;
	Tpyobject125574* LOC1;
	Tpyobject125574* LOC2;
	nimfr("newPythonList", "pythonize.nim")
	result = 0;
	nimln(276, "pythonize.nim");
	LOC1 = 0;
	LOC1 = Dl_126952(size);
	LOC2 = 0;
	LOC2 = addreference_130098(((Tpyobject125574*) (LOC1)));
	result = ((PythonlistHEX3Aobjecttype130011*) (LOC2));
	popFrame();
	return result;
}

static N_INLINE(Tpyobject125574*, pythonify_132111)(Tpyobject125574* x) {
	Tpyobject125574* result;
	nimfr("pythonify", "pythonize.nim")
	result = 0;
	nimln(97, "pythonize.nim");
	result = x;
	popFrame();
	return result;
}

static N_INLINE(void, setitem_132101)(PythonlistHEX3Aobjecttype130011** p, NI index, Tpyobject125574* val) {
	Tpyobject125574* LOC1;
	NI LOC2;
	nimfr("setItem", "pythonize.nim")
	nimln(340, "pythonize.nim");
	LOC1 = 0;
	LOC1 = pythonify_132111(val);
	LOC2 = 0;
	LOC2 = Dl_126964(((Tpyobject125574*) ((*p))), ((NI) (index)), ((Tpyobject125574*) (LOC1)));
	popFrame();
}

static N_INLINE(void, HEX5BHEX5DHEX3D_132091)(PythonlistHEX3Aobjecttype130011** p, NI index, Tpyobject125574* val) {
	nimfr("[]=", "pythonize.nim")
	nimln(342, "pythonize.nim");
	setitem_132101(p, index, val);
	popFrame();
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = 0;
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (a <= i);
		if (!(LOC3)) goto LA4;
		LOC3 = (i <= b);
		LA4: ;
		if (!LOC3) goto LA5;
		result = i;
		goto BeforeRet;
	}
	goto LA1;
	LA5: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1: ;
	}BeforeRet: ;
	return result;
}

static N_INLINE(Tpyobject125574*, pythonify_130214)(NI x) {
	Tpyobject125574* result;
	Tpyobject125574* LOC1;
	nimfr("pythonify", "pythonize.nim")
	result = 0;
	nimln(107, "pythonize.nim");
	LOC1 = 0;
	LOC1 = Dl_127046(((NI64) (x)));
	result = ((Tpyobject125574*) (LOC1));
	popFrame();
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = 0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (((NI) 0) <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result;
}

static N_INLINE(PythonlistHEX3Aobjecttype130011*, pythonify_132033)(NI* data, NI dataLen0) {
	PythonlistHEX3Aobjecttype130011* result;
	nimfr("pythonify", "pythonize.nim")
	result = 0;
	nimln(287, "pythonize.nim");
	result = newpythonlist_130742(dataLen0);
	{
		NI index_132088;
		NI value_132089;
		NI i_132132;
		index_132088 = 0;
		value_132089 = 0;
		nimln(2031, "system.nim");
		i_132132 = ((NI) 0);
		{
			nimln(2032, "system.nim");
			while (1) {
				Tpyobject125574* LOC4;
				NI TMP512;
				if (!(i_132132 < dataLen0)) goto LA3;
				nimln(2031, "system.nim");
				index_132088 = i_132132;
				nimln(2033, "system.nim");
				if ((NU)(i_132132) >= (NU)(dataLen0)) raiseIndexError();
				value_132089 = data[i_132132];
				nimln(289, "pythonize.nim");
				LOC4 = 0;
				LOC4 = pythonify_130214(value_132089);
				HEX5BHEX5DHEX3D_132091(&result, ((NI)chckRange(index_132088, ((NI) 0), ((NI) IL64(9223372036854775807)))), LOC4);
				nimln(2034, "system.nim");
				TMP512 = addInt(i_132132, ((NI) 1));
				i_132132 = (NI)(TMP512);
			} LA3: ;
		}
	}
	popFrame();
	return result;
}

static N_INLINE(void, initStackBottomWith)(void* locals) {
	setStackBottom(locals);
}
void PreMainInner() {
	systemInit000();
	HEX00_parseutilsDatInit000();
	HEX00_strutilsDatInit000();
	HEX00_etcprivDatInit000();
	HEX00_hashesDatInit000();
	HEX00_timesDatInit000();
	HEX00_mathDatInit000();
	HEX00_tablesDatInit000();
	HEX00_dynlibDatInit000();
	python_pythonDatInit000();
	pythonize_pythonizeDatInit000();
	plottingDatInit000();
	HEX00_parseutilsInit000();
	HEX00_strutilsInit000();
	HEX00_etcprivInit000();
	HEX00_hashesInit000();
	HEX00_timesInit000();
	HEX00_mathInit000();
	HEX00_tablesInit000();
	HEX00_dynlibInit000();
	python_pythonInit000();
	pythonize_pythonizeInit000();
}

void PreMain() {
	void (*volatile inner)();
	systemDatInit000();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	plottingInit000();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)();
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

NIM_EXTERNC N_NOINLINE(void, plottingInit000)(void) {
	PythonlistHEX3Aobjecttype130011* LOC1;
	nimfr("plotting", "plotting.nim")
	nimln(3, "plotting.nim");
	LOC1 = 0;
	LOC1 = pythonify_132033(TMP513->data, TMP513->Sup.len);
	HEX5BHEX5DHEX3D_132146(((PythondictHEX3Aobjecttype130025*) (pythonenvironmentobject_130069)), ((NimStringDesc*) &TMP511), LOC1);
	nimln(70, "pythonize.nim");
	{
		Tpyobject125574* LOC4;
		LOC4 = 0;
		LOC4 = Dl_126680("import pylab", ((NI) 257), pythonenvironmentobject_130069, pythonenvironmentobject_130069);
		if (!LOC4 == 0) goto LA5;
		nimln(71, "pythonize.nim");
		Dl_126508();
	}
	LA5: ;
	nimln(70, "pythonize.nim");
	{
		Tpyobject125574* LOC9;
		LOC9 = 0;
		LOC9 = Dl_126680("pylab.fill(signal)", ((NI) 257), pythonenvironmentobject_130069, pythonenvironmentobject_130069);
		if (!LOC9 == 0) goto LA10;
		nimln(71, "pythonize.nim");
		Dl_126508();
	}
	LA10: ;
	nimln(70, "pythonize.nim");
	{
		Tpyobject125574* LOC14;
		LOC14 = 0;
		LOC14 = Dl_126680("pylab.show()", ((NI) 257), pythonenvironmentobject_130069, pythonenvironmentobject_130069);
		if (!LOC14 == 0) goto LA15;
		nimln(71, "pythonize.nim");
		Dl_126508();
	}
	LA15: ;
	{
		NI i_132458;
		NI L_132460;
		nimln(3365, "system.nim");
		i_132458 = ((NI) 0);
		nimln(3366, "system.nim");
		L_132460 = (pythonreferences_130059 ? pythonreferences_130059->Sup.len : 0);
		{
			nimln(3367, "system.nim");
			while (1) {
				NI TMP515;
				if (!(i_132458 < L_132460)) goto LA19;
				nimln(3368, "system.nim");
				if ((NU)(i_132458) >= (NU)(pythonreferences_130059->Sup.len)) raiseIndexError();
				pythonref_132221 = pythonreferences_130059->data[i_132458];
				nimln(603, "pythonize.nim");
				release_132412(pythonref_132221);
				nimln(3369, "system.nim");
				TMP515 = addInt(i_132458, ((NI) 1));
				i_132458 = (NI)(TMP515);
				nimln(3370, "system.nim");
				{
					if (!!(((pythonreferences_130059 ? pythonreferences_130059->Sup.len : 0) == L_132460))) goto LA22;
					failedassertimpl_91603(((NimStringDesc*) &TMP516));
				}
				LA22: ;
			} LA19: ;
		}
	}
	nimln(604, "pythonize.nim");
	{
		if (!NIM_TRUE) goto LA26;
		nimln(596, "pythonize.nim");
		Dl_127891();
	}
	LA26: ;
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, plottingDatInit000)(void) {
}

