/* Generated by Nim Compiler v0.12.0 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -g3 -O0  -I/media/marco/Research/Applications/aporia/Nim/lib -o nimcache/pythonize_md5_python.o nimcache/pythonize_md5_python.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <stdio.h>
#include <stdlib.h>
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct Memregion31291 Memregion31291;
typedef struct Gcheap51418 Gcheap51418;
typedef struct Gcstack51416 Gcstack51416;
typedef struct Cellseq49363 Cellseq49363;
typedef struct Cell49347 Cell49347;
typedef struct Cellset49359 Cellset49359;
typedef struct Pagedesc49355 Pagedesc49355;
typedef struct Smallchunk31243 Smallchunk31243;
typedef struct Llchunk31285 Llchunk31285;
typedef struct Bigchunk31245 Bigchunk31245;
typedef struct Intset31217 Intset31217;
typedef struct Trunk31213 Trunk31213;
typedef struct Avlnode31289 Avlnode31289;
typedef struct Gcstat51414 Gcstat51414;
typedef struct TNimType TNimType;
typedef struct Tpyobject96574 Tpyobject96574;
typedef struct Tpytypeobject96626 Tpytypeobject96626;
typedef struct Tpynumbermethods96556 Tpynumbermethods96556;
typedef struct Tpysequencemethods96560 Tpysequencemethods96560;
typedef struct Tpymappingmethods96564 Tpymappingmethods96564;
typedef struct Tpybufferprocs96568 Tpybufferprocs96568;
typedef struct Tpymethoddef96586 Tpymethoddef96586;
typedef struct Tpymemberdef96590 Tpymemberdef96590;
typedef struct Tpygetsetdef96598 Tpygetsetdef96598;
typedef struct Basechunk31241 Basechunk31241;
typedef struct Freecell31233 Freecell31233;
typedef struct TNimNode TNimNode;
typedef N_CDECL_PTR(void, TY97559) (void);
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct  Cellseq49363  {
NI len;
NI cap;
Cell49347** d;
};
struct  Cellset49359  {
NI counter;
NI max;
Pagedesc49355* head;
Pagedesc49355** data;
};
typedef Smallchunk31243* TY31306[512];
typedef Trunk31213* Trunkbuckets31215[256];
struct  Intset31217  {
Trunkbuckets31215 data;
};
struct  Memregion31291  {
NI minlargeobj;
NI maxlargeobj;
TY31306 freesmallchunks;
Llchunk31285* llmem;
NI currmem;
NI maxmem;
NI freemem;
NI lastsize;
Bigchunk31245* freechunkslist;
Intset31217 chunkstarts;
Avlnode31289* root;
Avlnode31289* deleted;
Avlnode31289* last;
Avlnode31289* freeavlnodes;
};
struct  Gcstat51414  {
NI stackscans;
NI cyclecollections;
NI maxthreshold;
NI maxstacksize;
NI maxstackcells;
NI cycletablesize;
NI64 maxpause;
};
struct  Gcheap51418  {
Gcstack51416* stack;
void* stackbottom;
NI cyclethreshold;
Cellseq49363 zct;
Cellseq49363 decstack;
Cellset49359 cycleroots;
Cellseq49363 tempstack;
NI recgclock;
Memregion31291 region;
Gcstat51414 stat;
};
struct  Cell49347  {
NI refcount;
TNimType* typ;
};
typedef N_CDECL_PTR(Tpyobject96574*, TY97702) (NCSTRING str);
typedef N_CDECL_PTR(Tpyobject96574*, TY97880) (NCSTRING name);
typedef N_CDECL_PTR(Tpyobject96574*, TY97669) (Tpyobject96574* module);
typedef N_CDECL_PTR(NI, TY97655) (Tpyobject96574* dp, NCSTRING key, Tpyobject96574* item);
typedef N_CDECL_PTR(NI, TY97690) (NCSTRING str);
typedef N_CDECL_PTR(Tpyobject96574*, TY97648) (Tpyobject96574* dp, NCSTRING key);
typedef N_CDECL_PTR(NCSTRING, TY97696) (Tpyobject96574* ob);
struct  Tpyobject96574  {
NI obrefcnt;
Tpytypeobject96626* obtype;
};
typedef N_CDECL_PTR(void, Tpydestructor96508) (Tpyobject96574* ob);
typedef N_CDECL_PTR(NI, Tprintfunc96510) (Tpyobject96574* ob, FILE* f, NI i);
typedef N_CDECL_PTR(Tpyobject96574*, Tgetattrfunc96512) (Tpyobject96574* ob1, NCSTRING name);
typedef N_CDECL_PTR(NI, Tsetattrfunc96514) (Tpyobject96574* ob1, NCSTRING name, Tpyobject96574* ob2);
typedef N_CDECL_PTR(NI, Tcmpfunc96516) (Tpyobject96574* ob1, Tpyobject96574* ob2);
typedef N_CDECL_PTR(Tpyobject96574*, Treprfunc96518) (Tpyobject96574* ob);
typedef N_CDECL_PTR(NI32, Thashfunc96520) (Tpyobject96574* ob);
typedef N_CDECL_PTR(Tpyobject96574*, Tternaryfunc96492) (Tpyobject96574* ob1, Tpyobject96574* ob2, Tpyobject96574* ob3);
typedef N_CDECL_PTR(Tpyobject96574*, Tgetattrofunc96522) (Tpyobject96574* ob1, Tpyobject96574* ob2);
typedef N_CDECL_PTR(NI, Tsetattrofunc96524) (Tpyobject96574* ob1, Tpyobject96574* ob2, Tpyobject96574* ob3);
typedef N_CDECL_PTR(NI, Tvisitproc96536) (Tpyobject96574* ob1, void* p);
typedef N_CDECL_PTR(NI, Ttraverseproc96538) (Tpyobject96574* ob1, Tvisitproc96536 prc, void* p);
typedef N_CDECL_PTR(NI, Tinquiry96494) (Tpyobject96574* ob1);
typedef N_CDECL_PTR(Tpyobject96574*, Trichcmpfunc96540) (Tpyobject96574* ob1, Tpyobject96574* ob2, NI i);
typedef N_CDECL_PTR(Tpyobject96574*, Tgetiterfunc96542) (Tpyobject96574* ob1);
typedef N_CDECL_PTR(Tpyobject96574*, Titernextfunc96544) (Tpyobject96574* ob1);
typedef N_CDECL_PTR(Tpyobject96574*, Tdescrgetfunc96546) (Tpyobject96574* ob1, Tpyobject96574* ob2, Tpyobject96574* ob3);
typedef N_CDECL_PTR(NI, Tdescrsetfunc96548) (Tpyobject96574* ob1, Tpyobject96574* ob2, Tpyobject96574* ob3);
typedef N_CDECL_PTR(NI, Tinitproc96550) (Tpyobject96574* self, Tpyobject96574* args, Tpyobject96574* kwds);
typedef N_CDECL_PTR(Tpyobject96574*, Tallocfunc96554) (Tpytypeobject96626* self, NI nitems);
typedef N_CDECL_PTR(Tpyobject96574*, Tnewfunc96552) (Tpytypeobject96626* subtype, Tpyobject96574* args, Tpyobject96574* kwds);
struct  Tpytypeobject96626  {
  Tpyobject96574 Sup;
NI obsize;
NCSTRING tpname;
NI tpbasicsize;
NI tpitemsize;
Tpydestructor96508 tpdealloc;
Tprintfunc96510 tpprint;
Tgetattrfunc96512 tpgetattr;
Tsetattrfunc96514 tpsetattr;
Tcmpfunc96516 tpcompare;
Treprfunc96518 tprepr;
Tpynumbermethods96556* tpasnumber;
Tpysequencemethods96560* tpassequence;
Tpymappingmethods96564* tpasmapping;
Thashfunc96520 tphash;
Tternaryfunc96492 tpcall;
Treprfunc96518 tpstr;
Tgetattrofunc96522 tpgetattro;
Tsetattrofunc96524 tpsetattro;
Tpybufferprocs96568* tpasbuffer;
NI32 tpflags;
NCSTRING tpdoc;
Ttraverseproc96538 tptraverse;
Tinquiry96494 tpclear;
Trichcmpfunc96540 tprichcompare;
NI32 tpweaklistoffset;
Tgetiterfunc96542 tpiter;
Titernextfunc96544 tpiternext;
Tpymethoddef96586* tpmethods;
Tpymemberdef96590* tpmembers;
Tpygetsetdef96598* tpgetset;
Tpytypeobject96626* tpbase;
Tpyobject96574* tpdict;
Tdescrgetfunc96546 tpdescrget;
Tdescrsetfunc96548 tpdescrset;
NI32 tpdictoffset;
Tinitproc96550 tpinit;
Tallocfunc96554 tpalloc;
Tnewfunc96552 tpnew;
Tpydestructor96508 tpfree;
Tinquiry96494 tpisgc;
Tpyobject96574* tpbases;
Tpyobject96574* tpmro;
Tpyobject96574* tpcache;
Tpyobject96574* tpsubclasses;
Tpyobject96574* tpweaklist;
void* tpxxx7;
void* tpxxx8;
};
typedef N_CDECL_PTR(void, TY98892) (void);
struct  Gcstack51416  {
Gcstack51416* prev;
Gcstack51416* next;
void* starts;
void* pos;
NI maxstacksize;
};
typedef NI TY31222[8];
struct  Pagedesc49355  {
Pagedesc49355* next;
NI key;
TY31222 bits;
};
struct  Basechunk31241  {
NI prevsize;
NI size;
NIM_BOOL used;
};
struct  Smallchunk31243  {
  Basechunk31241 Sup;
Smallchunk31243* next;
Smallchunk31243* prev;
Freecell31233* freelist;
NI free;
NI acc;
NF data;
};
struct  Llchunk31285  {
NI size;
NI acc;
Llchunk31285* next;
};
struct  Bigchunk31245  {
  Basechunk31241 Sup;
Bigchunk31245* next;
Bigchunk31245* prev;
NI align;
NF data;
};
struct  Trunk31213  {
Trunk31213* next;
NI key;
TY31222 bits;
};
typedef Avlnode31289* TY31296[2];
struct  Avlnode31289  {
TY31296 link;
NI key;
NI upperbound;
NI level;
};
typedef N_NIMCALL_PTR(void, TY3889) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3894) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3889 marker;
TY3894 deepcopy;
};
typedef N_CDECL_PTR(Tpyobject96574*, Tbinaryfunc96490) (Tpyobject96574* ob1, Tpyobject96574* ob2);
typedef N_CDECL_PTR(Tpyobject96574*, Tunaryfunc96488) (Tpyobject96574* ob1);
typedef N_CDECL_PTR(NI, Tcoercion96496) (Tpyobject96574** ob1, Tpyobject96574** ob2);
struct  Tpynumbermethods96556  {
Tbinaryfunc96490 nbadd;
Tbinaryfunc96490 nbsubstract;
Tbinaryfunc96490 nbmultiply;
Tbinaryfunc96490 nbdivide;
Tbinaryfunc96490 nbremainder;
Tbinaryfunc96490 nbdivmod;
Tternaryfunc96492 nbpower;
Tunaryfunc96488 nbnegative;
Tunaryfunc96488 nbpositive;
Tunaryfunc96488 nbabsolute;
Tinquiry96494 nbnonzero;
Tunaryfunc96488 nbinvert;
Tbinaryfunc96490 nblshift;
Tbinaryfunc96490 nbrshift;
Tbinaryfunc96490 nband;
Tbinaryfunc96490 nbxor;
Tbinaryfunc96490 nbor;
Tcoercion96496 nbcoerce;
Tunaryfunc96488 nbint;
Tunaryfunc96488 nblong;
Tunaryfunc96488 nbfloat;
Tunaryfunc96488 nboct;
Tunaryfunc96488 nbhex;
Tbinaryfunc96490 nbinplaceadd;
Tbinaryfunc96490 nbinplacesubtract;
Tbinaryfunc96490 nbinplacemultiply;
Tbinaryfunc96490 nbinplacedivide;
Tbinaryfunc96490 nbinplaceremainder;
Tternaryfunc96492 nbinplacepower;
Tbinaryfunc96490 nbinplacelshift;
Tbinaryfunc96490 nbinplacershift;
Tbinaryfunc96490 nbinplaceand;
Tbinaryfunc96490 nbinplacexor;
Tbinaryfunc96490 nbinplaceor;
Tbinaryfunc96490 nbfloordivide;
Tbinaryfunc96490 nbtruedivide;
Tbinaryfunc96490 nbinplacefloordivide;
Tbinaryfunc96490 nbinplacetruedivide;
};
typedef N_CDECL_PTR(Tpyobject96574*, Tintargfunc96498) (Tpyobject96574* ob1, NI i);
typedef N_CDECL_PTR(Tpyobject96574*, Tintintargfunc96500) (Tpyobject96574* ob1, NI i1, NI i2);
typedef N_CDECL_PTR(NI, Tintobjargproc96502) (Tpyobject96574* ob1, NI i, Tpyobject96574* ob2);
typedef N_CDECL_PTR(NI, Tintintobjargproc96504) (Tpyobject96574* ob1, NI i1, NI i2, Tpyobject96574* ob2);
typedef N_CDECL_PTR(NI, Tobjobjproc96534) (Tpyobject96574* ob1, Tpyobject96574* ob2);
struct  Tpysequencemethods96560  {
Tinquiry96494 sqlength;
Tbinaryfunc96490 sqconcat;
Tintargfunc96498 sqrepeat;
Tintargfunc96498 sqitem;
Tintintargfunc96500 sqslice;
Tintobjargproc96502 sqassitem;
Tintintobjargproc96504 sqassslice;
Tobjobjproc96534 sqcontains;
Tbinaryfunc96490 sqinplaceconcat;
Tintargfunc96498 sqinplacerepeat;
};
typedef N_CDECL_PTR(NI, Tobjobjargproc96506) (Tpyobject96574* ob1, Tpyobject96574* ob2, Tpyobject96574* ob3);
struct  Tpymappingmethods96564  {
Tinquiry96494 mplength;
Tbinaryfunc96490 mpsubscript;
Tobjobjargproc96506 mpasssubscript;
};
typedef N_CDECL_PTR(NI, Tgetreadbufferproc96526) (Tpyobject96574* ob1, NI i, void* p);
typedef N_CDECL_PTR(NI, Tgetwritebufferproc96528) (Tpyobject96574* ob1, NI i, void* p);
typedef N_CDECL_PTR(NI, Tgetsegcountproc96530) (Tpyobject96574* ob1, NI i);
typedef N_CDECL_PTR(NI, Tgetcharbufferproc96532) (Tpyobject96574* ob1, NI i, NCSTRING pstr);
struct  Tpybufferprocs96568  {
Tgetreadbufferproc96526 bfgetreadbuffer;
Tgetwritebufferproc96528 bfgetwritebuffer;
Tgetsegcountproc96530 bfgetsegcount;
Tgetcharbufferproc96532 bfgetcharbuffer;
};
typedef N_CDECL_PTR(Tpyobject96574*, Tpycfunction96486) (Tpyobject96574* self, Tpyobject96574* args);
struct  Tpymethoddef96586  {
NCSTRING mlname;
Tpycfunction96486 mlmeth;
NI mlflags;
NCSTRING mldoc;
};
struct  Tpymemberdef96590  {
NCSTRING name;
NI thetype;
NI offset;
NI flags;
NCSTRING doc;
};
typedef N_CDECL_PTR(Tpyobject96574*, Tgetter96592) (Tpyobject96574* obj, void* context);
typedef N_CDECL_PTR(NI, Tsetter96594) (Tpyobject96574* obj, Tpyobject96574* value, void* context);
struct  Tpygetsetdef96598  {
NCSTRING name;
Tgetter96592 get;
Tsetter96594 setter;
NCSTRING doc;
void* closure;
};
struct  Freecell31233  {
Freecell31233* next;
NI zerofield;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
N_NIMCALL(NIM_BOOL, allocinv_38411)(Memregion31291* a);
static N_INLINE(Cell49347*, usrtocell_53046)(void* usr);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_23601)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(NIM_BOOL, isallocatedptr_38407)(Memregion31291* a, void* p);
static N_INLINE(void, Gcdisable_11201)(void);
N_NIMCALL(void, writestacktrace_20207)(void);
static N_INLINE(void, rtladdzct_54604)(Cell49347* c);
N_NOINLINE(void, addzct_53017)(Cellseq49363* s, Cell49347* c);
N_NIMCALL(NimStringDesc*, cstrToNimstr)(NCSTRING str);
static N_INLINE(void, Pyxdecref_99336)(Tpyobject96574* op);
static N_INLINE(void, Pydecref_99297)(Tpyobject96574* op);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_NOINLINE(void, setStackBottom)(void* thestackbottom);
NIM_EXTERNC N_NOINLINE(void, systemInit000)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_dynlibInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_dynlibDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, python_pythonInit000)(void);
NIM_EXTERNC N_NOINLINE(void, python_pythonDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, md5_pythonInit000)(void);
NIM_EXTERNC N_NOINLINE(void, md5_pythonDatInit000)(void);
STRING_LITERAL(TMP312, "Hello world!", 12);
STRING_LITERAL(TMP313, "[SYSASSERT] ", 12);
STRING_LITERAL(TMP314, "begin nimGCunrefNoCycle", 23);
STRING_LITERAL(TMP315, "[GCASSERT] ", 11);
STRING_LITERAL(TMP316, "nimGCunrefNoCycle: isAllocatedPtr", 33);
STRING_LITERAL(TMP317, "end nimGCunrefNoCycle 2", 23);
STRING_LITERAL(TMP318, "end nimGCunrefNoCycle 5", 23);
STRING_LITERAL(TMP319, "Text: ", 6);
STRING_LITERAL(TMP320, "Encoded Text: ", 14);
extern TY97559 Dl_97558;
NimStringDesc* texttoencode_101007;
extern Gcheap51418 gch_51459;
extern TFrame* frameptr_20842;
Tpyobject96574* pytexttoencode_101011;
extern TY97702 Dl_97701;
Tpyobject96574* pyenvironmentmodule_101015;
extern TY97880 Dl_97879;
Tpyobject96574* pyenvironmentvars_101019;
extern TY97669 Dl_97668;
extern TY97655 Dl_97654;
extern TY97690 Dl_97689;
Tpyobject96574* pyencodedtext_101032;
extern TY97648 Dl_97647;
NCSTRING encodedtext_101036;
extern TY97696 Dl_97695;
extern TY98892 Dl_98891;

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_20842 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_20842).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_20842;
	frameptr_20842 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_23601();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_20842 = (*frameptr_20842).prev;
}

static N_INLINE(Cell49347*, usrtocell_53046)(void* usr) {
	Cell49347* result;
	nimfr("usrToCell", "gc.nim")
	result = 0;
	nimln(131, "gc.nim");
	result = ((Cell49347*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(Cell49347))))));
	popFrame();
	return result;
}

static N_INLINE(void, Gcdisable_11201)(void) {
	nimfr("GC_disable", "gc.nim")
	nimln(976, "gc.nim");
	gch_51459.recgclock += ((NI) 1);
	popFrame();
}

static N_INLINE(void, rtladdzct_54604)(Cell49347* c) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(212, "gc.nim");
	addzct_53017((&gch_51459.zct), c);
	popFrame();
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	Cell49347* c;
	nimfr("nimGCunrefNoCycle", "gc.nim")
	nimln(1365, "system.nim");
	{
		NIM_BOOL LOC3;
		nimln(245, "gc.nim");
		LOC3 = 0;
		LOC3 = allocinv_38411((&gch_51459.region));
		if (!!(LOC3)) goto LA4;
		nimln(1366, "system.nim");
		printf("%s%s\012", ((NimStringDesc*) &TMP313)? (((NimStringDesc*) &TMP313))->data:"nil", ((NimStringDesc*) &TMP314)? (((NimStringDesc*) &TMP314))->data:"nil");
		nimln(1367, "system.nim");
		exit(((NI) 1));
	}
	LA4: ;
	nimln(246, "gc.nim");
	c = usrtocell_53046(p);
	nimln(114, "gc.nim");
	{
		NIM_BOOL LOC8;
		nimln(247, "gc.nim");
		LOC8 = 0;
		LOC8 = isallocatedptr_38407((&gch_51459.region), ((void*) (c)));
		if (!!(LOC8)) goto LA9;
		nimln(115, "gc.nim");
		printf("%s%s\012", ((NimStringDesc*) &TMP315)? (((NimStringDesc*) &TMP315))->data:"nil", ((NimStringDesc*) &TMP316)? (((NimStringDesc*) &TMP316))->data:"nil");
		nimln(116, "gc.nim");
		Gcdisable_11201();
		nimln(117, "gc.nim");
		writestacktrace_20207();
		nimln(118, "gc.nim");
		exit(((NI) 1));
	}
	LA9: ;
	nimln(248, "gc.nim");
	{
		nimln(180, "gc.nim");
		(*c).refcount -= ((NI) 8);
		nimln(181, "gc.nim");
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA13;
		nimln(249, "gc.nim");
		rtladdzct_54604(c);
		nimln(1365, "system.nim");
		{
			NIM_BOOL LOC17;
			nimln(250, "gc.nim");
			LOC17 = 0;
			LOC17 = allocinv_38411((&gch_51459.region));
			if (!!(LOC17)) goto LA18;
			nimln(1366, "system.nim");
			printf("%s%s\012", ((NimStringDesc*) &TMP313)? (((NimStringDesc*) &TMP313))->data:"nil", ((NimStringDesc*) &TMP317)? (((NimStringDesc*) &TMP317))->data:"nil");
			nimln(1367, "system.nim");
			exit(((NI) 1));
		}
		LA18: ;
	}
	LA13: ;
	nimln(1365, "system.nim");
	{
		NIM_BOOL LOC22;
		nimln(251, "gc.nim");
		LOC22 = 0;
		LOC22 = allocinv_38411((&gch_51459.region));
		if (!!(LOC22)) goto LA23;
		nimln(1366, "system.nim");
		printf("%s%s\012", ((NimStringDesc*) &TMP313)? (((NimStringDesc*) &TMP313))->data:"nil", ((NimStringDesc*) &TMP318)? (((NimStringDesc*) &TMP318))->data:"nil");
		nimln(1367, "system.nim");
		exit(((NI) 1));
	}
	LA23: ;
	popFrame();
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = 0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (((NI) 0) <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result;
}

static N_INLINE(void, Pydecref_99297)(Tpyobject96574* op) {
	NI TMP321;
	nimfr("Py_DECREF", "python.nim")
	nimln(1315, "python.nim");
	TMP321 = subInt((*op).obrefcnt, ((NI) 1));
	(*op).obrefcnt = (NI)(TMP321);
	nimln(1316, "python.nim");
	{
		if (!((*op).obrefcnt == ((NI) 0))) goto LA3;
		nimln(1317, "python.nim");
		(*(*op).obtype).tpdealloc(op);
	}
	LA3: ;
	popFrame();
}

static N_INLINE(void, Pyxdecref_99336)(Tpyobject96574* op) {
	nimfr("Py_XDECREF", "python.nim")
	nimln(1323, "python.nim");
	{
		nimln(349, "system.nim");
		if (!!((op == NIM_NIL))) goto LA3;
		nimln(1323, "python.nim");
		Pydecref_99297(op);
	}
	LA3: ;
	popFrame();
}

static N_INLINE(void, initStackBottomWith)(void* locals) {
	setStackBottom(locals);
}
void PreMainInner() {
	systemInit000();
	HEX00_dynlibDatInit000();
	python_pythonDatInit000();
	md5_pythonDatInit000();
	HEX00_dynlibInit000();
	python_pythonInit000();
}

void PreMain() {
	void (*volatile inner)();
	systemDatInit000();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	md5_pythonInit000();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)();
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

NIM_EXTERNC N_NOINLINE(void, md5_pythonInit000)(void) {
	NimStringDesc* LOC1;
	NI LOC2;
	NI LOC3;
	NI LOC4;
	NimStringDesc* LOC5;
	nimfr("md5_python", "md5_python.nim")
	nimln(6, "md5_python.nim");
	Dl_97558();
	nimln(7, "md5_python.nim");
	LOC1 = 0;
	LOC1 = texttoencode_101007; texttoencode_101007 = copyStringRC1(((NimStringDesc*) &TMP312));
	if (LOC1) nimGCunrefNoCycle(LOC1);
	nimln(8, "md5_python.nim");
	pytexttoencode_101011 = Dl_97701(texttoencode_101007->data);
	nimln(9, "md5_python.nim");
	pyenvironmentmodule_101015 = Dl_97879("__main__");
	nimln(10, "md5_python.nim");
	pyenvironmentvars_101019 = Dl_97668(pyenvironmentmodule_101015);
	nimln(11, "md5_python.nim");
	LOC2 = 0;
	LOC2 = Dl_97654(pyenvironmentvars_101019, "text", pytexttoencode_101011);
	nimln(12, "md5_python.nim");
	LOC3 = 0;
	LOC3 = Dl_97689("import md5");
	nimln(13, "md5_python.nim");
	LOC4 = 0;
	LOC4 = Dl_97689("encoded_text = md5.md5(text).hexdigest()");
	nimln(14, "md5_python.nim");
	pyencodedtext_101032 = Dl_97647(pyenvironmentvars_101019, "encoded_text");
	nimln(15, "md5_python.nim");
	encodedtext_101036 = Dl_97695(pyencodedtext_101032);
	nimln(16, "md5_python.nim");
	printf("%s%s\012", ((NimStringDesc*) &TMP319)? (((NimStringDesc*) &TMP319))->data:"nil", texttoencode_101007? (texttoencode_101007)->data:"nil");
	nimln(17, "md5_python.nim");
	LOC5 = 0;
	LOC5 = cstrToNimstr(encodedtext_101036);
	printf("%s%s\012", ((NimStringDesc*) &TMP320)? (((NimStringDesc*) &TMP320))->data:"nil", LOC5? (LOC5)->data:"nil");
	nimln(18, "md5_python.nim");
	Pyxdecref_99336(pyenvironmentmodule_101015);
	nimln(19, "md5_python.nim");
	Pyxdecref_99336(pytexttoencode_101011);
	nimln(20, "md5_python.nim");
	Pyxdecref_99336(pyencodedtext_101032);
	nimln(21, "md5_python.nim");
	Dl_98891();
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, md5_pythonDatInit000)(void) {
}

