/* Generated by Nim Compiler v0.12.0 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -g3 -O0  -I/media/marco/Research/Applications/aporia/Nim/lib -o /home/marco/.nimble/pkgs/Pythonize27-1.0.0/tests/nimcache/times.o /home/marco/.nimble/pkgs/Pythonize27-1.0.0/tests/nimcache/times.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <time.h>
#include <string.h>
#include <sys/select.h>
#include <sys/time.h>
typedef struct Timeinterval111812 Timeinterval111812;
typedef struct Timeinfo111810 Timeinfo111810;
typedef struct TNimObject TNimObject;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct TY111972 TY111972;
typedef struct Slice90919 Slice90919;
typedef struct Valueerror4049 Valueerror4049;
typedef struct Exception Exception;
typedef struct Cell49347 Cell49347;
typedef struct Cellseq49363 Cellseq49363;
typedef struct Gcheap51418 Gcheap51418;
typedef struct Gcstack51416 Gcstack51416;
typedef struct Cellset49359 Cellset49359;
typedef struct Pagedesc49355 Pagedesc49355;
typedef struct Memregion31291 Memregion31291;
typedef struct Smallchunk31243 Smallchunk31243;
typedef struct Llchunk31285 Llchunk31285;
typedef struct Bigchunk31245 Bigchunk31245;
typedef struct Intset31217 Intset31217;
typedef struct Trunk31213 Trunk31213;
typedef struct Avlnode31289 Avlnode31289;
typedef struct Gcstat51414 Gcstat51414;
typedef struct TY115100 TY115100;
typedef struct Basechunk31241 Basechunk31241;
typedef struct Freecell31233 Freecell31233;
struct  Timeinterval111812  {
NI milliseconds;
NI seconds;
NI minutes;
NI hours;
NI days;
NI months;
NI years;
};
typedef N_NIMCALL_PTR(void, TY3889) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3894) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3889 marker;
TY3894 deepcopy;
};
struct  TNimObject  {
TNimType* m_type;
};
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct  Timeinfo111810  {
  TNimObject Sup;
NI second;
NI minute;
NI hour;
NI monthday;
NU8 month;
NI year;
NU8 weekday;
NI yearday;
NIM_BOOL isdst;
NimStringDesc* tzname;
NI timezone;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef NU8 TY112455[7];
struct TY111972 {
NimStringDesc* Field0;
NimStringDesc* Field1;
};
typedef NI8 TY112475[7];
typedef NimStringDesc* TY113841[7];
typedef NimStringDesc* TY113857[12];
struct  Slice90919  {
NI a;
NI b;
};
struct  Exception  {
  TNimObject Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
NimStringDesc* trace;
};
struct  Valueerror4049  {
  Exception Sup;
};
struct  Cell49347  {
NI refcount;
TNimType* typ;
};
struct  Cellseq49363  {
NI len;
NI cap;
Cell49347** d;
};
struct  Cellset49359  {
NI counter;
NI max;
Pagedesc49355* head;
Pagedesc49355** data;
};
typedef Smallchunk31243* TY31306[512];
typedef Trunk31213* Trunkbuckets31215[256];
struct  Intset31217  {
Trunkbuckets31215 data;
};
struct  Memregion31291  {
NI minlargeobj;
NI maxlargeobj;
TY31306 freesmallchunks;
Llchunk31285* llmem;
NI currmem;
NI maxmem;
NI freemem;
NI lastsize;
Bigchunk31245* freechunkslist;
Intset31217 chunkstarts;
Avlnode31289* root;
Avlnode31289* deleted;
Avlnode31289* last;
Avlnode31289* freeavlnodes;
};
struct  Gcstat51414  {
NI stackscans;
NI cyclecollections;
NI maxthreshold;
NI maxstacksize;
NI maxstackcells;
NI cycletablesize;
NI64 maxpause;
};
struct  Gcheap51418  {
Gcstack51416* stack;
void* stackbottom;
NI cyclethreshold;
Cellseq49363 zct;
Cellseq49363 decstack;
Cellset49359 cycleroots;
Cellseq49363 tempstack;
NI recgclock;
Memregion31291 region;
Gcstat51414 stat;
};
struct TY115100 {
NI Field0;
NI Field1;
};
struct  Gcstack51416  {
Gcstack51416* prev;
Gcstack51416* next;
void* starts;
void* pos;
NI maxstacksize;
};
typedef NI TY31222[8];
struct  Pagedesc49355  {
Pagedesc49355* next;
NI key;
TY31222 bits;
};
struct  Basechunk31241  {
NI prevsize;
NI size;
NIM_BOOL used;
};
struct  Smallchunk31243  {
  Basechunk31241 Sup;
Smallchunk31243* next;
Smallchunk31243* prev;
Freecell31233* freelist;
NI free;
NI acc;
NF data;
};
struct  Llchunk31285  {
NI size;
NI acc;
Llchunk31285* next;
};
struct  Bigchunk31245  {
  Basechunk31241 Sup;
Bigchunk31245* next;
Bigchunk31245* prev;
NI align;
NF data;
};
struct  Trunk31213  {
Trunk31213* next;
NI key;
TY31222 bits;
};
typedef Avlnode31289* TY31296[2];
struct  Avlnode31289  {
TY31296 link;
NI key;
NI upperbound;
NI level;
};
struct  Freecell31233  {
Freecell31233* next;
NI zerofield;
};
N_NIMCALL(NI, miliseconds_111851)(Timeinterval111812* t);
N_NIMCALL(void, milisecondsHEX3D_111861)(Timeinterval111812* t, NI milliseconds);
N_NIMCALL(time_t, fromseconds_111901)(NI64 since1970);
N_NIMCALL(NIM_BOOL, ntLtTime)(time_t a, time_t b);
N_NIMCALL(NIM_BOOL, ntLeTime)(time_t a, time_t b);
N_NIMCALL(NIM_BOOL, ntEqTime)(time_t a, time_t b);
N_NIMCALL(Timeinterval111812, initinterval_112014)(NI milliseconds, NI seconds, NI minutes, NI hours, NI days, NI months, NI years);
N_NIMCALL(NIM_BOOL, isleapyear_112030)(NI year);
N_NIMCALL(NI, getdaysinmonth_112045)(NU8 month, NI year);
N_NIMCALL(NI, getdaysinyear_112058)(NI year);
static N_INLINE(void, HEX2BHEX3D_112100)(NF* x, NF y);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_23601)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(NF, toseconds_112070)(Timeinfo111810* a, Timeinterval111812* interval);
N_NIMCALL(void, genericAssign)(void* dest, void* src, TNimType* mt);
static N_INLINE(NF, HEX2F_90866)(NI x, NI y);
N_NIMCALL(void, HEX2B_112219)(Timeinfo111810* a, Timeinterval111812* interval, Timeinfo111810* Result);
N_NIMCALL(void, genericReset)(void* dest, TNimType* mt);
N_NIMCALL(void, HEX2D_112232)(Timeinfo111810* a, Timeinterval111812* interval, Timeinfo111810* Result);
N_NIMCALL(void, tmtotimeinfo_112448)(struct tm* tm, NIM_BOOL local, Timeinfo111810* Result);
N_NIMCALL(void, gettzname_111970)(TY111972* Result);
N_NIMCALL(NimStringDesc*, cstrToNimstr)(NCSTRING str);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_NIMCALL(NI, gettimezone_112004)(void);
N_NIMCALL(void, genericShallowAssign)(void* dest, void* src, TNimType* mt);
N_NIMCALL(struct tm, timeinfototm_112468)(Timeinfo111810* t);
N_NIMCALL(NI64, ntDiffTime)(time_t a, time_t b);
N_NIMCALL(NI, getstartmilsecs_112009)(void);
N_NIMCALL(time_t, gettime_111872)(void);
N_NIMCALL(void, getlocaltime_111877)(time_t t, Timeinfo111810* Result);
N_NIMCALL(void, getgmtime_111883)(time_t t, Timeinfo111810* Result);
N_NIMCALL(time_t, timeinfototime_111889)(Timeinfo111810* timeinfo);
N_NIMCALL(NimStringDesc*, tostringtillnl_113221)(NCSTRING p);
N_NIMCALL(NimStringDesc*, addChar)(NimStringDesc* s, NIM_CHAR c);
N_NIMCALL(NimStringDesc*, HEX24_111918)(Timeinfo111810* timeinfo);
N_NIMCALL(NimStringDesc*, HEX24_111924)(time_t time);
N_NIMCALL(NI64, unixtimetowintime_113264)(time_t t);
N_NIMCALL(time_t, wintimetounixtime_113272)(NI64 t);
N_NIMCALL(time_t, fromseconds_111895)(NF since1970);
N_NIMCALL(NF, toseconds_111912)(time_t time);
N_NIMCALL(NF, ntepochTime)(void);
N_NIMCALL(NF, ntcpuTime)(void);
N_NIMCALL(NimStringDesc*, ntgetDateStr)(void);
N_NIMCALL(NimStringDesc*, nimIntToStr)(NI x);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, appendChar)(NimStringDesc* dest, NIM_CHAR c);
N_NIMCALL(NimStringDesc*, nsuIntToStr)(NI x, NI minchars);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
N_NIMCALL(NimStringDesc*, ntgetClockStr)(void);
N_NIMCALL(NimStringDesc*, HEX24_113834)(NU8 day);
N_NIMCALL(NimStringDesc*, HEX24_113850)(NU8 m);
N_NIMCALL(void, formattoken_113866)(Timeinfo111810* info, NimStringDesc* token, NimStringDesc** buf);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b);
N_NIMCALL(NI, hashString)(NimStringDesc* s);
N_NIMCALL(NimStringDesc*, resizeString)(NimStringDesc* dest, NI addlen);
static N_INLINE(NimStringDesc*, HEX5BHEX5D_90912)(NimStringDesc* s, Slice90919 x);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI start_81416, NI last);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI first, NI last);
static N_INLINE(Slice90919, HEX2EHEX2E_104291)(NI a, NI b);
N_NIMCALL(NimStringDesc*, nsuRepeatChar)(NIM_CHAR c, NI count);
N_NIMCALL(void, insert_92601)(NimStringDesc** x, NimStringDesc* item, NI i);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
static N_INLINE(Cell49347*, usrtocell_53046)(void* usr);
static N_INLINE(void, rtladdzct_54604)(Cell49347* c);
N_NOINLINE(void, addzct_53017)(Cellseq49363* s, Cell49347* c);
N_NIMCALL(void, raiseException)(Exception* e, NCSTRING ename);
N_NIMCALL(NimStringDesc*, format_113990)(Timeinfo111810* info, NimStringDesc* f);
N_NIMCALL(void, parsetoken_114058)(Timeinfo111810* info, NimStringDesc* token, NimStringDesc* value, NI* j);
N_NIMCALL(NI, npuParseInt)(NimStringDesc* s, NI* number, NI start);
N_NIMCALL(NI, nsuParseInt)(NimStringDesc* s);
N_NIMCALL(NimStringDesc*, nsuToLowerStr)(NimStringDesc* s);
N_NIMCALL(NI, nsuCmpIgnoreCase)(NimStringDesc* a, NimStringDesc* b);
N_NIMCALL(NimStringDesc*, nimCharToStr)(NIM_CHAR x);
N_NIMCALL(NimStringDesc*, nsuToUpperStr)(NimStringDesc* s);
N_NIMCALL(void, parse_114965)(NimStringDesc* value, NimStringDesc* layout, Timeinfo111810* Result);
N_NIMCALL(NI, countleapyears_115061)(NI yearspan);
N_NIMCALL(NI, countdays_115074)(NI yearspan);
N_NIMCALL(NI, countyears_115085)(NI dayspan);
N_NIMCALL(TY115100, countyearsanddays_115097)(NI dayspan);
N_NIMCALL(NU8, getdayofweek_115126)(NI day, NI month, NI year);
N_NIMCALL(NU8, getdayofweekjulian_115147)(NI day, NI month, NI year);
N_NIMCALL(void, timetotimeinfo_115164)(time_t t, Timeinfo111810* Result);
N_NIMCALL(Timeinterval111812, timetotimeinterval_115234)(time_t t);
NIM_CONST TY112455 weekdays_112453 = {((NU8) 6),
((NU8) 0),
((NU8) 1),
((NU8) 2),
((NU8) 3),
((NU8) 4),
((NU8) 5)}
;
STRING_LITERAL(TMP330, "UTC", 3);
NIM_CONST TY112475 weekdays_112472 = {((NI8) 1),
((NI8) 2),
((NI8) 3),
((NI8) 4),
((NI8) 5),
((NI8) 6),
((NI8) 0)}
;
STRING_LITERAL(TMP331, "", 0);
STRING_LITERAL(TMP332, "Monday", 6);
STRING_LITERAL(TMP333, "Tuesday", 7);
STRING_LITERAL(TMP334, "Wednesday", 9);
STRING_LITERAL(TMP335, "Thursday", 8);
STRING_LITERAL(TMP336, "Friday", 6);
STRING_LITERAL(TMP337, "Saturday", 8);
STRING_LITERAL(TMP338, "Sunday", 6);
NIM_CONST TY113841 lookup_113838 = {((NimStringDesc*) &TMP332),
((NimStringDesc*) &TMP333),
((NimStringDesc*) &TMP334),
((NimStringDesc*) &TMP335),
((NimStringDesc*) &TMP336),
((NimStringDesc*) &TMP337),
((NimStringDesc*) &TMP338)}
;
STRING_LITERAL(TMP339, "January", 7);
STRING_LITERAL(TMP340, "February", 8);
STRING_LITERAL(TMP341, "March", 5);
STRING_LITERAL(TMP342, "April", 5);
STRING_LITERAL(TMP343, "May", 3);
STRING_LITERAL(TMP344, "June", 4);
STRING_LITERAL(TMP345, "July", 4);
STRING_LITERAL(TMP346, "August", 6);
STRING_LITERAL(TMP347, "September", 9);
STRING_LITERAL(TMP348, "October", 7);
STRING_LITERAL(TMP349, "November", 8);
STRING_LITERAL(TMP350, "December", 8);
NIM_CONST TY113857 lookup_113854 = {((NimStringDesc*) &TMP339),
((NimStringDesc*) &TMP340),
((NimStringDesc*) &TMP341),
((NimStringDesc*) &TMP342),
((NimStringDesc*) &TMP343),
((NimStringDesc*) &TMP344),
((NimStringDesc*) &TMP345),
((NimStringDesc*) &TMP346),
((NimStringDesc*) &TMP347),
((NimStringDesc*) &TMP348),
((NimStringDesc*) &TMP349),
((NimStringDesc*) &TMP350)}
;
STRING_LITERAL(TMP351, "d", 1);
STRING_LITERAL(TMP352, "dd", 2);
STRING_LITERAL(TMP353, "ddd", 3);
STRING_LITERAL(TMP354, "dddd", 4);
STRING_LITERAL(TMP355, "h", 1);
STRING_LITERAL(TMP356, "hh", 2);
STRING_LITERAL(TMP357, "H", 1);
STRING_LITERAL(TMP358, "HH", 2);
STRING_LITERAL(TMP359, "m", 1);
STRING_LITERAL(TMP360, "mm", 2);
STRING_LITERAL(TMP361, "M", 1);
STRING_LITERAL(TMP362, "MM", 2);
STRING_LITERAL(TMP363, "MMM", 3);
STRING_LITERAL(TMP364, "MMMM", 4);
STRING_LITERAL(TMP365, "s", 1);
STRING_LITERAL(TMP366, "ss", 2);
STRING_LITERAL(TMP367, "t", 1);
STRING_LITERAL(TMP368, "tt", 2);
STRING_LITERAL(TMP369, "y", 1);
STRING_LITERAL(TMP370, "yy", 2);
STRING_LITERAL(TMP371, "yyy", 3);
STRING_LITERAL(TMP372, "yyyy", 4);
STRING_LITERAL(TMP373, "yyyyy", 5);
STRING_LITERAL(TMP374, "z", 1);
STRING_LITERAL(TMP375, "zz", 2);
STRING_LITERAL(TMP376, "zzz", 3);
STRING_LITERAL(TMP377, "ZZZ", 3);
STRING_LITERAL(TMP378, "0", 1);
STRING_LITERAL(TMP379, "PM", 2);
STRING_LITERAL(TMP380, "AM", 2);
STRING_LITERAL(TMP381, ":00", 3);
STRING_LITERAL(TMP382, "Invalid format string: ", 23);
STRING_LITERAL(TMP403, "sun", 3);
STRING_LITERAL(TMP404, "mon", 3);
STRING_LITERAL(TMP405, "tue", 3);
STRING_LITERAL(TMP406, "wed", 3);
STRING_LITERAL(TMP407, "thu", 3);
STRING_LITERAL(TMP408, "fri", 3);
STRING_LITERAL(TMP409, "sat", 3);
STRING_LITERAL(TMP410, "Couldn\'t parse day of week (ddd), got: ", 39);
STRING_LITERAL(TMP414, "sunday", 6);
STRING_LITERAL(TMP415, "monday", 6);
STRING_LITERAL(TMP416, "tuesday", 7);
STRING_LITERAL(TMP417, "wednesday", 9);
STRING_LITERAL(TMP418, "thursday", 8);
STRING_LITERAL(TMP419, "friday", 6);
STRING_LITERAL(TMP420, "saturday", 8);
STRING_LITERAL(TMP421, "Couldn\'t parse day of week (dddd), got: ", 40);
STRING_LITERAL(TMP422, "jan", 3);
STRING_LITERAL(TMP423, "feb", 3);
STRING_LITERAL(TMP424, "mar", 3);
STRING_LITERAL(TMP425, "apr", 3);
STRING_LITERAL(TMP426, "may", 3);
STRING_LITERAL(TMP427, "jun", 3);
STRING_LITERAL(TMP428, "jul", 3);
STRING_LITERAL(TMP429, "aug", 3);
STRING_LITERAL(TMP430, "sep", 3);
STRING_LITERAL(TMP431, "oct", 3);
STRING_LITERAL(TMP432, "nov", 3);
STRING_LITERAL(TMP433, "dec", 3);
STRING_LITERAL(TMP434, "Couldn\'t parse month (MMM), got: ", 33);
STRING_LITERAL(TMP435, "january", 7);
STRING_LITERAL(TMP436, "february", 8);
STRING_LITERAL(TMP437, "march", 5);
STRING_LITERAL(TMP438, "april", 5);
STRING_LITERAL(TMP439, "june", 4);
STRING_LITERAL(TMP440, "july", 4);
STRING_LITERAL(TMP441, "august", 6);
STRING_LITERAL(TMP442, "september", 9);
STRING_LITERAL(TMP443, "october", 7);
STRING_LITERAL(TMP444, "november", 8);
STRING_LITERAL(TMP445, "december", 8);
STRING_LITERAL(TMP446, "Couldn\'t parse month (MMMM), got: ", 34);
STRING_LITERAL(TMP447, "Couldn\'t parse timezone offset (z), got: ", 41);
STRING_LITERAL(TMP448, "Couldn\'t parse timezone offset (zz), got: ", 42);
STRING_LITERAL(TMP449, "Couldn\'t parse timezone offset (zzz), got: ", 43);
extern TFrame* frameptr_20842;
extern TNimType NTI4011; /* RootObj */
TNimType NTI111810; /* TimeInfo */
extern TNimType NTI108; /* int */
TNimType NTI111813; /* range 0..61(int) */
TNimType NTI111816; /* range 0..59(int) */
TNimType NTI111818; /* range 0..23(int) */
TNimType NTI111821; /* range 1..31(int) */
TNimType NTI111606; /* Month */
TNimType NTI111608; /* WeekDay */
TNimType NTI111827; /* range 0..365(int) */
extern TNimType NTI138; /* bool */
extern TNimType NTI149; /* string */
extern TNimType NTI25428; /* ref ValueError */
extern TNimType NTI4049; /* ValueError */
extern Gcheap51418 gch_51459;

N_NIMCALL(NI, miliseconds_111851)(Timeinterval111812* t) {
	NI result;
	result = 0;
	result = (*t).milliseconds;
	return result;
}

N_NIMCALL(void, milisecondsHEX3D_111861)(Timeinterval111812* t, NI milliseconds) {
	(*t).milliseconds = milliseconds;
}

N_NIMCALL(time_t, fromseconds_111901)(NI64 since1970) {
	time_t result;
	result = 0;
	result = fromseconds_111895(((NF) (since1970)));
	return result;
}

N_NIMCALL(NIM_BOOL, ntLtTime)(time_t a, time_t b) {
	NIM_BOOL result;
	NI64 LOC1;
	result = 0;
	LOC1 = 0;
	LOC1 = ntDiffTime(a, b);
	result = (LOC1 < IL64(0));
	return result;
}

N_NIMCALL(NIM_BOOL, ntLeTime)(time_t a, time_t b) {
	NIM_BOOL result;
	NI64 LOC1;
	result = 0;
	LOC1 = 0;
	LOC1 = ntDiffTime(a, b);
	result = (LOC1 <= IL64(0));
	return result;
}

N_NIMCALL(NIM_BOOL, ntEqTime)(time_t a, time_t b) {
	NIM_BOOL result;
	NI64 LOC1;
	result = 0;
	LOC1 = 0;
	LOC1 = ntDiffTime(a, b);
	result = (LOC1 == IL64(0));
	return result;
}

N_NIMCALL(Timeinterval111812, initinterval_112014)(NI milliseconds, NI seconds, NI minutes, NI hours, NI days, NI months, NI years) {
	Timeinterval111812 result;
	memset((void*)(&result), 0, sizeof(result));
	result.milliseconds = milliseconds;
	result.seconds = seconds;
	result.minutes = minutes;
	result.hours = hours;
	result.days = days;
	result.months = months;
	result.years = years;
	return result;
}

N_NIMCALL(NIM_BOOL, isleapyear_112030)(NI year) {
	NIM_BOOL result;
{	result = 0;
	{
		if (!(((NI) ((NI)(year % ((NI) 400)))) == ((NI) 0))) goto LA3;
		result = NIM_TRUE;
		goto BeforeRet;
	}
	goto LA1;
	LA3: ;
	{
		if (!(((NI) ((NI)(year % ((NI) 100)))) == ((NI) 0))) goto LA6;
		result = NIM_FALSE;
		goto BeforeRet;
	}
	goto LA1;
	LA6: ;
	{
		if (!(((NI) ((NI)(year % ((NI) 4)))) == ((NI) 0))) goto LA9;
		result = NIM_TRUE;
		goto BeforeRet;
	}
	goto LA1;
	LA9: ;
	{
		result = NIM_FALSE;
		goto BeforeRet;
	}
	LA1: ;
	}BeforeRet: ;
	return result;
}

N_NIMCALL(NI, getdaysinmonth_112045)(NU8 month, NI year) {
	NI result;
	result = 0;
	switch (month) {
	case ((NU8) 1):
	{
		{
			NIM_BOOL LOC4;
			LOC4 = 0;
			LOC4 = isleapyear_112030(year);
			if (!LOC4) goto LA5;
			result = ((NI) 29);
		}
		goto LA2;
		LA5: ;
		{
			result = ((NI) 28);
		}
		LA2: ;
	}
	break;
	case ((NU8) 3):
	case ((NU8) 5):
	case ((NU8) 8):
	case ((NU8) 10):
	{
		result = ((NI) 30);
	}
	break;
	default:
	{
		result = ((NI) 31);
	}
	break;
	}
	return result;
}

N_NIMCALL(NI, getdaysinyear_112058)(NI year) {
	NI result;
	NI LOC1;
	result = 0;
	LOC1 = 0;
	{
		NIM_BOOL LOC4;
		LOC4 = 0;
		LOC4 = isleapyear_112030(year);
		if (!LOC4) goto LA5;
		LOC1 = ((NI) 1);
	}
	goto LA2;
	LA5: ;
	{
		LOC1 = ((NI) 0);
	}
	LA2: ;
	result = (NI)(((NI) 365) + LOC1);
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_20842 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_20842).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_20842;
	frameptr_20842 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_23601();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_20842 = (*frameptr_20842).prev;
}

static N_INLINE(void, HEX2BHEX3D_112100)(NF* x, NF y) {
	nimfr("+=", "system.nim")
	nimln(3270, "system.nim");
	(*x) = ((NF)((*x)) + (NF)(y));
	popFrame();
}

static N_INLINE(NF, HEX2F_90866)(NI x, NI y) {
	NF result;
	nimfr("/", "system.nim")
	result = 0;
	nimln(3124, "system.nim");
	result = ((NF)(((double) (x))) / (NF)(((double) (y))));
	popFrame();
	return result;
}

N_NIMCALL(NF, toseconds_112070)(Timeinfo111810* a, Timeinterval111812* interval) {
	NF result;
	Timeinfo111810 anew;
	Timeinterval111812 newinterv;
	NU8 curmonth;
	NF LOC10;
	result = 0;
	memset((void*)(&anew), 0, sizeof(anew));
	anew.Sup.m_type = (&NTI111810);
	genericAssign((void*)(&anew), (void*)a, (&NTI111810));
	newinterv = (*interval);
	result = 0.0;
	newinterv.months += (NI)((*interval).years * ((NI) 12));
	curmonth = anew.month;
	{
		NI mth_112097;
		NI HEX3Atmp_112193;
		NI res_112196;
		mth_112097 = 0;
		HEX3Atmp_112193 = 0;
		HEX3Atmp_112193 = newinterv.months;
		res_112196 = ((NI) 1);
		{
			while (1) {
				NI LOC4;
				if (!(res_112196 <= HEX3Atmp_112193)) goto LA3;
				mth_112097 = res_112196;
				LOC4 = 0;
				LOC4 = getdaysinmonth_112045(curmonth, anew.year);
				HEX2BHEX3D_112100((&result), ((NF) ((NI)((NI)((NI)(LOC4 * ((NI) 24)) * ((NI) 60)) * ((NI) 60)))));
				{
					if (!(curmonth == ((NU8) 11))) goto LA7;
					curmonth = ((NU8) 0);
					anew.year += ((NI) 1);
				}
				goto LA5;
				LA7: ;
				{
					curmonth += ((NI) 1);
				}
				LA5: ;
				res_112196 += ((NI) 1);
			} LA3: ;
		}
	}
	HEX2BHEX3D_112100((&result), ((NF) ((NI)((NI)((NI)(newinterv.days * ((NI) 24)) * ((NI) 60)) * ((NI) 60)))));
	HEX2BHEX3D_112100((&result), ((NF) ((NI)((NI)(newinterv.hours * ((NI) 60)) * ((NI) 60)))));
	HEX2BHEX3D_112100((&result), ((NF) ((NI)(newinterv.minutes * ((NI) 60)))));
	HEX2BHEX3D_112100((&result), ((NF) (newinterv.seconds)));
	LOC10 = 0;
	LOC10 = HEX2F_90866(newinterv.milliseconds, ((NI) 1000));
	HEX2BHEX3D_112100((&result), LOC10);
	return result;
}

N_NIMCALL(void, HEX2B_112219)(Timeinfo111810* a, Timeinterval111812* interval, Timeinfo111810* Result) {
	NF t;
	time_t LOC1;
	NF secs;
	time_t LOC2;
	LOC1 = 0;
	LOC1 = timeinfototime_111889(a);
	t = toseconds_111912(LOC1);
	secs = toseconds_112070(a, interval);
	LOC2 = 0;
	LOC2 = fromseconds_111895(((NF)(t) + (NF)(secs)));
	genericReset((void*)Result, (&NTI111810));
	(*Result).Sup.m_type = (&NTI111810);
	getlocaltime_111877(LOC2, Result);
}

N_NIMCALL(void, HEX2D_112232)(Timeinfo111810* a, Timeinterval111812* interval, Timeinfo111810* Result) {
	NF t;
	time_t LOC1;
	NF secs;
	time_t LOC2;
	LOC1 = 0;
	LOC1 = timeinfototime_111889(a);
	t = toseconds_111912(LOC1);
	secs = toseconds_112070(a, interval);
	LOC2 = 0;
	LOC2 = fromseconds_111895(((NF)(t) - (NF)(secs)));
	genericReset((void*)Result, (&NTI111810));
	(*Result).Sup.m_type = (&NTI111810);
	getlocaltime_111877(LOC2, Result);
}

N_NIMCALL(void, gettzname_111970)(TY111972* Result) {
{	unsureAsgnRef((void**) (&(*Result).Field0), cstrToNimstr(tzname[(((NI) 0))- 0]));
	unsureAsgnRef((void**) (&(*Result).Field1), cstrToNimstr(tzname[(((NI) 1))- 0]));
	goto BeforeRet;
	}BeforeRet: ;
}

N_NIMCALL(NI, gettimezone_112004)(void) {
	NI result;
{	result = 0;
	result = timezone;
	goto BeforeRet;
	}BeforeRet: ;
	return result;
}

N_NIMCALL(void, tmtotimeinfo_112448)(struct tm* tm, NIM_BOOL local, Timeinfo111810* Result) {
	Timeinfo111810 LOC1;
	memset((void*)(&LOC1), 0, sizeof(LOC1));
	LOC1.Sup.m_type = (&NTI111810);
	memset((void*)(&LOC1), 0, sizeof(LOC1));
	LOC1.Sup.m_type = (&NTI111810);
	LOC1.second = ((NI) (((NI) ((*tm).tm_sec))));
	LOC1.minute = ((NI) (((NI) ((*tm).tm_min))));
	LOC1.hour = ((NI) (((NI) ((*tm).tm_hour))));
	LOC1.monthday = ((NI) (((NI) ((*tm).tm_mday))));
	LOC1.month = ((NU8) ((*tm).tm_mon));
	LOC1.year = ((NI) ((NI32)((*tm).tm_year + ((NI32) 1900))));
	LOC1.weekday = weekdays_112453[(((NI) ((*tm).tm_wday)))- 0];
	LOC1.yearday = ((NI) (((NI) ((*tm).tm_yday))));
	LOC1.isdst = (((NI32) 0) < (*tm).tm_isdst);
	{
		if (!local) goto LA4;
		{
			TY111972 LOC10;
			if (!(((NI32) 0) < (*tm).tm_isdst)) goto LA8;
			memset((void*)(&LOC10), 0, sizeof(LOC10));
			gettzname_111970((&LOC10));
			LOC1.tzname = copyString(LOC10.Field1);
		}
		goto LA6;
		LA8: ;
		{
			TY111972 LOC12;
			memset((void*)(&LOC12), 0, sizeof(LOC12));
			gettzname_111970((&LOC12));
			LOC1.tzname = copyString(LOC12.Field0);
		}
		LA6: ;
	}
	goto LA2;
	LA4: ;
	{
		LOC1.tzname = copyString(((NimStringDesc*) &TMP330));
	}
	LA2: ;
	{
		if (!local) goto LA16;
		LOC1.timezone = gettimezone_112004();
	}
	goto LA14;
	LA16: ;
	{
		LOC1.timezone = ((NI) 0);
	}
	LA14: ;
	genericShallowAssign((void*)Result, (void*)(&LOC1), (&NTI111810));
}

N_NIMCALL(struct tm, timeinfototm_112468)(Timeinfo111810* t) {
	struct tm result;
	NI LOC1;
	memset((void*)(&result), 0, sizeof(result));
	result.tm_sec = ((int) ((*t).second));
	result.tm_min = ((int) ((*t).minute));
	result.tm_hour = ((int) ((*t).hour));
	result.tm_mday = ((int) ((*t).monthday));
	result.tm_mon = ((int) ((*t).month));
	result.tm_year = ((int) ((NI)((*t).year - ((NI) 1900))));
	result.tm_wday = ((int) (weekdays_112472[((*t).weekday)- 0]));
	result.tm_yday = ((int) ((*t).yearday));
	LOC1 = 0;
	{
		if (!(*t).isdst) goto LA4;
		LOC1 = ((NI) 1);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) 0);
	}
	LA2: ;
	result.tm_isdst = ((int) (LOC1));
	return result;
}

N_NIMCALL(NI64, ntDiffTime)(time_t a, time_t b) {
	NI64 result;
	NF LOC1;
{	result = 0;
	LOC1 = 0;
	LOC1 = difftime(a, b);
	result = float64ToInt64(LOC1);
	goto BeforeRet;
	}BeforeRet: ;
	return result;
}

N_NIMCALL(NI, getstartmilsecs_112009)(void) {
	NI result;
	NI LOC1;
	result = 0;
	LOC1 = 0;
	LOC1 = clock();
	result = (NI)(LOC1 / (NI)(CLOCKS_PER_SEC / ((NI) 1000)));
	return result;
}

N_NIMCALL(time_t, gettime_111872)(void) {
	time_t result;
{	result = 0;
	result = time(NIM_NIL);
	goto BeforeRet;
	}BeforeRet: ;
	return result;
}

N_NIMCALL(void, getlocaltime_111877)(time_t t, Timeinfo111810* Result) {
	time_t a;
	struct tm* lt;
	a = t;
	lt = localtime((&a));
	genericReset((void*)Result, (&NTI111810));
	(*Result).Sup.m_type = (&NTI111810);
	tmtotimeinfo_112448((&(*lt)), NIM_TRUE, Result);
}

N_NIMCALL(void, getgmtime_111883)(time_t t, Timeinfo111810* Result) {
	time_t a;
	struct tm* LOC1;
	a = t;
	LOC1 = 0;
	LOC1 = gmtime((&a));
	genericReset((void*)Result, (&NTI111810));
	(*Result).Sup.m_type = (&NTI111810);
	tmtotimeinfo_112448((&(*LOC1)), NIM_FALSE, Result);
}

N_NIMCALL(time_t, timeinfototime_111889)(Timeinfo111810* timeinfo) {
	time_t result;
	Timeinfo111810 ctimeinfo;
	struct tm LOC1;
{	result = 0;
	memset((void*)(&ctimeinfo), 0, sizeof(ctimeinfo));
	ctimeinfo.Sup.m_type = (&NTI111810);
	genericAssign((void*)(&ctimeinfo), (void*)timeinfo, (&NTI111810));
	LOC1 = timeinfototm_112468((&ctimeinfo));
	result = mktime((&LOC1));
	goto BeforeRet;
	}BeforeRet: ;
	return result;
}

N_NIMCALL(NimStringDesc*, tostringtillnl_113221)(NCSTRING p) {
	NimStringDesc* result;
	NI i;
	result = 0;
	result = copyString(((NimStringDesc*) &TMP331));
	i = ((NI) 0);
	{
		while (1) {
			NIM_BOOL LOC3;
			NIM_BOOL LOC4;
			LOC3 = 0;
			LOC4 = 0;
			LOC4 = !(((NU8)(p[i]) == (NU8)(0)));
			if (!(LOC4)) goto LA5;
			LOC4 = !(((NU8)(p[i]) == (NU8)(10)));
			LA5: ;
			LOC3 = LOC4;
			if (!(LOC3)) goto LA6;
			LOC3 = !(((NU8)(p[i]) == (NU8)(13)));
			LA6: ;
			if (!LOC3) goto LA2;
			result = addChar(result, p[i]);
			i += ((NI) 1);
		} LA2: ;
	}
	return result;
}

N_NIMCALL(NimStringDesc*, HEX24_111918)(Timeinfo111810* timeinfo) {
	NimStringDesc* result;
	NCSTRING p;
	struct tm LOC1;
	result = 0;
	LOC1 = timeinfototm_112468(timeinfo);
	p = asctime((&LOC1));
	result = tostringtillnl_113221(p);
	return result;
}

N_NIMCALL(NimStringDesc*, HEX24_111924)(time_t time) {
	NimStringDesc* result;
	time_t a;
	NCSTRING LOC1;
{	result = 0;
	a = time;
	LOC1 = 0;
	LOC1 = ctime((&a));
	result = tostringtillnl_113221(LOC1);
	goto BeforeRet;
	}BeforeRet: ;
	return result;
}

N_NIMCALL(NI64, unixtimetowintime_113264)(time_t t) {
	NI64 result;
	result = 0;
	result = (NI64)((NI64)(((NI64) (t)) * IL64(10000000)) + IL64(116444736000000000));
	return result;
}

N_NIMCALL(time_t, wintimetounixtime_113272)(NI64 t) {
	time_t result;
	result = 0;
	result = ((time_t) ((NI64)((NI64)(t - IL64(116444736000000000)) / IL64(10000000))));
	return result;
}

N_NIMCALL(time_t, fromseconds_111895)(NF since1970) {
	time_t result;
	result = 0;
	result = ((time_t) (since1970));
	return result;
}

N_NIMCALL(NF, toseconds_111912)(time_t time) {
	NF result;
	result = 0;
	result = ((NF) (time));
	return result;
}

N_NIMCALL(NF, ntepochTime)(void) {
	NF result;
	struct timeval a;
	result = 0;
	memset((void*)(&a), 0, sizeof(a));
	gettimeofday((&a), NIM_NIL);
	result = ((NF)(((double) (a.tv_sec))) + (NF)(((NF)(((double) (a.tv_usec))) * (NF)(9.9999999999999995e-07))));
	return result;
}

N_NIMCALL(NF, ntcpuTime)(void) {
	NF result;
	NI LOC1;
	result = 0;
	LOC1 = 0;
	LOC1 = clock();
	result = ((NF)(((double) (LOC1))) / (NF)(((double) (CLOCKS_PER_SEC))));
	return result;
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	memcpy(((NCSTRING) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((NCSTRING) ((*src).data)), (NI)((*src).Sup.len + ((NI) 1)));
	(*dest).Sup.len += (*src).Sup.len;
}

static N_INLINE(void, appendChar)(NimStringDesc* dest, NIM_CHAR c) {
	(*dest).data[((*dest).Sup.len)- 0] = c;
	(*dest).data[((NI)((*dest).Sup.len + ((NI) 1)))- 0] = 0;
	(*dest).Sup.len += ((NI) 1);
}

N_NIMCALL(NimStringDesc*, ntgetDateStr)(void) {
	NimStringDesc* result;
	Timeinfo111810 ti;
	time_t LOC1;
	NimStringDesc* LOC2;
	NimStringDesc* LOC3;
	NimStringDesc* LOC4;
	NimStringDesc* LOC5;
	result = 0;
	memset((void*)(&ti), 0, sizeof(ti));
	ti.Sup.m_type = (&NTI111810);
	LOC1 = 0;
	LOC1 = gettime_111872();
	memset((void*)(&ti), 0, sizeof(ti));
	ti.Sup.m_type = (&NTI111810);
	getlocaltime_111877(LOC1, (&ti));
	LOC2 = 0;
	LOC3 = 0;
	LOC3 = nimIntToStr(ti.year);
	LOC4 = 0;
	LOC4 = nsuIntToStr(((NI) ((NI)(((NI) (ti.month)) + ((NI) 1)))), ((NI) 2));
	LOC5 = 0;
	LOC5 = nsuIntToStr(((NI) (ti.monthday)), ((NI) 2));
	LOC2 = rawNewString(LOC3->Sup.len + LOC4->Sup.len + LOC5->Sup.len + 2);
appendString(LOC2, LOC3);
appendChar(LOC2, 45);
appendString(LOC2, LOC4);
appendChar(LOC2, 45);
appendString(LOC2, LOC5);
	result = LOC2;
	return result;
}

N_NIMCALL(NimStringDesc*, ntgetClockStr)(void) {
	NimStringDesc* result;
	Timeinfo111810 ti;
	time_t LOC1;
	NimStringDesc* LOC2;
	NimStringDesc* LOC3;
	NimStringDesc* LOC4;
	NimStringDesc* LOC5;
	result = 0;
	memset((void*)(&ti), 0, sizeof(ti));
	ti.Sup.m_type = (&NTI111810);
	LOC1 = 0;
	LOC1 = gettime_111872();
	memset((void*)(&ti), 0, sizeof(ti));
	ti.Sup.m_type = (&NTI111810);
	getlocaltime_111877(LOC1, (&ti));
	LOC2 = 0;
	LOC3 = 0;
	LOC3 = nsuIntToStr(((NI) (ti.hour)), ((NI) 2));
	LOC4 = 0;
	LOC4 = nsuIntToStr(((NI) (ti.minute)), ((NI) 2));
	LOC5 = 0;
	LOC5 = nsuIntToStr(((NI) (ti.second)), ((NI) 2));
	LOC2 = rawNewString(LOC3->Sup.len + LOC4->Sup.len + LOC5->Sup.len + 2);
appendString(LOC2, LOC3);
appendChar(LOC2, 58);
appendString(LOC2, LOC4);
appendChar(LOC2, 58);
appendString(LOC2, LOC5);
	result = LOC2;
	return result;
}

N_NIMCALL(NimStringDesc*, HEX24_113834)(NU8 day) {
	NimStringDesc* result;
{	result = 0;
	result = copyString(lookup_113838[(day)- 0]);
	goto BeforeRet;
	}BeforeRet: ;
	return result;
}

N_NIMCALL(NimStringDesc*, HEX24_113850)(NU8 m) {
	NimStringDesc* result;
{	result = 0;
	result = copyString(lookup_113854[(m)- 0]);
	goto BeforeRet;
	}BeforeRet: ;
	return result;
}

static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b) {
	NIM_BOOL result;
	NIM_BOOL LOC11;
	int LOC13;
{	result = 0;
	{
		if (!(a == b)) goto LA3;
		result = NIM_TRUE;
		goto BeforeRet;
	}
	LA3: ;
	{
		NIM_BOOL LOC7;
		LOC7 = 0;
		LOC7 = (a == NIM_NIL);
		if (LOC7) goto LA8;
		LOC7 = (b == NIM_NIL);
		LA8: ;
		if (!LOC7) goto LA9;
		result = NIM_FALSE;
		goto BeforeRet;
	}
	LA9: ;
	LOC11 = 0;
	LOC11 = ((*a).Sup.len == (*b).Sup.len);
	if (!(LOC11)) goto LA12;
	LOC13 = 0;
	LOC13 = memcmp(((NCSTRING) ((*a).data)), ((NCSTRING) ((*b).data)), (*a).Sup.len);
	LOC11 = (LOC13 == ((NI32) 0));
	LA12: ;
	result = LOC11;
	goto BeforeRet;
	}BeforeRet: ;
	return result;
}

static N_INLINE(NimStringDesc*, HEX5BHEX5D_90912)(NimStringDesc* s, Slice90919 x) {
	NimStringDesc* result;
	nimfr("[]", "system.nim")
	result = 0;
	nimln(3145, "system.nim");
	result = copyStrLast(s, x.a, x.b);
	popFrame();
	return result;
}

static N_INLINE(Slice90919, HEX2EHEX2E_104291)(NI a, NI b) {
	Slice90919 result;
	nimfr("..", "system.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln(270, "system.nim");
	result.a = a;
	nimln(271, "system.nim");
	result.b = b;
	popFrame();
	return result;
}

static N_INLINE(Cell49347*, usrtocell_53046)(void* usr) {
	Cell49347* result;
	nimfr("usrToCell", "gc.nim")
	result = 0;
	nimln(131, "gc.nim");
	result = ((Cell49347*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(Cell49347))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtladdzct_54604)(Cell49347* c) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(212, "gc.nim");
	addzct_53017((&gch_51459.zct), c);
	popFrame();
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr("asgnRefNoCycle", "gc.nim")
	nimln(264, "gc.nim");
	{
		Cell49347* c;
		nimln(349, "system.nim");
		if (!!((src == NIM_NIL))) goto LA3;
		nimln(265, "gc.nim");
		c = usrtocell_53046(src);
		nimln(182, "gc.nim");
		(*c).refcount += ((NI) 8);
	}
	LA3: ;
	nimln(267, "gc.nim");
	{
		Cell49347* c;
		nimln(349, "system.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA7;
		nimln(268, "gc.nim");
		c = usrtocell_53046((*dest));
		nimln(269, "gc.nim");
		{
			nimln(180, "gc.nim");
			(*c).refcount -= ((NI) 8);
			nimln(181, "gc.nim");
			if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA11;
			nimln(270, "gc.nim");
			rtladdzct_54604(c);
		}
		LA11: ;
	}
	LA7: ;
	nimln(271, "gc.nim");
	(*dest) = src;
	popFrame();
}

N_NIMCALL(void, formattoken_113866)(Timeinfo111810* info, NimStringDesc* token, NimStringDesc** buf) {
	switch (hashString(token) & 31) {
	case 0: 
if (eqStrings(token, ((NimStringDesc*) &TMP331))) goto LA28;
break;
	case 1: 
if (eqStrings(token, ((NimStringDesc*) &TMP360))) goto LA10;
break;
	case 5: 
if (eqStrings(token, ((NimStringDesc*) &TMP351))) goto LA1;
break;
	case 6: 
if (eqStrings(token, ((NimStringDesc*) &TMP368))) goto LA18;
break;
	case 7: 
if (eqStrings(token, ((NimStringDesc*) &TMP377))) goto LA27;
break;
	case 8: 
if (eqStrings(token, ((NimStringDesc*) &TMP369))) goto LA19;
break;
	case 10: 
if (eqStrings(token, ((NimStringDesc*) &TMP355))) goto LA5;
if (eqStrings(token, ((NimStringDesc*) &TMP361))) goto LA11;
if (eqStrings(token, ((NimStringDesc*) &TMP362))) goto LA12;
if (eqStrings(token, ((NimStringDesc*) &TMP366))) goto LA16;
if (eqStrings(token, ((NimStringDesc*) &TMP370))) goto LA20;
break;
	case 12: 
if (eqStrings(token, ((NimStringDesc*) &TMP363))) goto LA13;
break;
	case 14: 
if (eqStrings(token, ((NimStringDesc*) &TMP376))) goto LA26;
break;
	case 15: 
if (eqStrings(token, ((NimStringDesc*) &TMP354))) goto LA4;
if (eqStrings(token, ((NimStringDesc*) &TMP367))) goto LA17;
break;
	case 20: 
if (eqStrings(token, ((NimStringDesc*) &TMP373))) goto LA23;
break;
	case 21: 
if (eqStrings(token, ((NimStringDesc*) &TMP352))) goto LA2;
if (eqStrings(token, ((NimStringDesc*) &TMP359))) goto LA9;
break;
	case 22: 
if (eqStrings(token, ((NimStringDesc*) &TMP365))) goto LA15;
if (eqStrings(token, ((NimStringDesc*) &TMP375))) goto LA25;
break;
	case 24: 
if (eqStrings(token, ((NimStringDesc*) &TMP357))) goto LA7;
break;
	case 25: 
if (eqStrings(token, ((NimStringDesc*) &TMP358))) goto LA8;
break;
	case 28: 
if (eqStrings(token, ((NimStringDesc*) &TMP364))) goto LA14;
break;
	case 29: 
if (eqStrings(token, ((NimStringDesc*) &TMP371))) goto LA21;
break;
	case 30: 
if (eqStrings(token, ((NimStringDesc*) &TMP374))) goto LA24;
break;
	case 31: 
if (eqStrings(token, ((NimStringDesc*) &TMP353))) goto LA3;
if (eqStrings(token, ((NimStringDesc*) &TMP356))) goto LA6;
if (eqStrings(token, ((NimStringDesc*) &TMP372))) goto LA22;
break;
	}
	goto LA29;
	LA1: ;
	{
		NimStringDesc* LOC32;
		LOC32 = 0;
		LOC32 = nimIntToStr(((NI) ((*info).monthday)));
		(*buf) = resizeString((*buf), LOC32->Sup.len + 0);
appendString((*buf), LOC32);
	}
	goto LA30;
	LA2: ;
	{
		NimStringDesc* LOC38;
		{
			if (!(((NI) ((*info).monthday)) < ((NI) 10))) goto LA36;
			(*buf) = resizeString((*buf), 1);
appendString((*buf), ((NimStringDesc*) &TMP378));
		}
		LA36: ;
		LOC38 = 0;
		LOC38 = nimIntToStr(((NI) ((*info).monthday)));
		(*buf) = resizeString((*buf), LOC38->Sup.len + 0);
appendString((*buf), LOC38);
	}
	goto LA30;
	LA3: ;
	{
		NimStringDesc* LOC40;
		Slice90919 LOC41;
		NimStringDesc* LOC42;
		LOC40 = 0;
		LOC40 = HEX24_113834((*info).weekday);
		LOC41 = HEX2EHEX2E_104291(((NI) 0), ((NI) 2));
		LOC42 = 0;
		LOC42 = HEX5BHEX5D_90912(LOC40, LOC41);
		(*buf) = resizeString((*buf), LOC42->Sup.len + 0);
appendString((*buf), LOC42);
	}
	goto LA30;
	LA4: ;
	{
		NimStringDesc* LOC44;
		LOC44 = 0;
		LOC44 = HEX24_113834((*info).weekday);
		(*buf) = resizeString((*buf), LOC44->Sup.len + 0);
appendString((*buf), LOC44);
	}
	goto LA30;
	LA5: ;
	{
		NI LOC46;
		NimStringDesc* LOC52;
		LOC46 = 0;
		{
			if (!(((NI) 12) < ((NI) ((*info).hour)))) goto LA49;
			LOC46 = ((NI) ((NI)(((NI) ((*info).hour)) - ((NI) 12))));
		}
		goto LA47;
		LA49: ;
		{
			LOC46 = ((NI) ((*info).hour));
		}
		LA47: ;
		LOC52 = 0;
		LOC52 = nimIntToStr(LOC46);
		(*buf) = resizeString((*buf), LOC52->Sup.len + 0);
appendString((*buf), LOC52);
	}
	goto LA30;
	LA6: ;
	{
		NI amerhour;
		NimStringDesc* LOC63;
		{
			if (!(((NI) 12) < ((NI) ((*info).hour)))) goto LA56;
			amerhour = ((NI) ((NI)(((NI) ((*info).hour)) - ((NI) 12))));
		}
		goto LA54;
		LA56: ;
		{
			amerhour = ((NI) ((*info).hour));
		}
		LA54: ;
		{
			if (!(amerhour < ((NI) 10))) goto LA61;
			(*buf) = addChar((*buf), 48);
		}
		LA61: ;
		LOC63 = 0;
		LOC63 = nimIntToStr(amerhour);
		(*buf) = resizeString((*buf), LOC63->Sup.len + 0);
appendString((*buf), LOC63);
	}
	goto LA30;
	LA7: ;
	{
		NimStringDesc* LOC65;
		LOC65 = 0;
		LOC65 = nimIntToStr(((NI) ((*info).hour)));
		(*buf) = resizeString((*buf), LOC65->Sup.len + 0);
appendString((*buf), LOC65);
	}
	goto LA30;
	LA8: ;
	{
		NimStringDesc* LOC71;
		{
			if (!(((NI) ((*info).hour)) < ((NI) 10))) goto LA69;
			(*buf) = addChar((*buf), 48);
		}
		LA69: ;
		LOC71 = 0;
		LOC71 = nimIntToStr(((NI) ((*info).hour)));
		(*buf) = resizeString((*buf), LOC71->Sup.len + 0);
appendString((*buf), LOC71);
	}
	goto LA30;
	LA9: ;
	{
		NimStringDesc* LOC73;
		LOC73 = 0;
		LOC73 = nimIntToStr(((NI) ((*info).minute)));
		(*buf) = resizeString((*buf), LOC73->Sup.len + 0);
appendString((*buf), LOC73);
	}
	goto LA30;
	LA10: ;
	{
		NimStringDesc* LOC79;
		{
			if (!(((NI) ((*info).minute)) < ((NI) 10))) goto LA77;
			(*buf) = addChar((*buf), 48);
		}
		LA77: ;
		LOC79 = 0;
		LOC79 = nimIntToStr(((NI) ((*info).minute)));
		(*buf) = resizeString((*buf), LOC79->Sup.len + 0);
appendString((*buf), LOC79);
	}
	goto LA30;
	LA11: ;
	{
		NimStringDesc* LOC81;
		LOC81 = 0;
		LOC81 = nimIntToStr((NI)(((NI) ((*info).month)) + ((NI) 1)));
		(*buf) = resizeString((*buf), LOC81->Sup.len + 0);
appendString((*buf), LOC81);
	}
	goto LA30;
	LA12: ;
	{
		NimStringDesc* LOC87;
		{
			if (!((*info).month < ((NU8) 9))) goto LA85;
			(*buf) = addChar((*buf), 48);
		}
		LA85: ;
		LOC87 = 0;
		LOC87 = nimIntToStr((NI)(((NI) ((*info).month)) + ((NI) 1)));
		(*buf) = resizeString((*buf), LOC87->Sup.len + 0);
appendString((*buf), LOC87);
	}
	goto LA30;
	LA13: ;
	{
		NimStringDesc* LOC89;
		Slice90919 LOC90;
		NimStringDesc* LOC91;
		LOC89 = 0;
		LOC89 = HEX24_113850((*info).month);
		LOC90 = HEX2EHEX2E_104291(((NI) 0), ((NI) 2));
		LOC91 = 0;
		LOC91 = HEX5BHEX5D_90912(LOC89, LOC90);
		(*buf) = resizeString((*buf), LOC91->Sup.len + 0);
appendString((*buf), LOC91);
	}
	goto LA30;
	LA14: ;
	{
		NimStringDesc* LOC93;
		LOC93 = 0;
		LOC93 = HEX24_113850((*info).month);
		(*buf) = resizeString((*buf), LOC93->Sup.len + 0);
appendString((*buf), LOC93);
	}
	goto LA30;
	LA15: ;
	{
		NimStringDesc* LOC95;
		LOC95 = 0;
		LOC95 = nimIntToStr(((NI) ((*info).second)));
		(*buf) = resizeString((*buf), LOC95->Sup.len + 0);
appendString((*buf), LOC95);
	}
	goto LA30;
	LA16: ;
	{
		NimStringDesc* LOC101;
		{
			if (!(((NI) ((*info).second)) < ((NI) 10))) goto LA99;
			(*buf) = addChar((*buf), 48);
		}
		LA99: ;
		LOC101 = 0;
		LOC101 = nimIntToStr(((NI) ((*info).second)));
		(*buf) = resizeString((*buf), LOC101->Sup.len + 0);
appendString((*buf), LOC101);
	}
	goto LA30;
	LA17: ;
	{
		{
			if (!(((NI) 12) <= ((NI) ((*info).hour)))) goto LA105;
			(*buf) = addChar((*buf), 80);
		}
		goto LA103;
		LA105: ;
		{
			(*buf) = addChar((*buf), 65);
		}
		LA103: ;
	}
	goto LA30;
	LA18: ;
	{
		{
			if (!(((NI) 12) <= ((NI) ((*info).hour)))) goto LA111;
			(*buf) = resizeString((*buf), 2);
appendString((*buf), ((NimStringDesc*) &TMP379));
		}
		goto LA109;
		LA111: ;
		{
			(*buf) = resizeString((*buf), 2);
appendString((*buf), ((NimStringDesc*) &TMP380));
		}
		LA109: ;
	}
	goto LA30;
	LA19: ;
	{
		NI fr;
		NimStringDesc* LOC115;
		NimStringDesc* LOC120;
		NimStringDesc* LOC121;
		Slice90919 LOC122;
		NimStringDesc* LOC123;
		LOC115 = 0;
		LOC115 = nimIntToStr((*info).year);
		fr = (NI)((LOC115 ? LOC115->Sup.len : 0) - ((NI) 1));
		{
			if (!(fr < ((NI) 0))) goto LA118;
			fr = ((NI) 0);
		}
		LA118: ;
		LOC120 = 0;
		LOC120 = nimIntToStr((*info).year);
		LOC121 = 0;
		LOC121 = nimIntToStr((*info).year);
		LOC122 = HEX2EHEX2E_104291(fr, (NI)((LOC121 ? LOC121->Sup.len : 0) - ((NI) 1)));
		LOC123 = 0;
		LOC123 = HEX5BHEX5D_90912(LOC120, LOC122);
		(*buf) = resizeString((*buf), LOC123->Sup.len + 0);
appendString((*buf), LOC123);
	}
	goto LA30;
	LA20: ;
	{
		NI fr;
		NimStringDesc* LOC125;
		NimStringDesc* fyear;
		NimStringDesc* LOC130;
		NimStringDesc* LOC131;
		Slice90919 LOC132;
		LOC125 = 0;
		LOC125 = nimIntToStr((*info).year);
		fr = (NI)((LOC125 ? LOC125->Sup.len : 0) - ((NI) 2));
		{
			if (!(fr < ((NI) 0))) goto LA128;
			fr = ((NI) 0);
		}
		LA128: ;
		LOC130 = 0;
		LOC130 = nimIntToStr((*info).year);
		LOC131 = 0;
		LOC131 = nimIntToStr((*info).year);
		LOC132 = HEX2EHEX2E_104291(fr, (NI)((LOC131 ? LOC131->Sup.len : 0) - ((NI) 1)));
		fyear = HEX5BHEX5D_90912(LOC130, LOC132);
		{
			NimStringDesc* LOC137;
			NimStringDesc* LOC138;
			if (!!(((fyear ? fyear->Sup.len : 0) == ((NI) 2)))) goto LA135;
			LOC137 = 0;
			LOC138 = 0;
			LOC138 = nsuRepeatChar(48, ((NI) ((NI)(((NI) 2) - (fyear ? fyear->Sup.len : 0)))));
			LOC137 = rawNewString(LOC138->Sup.len + fyear->Sup.len + 0);
appendString(LOC137, LOC138);
appendString(LOC137, fyear);
			fyear = LOC137;
		}
		LA135: ;
		(*buf) = resizeString((*buf), fyear->Sup.len + 0);
appendString((*buf), fyear);
	}
	goto LA30;
	LA21: ;
	{
		NI fr;
		NimStringDesc* LOC140;
		NimStringDesc* fyear;
		NimStringDesc* LOC145;
		NimStringDesc* LOC146;
		Slice90919 LOC147;
		LOC140 = 0;
		LOC140 = nimIntToStr((*info).year);
		fr = (NI)((LOC140 ? LOC140->Sup.len : 0) - ((NI) 3));
		{
			if (!(fr < ((NI) 0))) goto LA143;
			fr = ((NI) 0);
		}
		LA143: ;
		LOC145 = 0;
		LOC145 = nimIntToStr((*info).year);
		LOC146 = 0;
		LOC146 = nimIntToStr((*info).year);
		LOC147 = HEX2EHEX2E_104291(fr, (NI)((LOC146 ? LOC146->Sup.len : 0) - ((NI) 1)));
		fyear = HEX5BHEX5D_90912(LOC145, LOC147);
		{
			NimStringDesc* LOC152;
			NimStringDesc* LOC153;
			if (!!(((fyear ? fyear->Sup.len : 0) == ((NI) 3)))) goto LA150;
			LOC152 = 0;
			LOC153 = 0;
			LOC153 = nsuRepeatChar(48, ((NI) ((NI)(((NI) 3) - (fyear ? fyear->Sup.len : 0)))));
			LOC152 = rawNewString(LOC153->Sup.len + fyear->Sup.len + 0);
appendString(LOC152, LOC153);
appendString(LOC152, fyear);
			fyear = LOC152;
		}
		LA150: ;
		(*buf) = resizeString((*buf), fyear->Sup.len + 0);
appendString((*buf), fyear);
	}
	goto LA30;
	LA22: ;
	{
		NI fr;
		NimStringDesc* LOC155;
		NimStringDesc* fyear;
		NimStringDesc* LOC160;
		NimStringDesc* LOC161;
		Slice90919 LOC162;
		LOC155 = 0;
		LOC155 = nimIntToStr((*info).year);
		fr = (NI)((LOC155 ? LOC155->Sup.len : 0) - ((NI) 4));
		{
			if (!(fr < ((NI) 0))) goto LA158;
			fr = ((NI) 0);
		}
		LA158: ;
		LOC160 = 0;
		LOC160 = nimIntToStr((*info).year);
		LOC161 = 0;
		LOC161 = nimIntToStr((*info).year);
		LOC162 = HEX2EHEX2E_104291(fr, (NI)((LOC161 ? LOC161->Sup.len : 0) - ((NI) 1)));
		fyear = HEX5BHEX5D_90912(LOC160, LOC162);
		{
			NimStringDesc* LOC167;
			NimStringDesc* LOC168;
			if (!!(((fyear ? fyear->Sup.len : 0) == ((NI) 4)))) goto LA165;
			LOC167 = 0;
			LOC168 = 0;
			LOC168 = nsuRepeatChar(48, ((NI) ((NI)(((NI) 4) - (fyear ? fyear->Sup.len : 0)))));
			LOC167 = rawNewString(LOC168->Sup.len + fyear->Sup.len + 0);
appendString(LOC167, LOC168);
appendString(LOC167, fyear);
			fyear = LOC167;
		}
		LA165: ;
		(*buf) = resizeString((*buf), fyear->Sup.len + 0);
appendString((*buf), fyear);
	}
	goto LA30;
	LA23: ;
	{
		NI fr;
		NimStringDesc* LOC170;
		NimStringDesc* fyear;
		NimStringDesc* LOC175;
		NimStringDesc* LOC176;
		Slice90919 LOC177;
		LOC170 = 0;
		LOC170 = nimIntToStr((*info).year);
		fr = (NI)((LOC170 ? LOC170->Sup.len : 0) - ((NI) 5));
		{
			if (!(fr < ((NI) 0))) goto LA173;
			fr = ((NI) 0);
		}
		LA173: ;
		LOC175 = 0;
		LOC175 = nimIntToStr((*info).year);
		LOC176 = 0;
		LOC176 = nimIntToStr((*info).year);
		LOC177 = HEX2EHEX2E_104291(fr, (NI)((LOC176 ? LOC176->Sup.len : 0) - ((NI) 1)));
		fyear = HEX5BHEX5D_90912(LOC175, LOC177);
		{
			NimStringDesc* LOC182;
			NimStringDesc* LOC183;
			if (!!(((fyear ? fyear->Sup.len : 0) == ((NI) 5)))) goto LA180;
			LOC182 = 0;
			LOC183 = 0;
			LOC183 = nsuRepeatChar(48, ((NI) ((NI)(((NI) 5) - (fyear ? fyear->Sup.len : 0)))));
			LOC182 = rawNewString(LOC183->Sup.len + fyear->Sup.len + 0);
appendString(LOC182, LOC183);
appendString(LOC182, fyear);
			fyear = LOC182;
		}
		LA180: ;
		(*buf) = resizeString((*buf), fyear->Sup.len + 0);
appendString((*buf), fyear);
	}
	goto LA30;
	LA24: ;
	{
		NI hrs;
		NimStringDesc* LOC185;
		hrs = (NI)((NI)((*info).timezone / ((NI) 60)) / ((NI) 60));
		LOC185 = 0;
		LOC185 = nimIntToStr(hrs);
		(*buf) = resizeString((*buf), LOC185->Sup.len + 0);
appendString((*buf), LOC185);
	}
	goto LA30;
	LA25: ;
	{
		NI hrs;
		NimStringDesc* LOC187;
		hrs = (NI)((NI)((*info).timezone / ((NI) 60)) / ((NI) 60));
		LOC187 = 0;
		LOC187 = nimIntToStr(hrs);
		(*buf) = resizeString((*buf), LOC187->Sup.len + 0);
appendString((*buf), LOC187);
		{
			NI atindex;
			NimStringDesc* LOC192;
			NI LOC193;
			if (!((hrs > 0? (hrs) : -(hrs)) < ((NI) 10))) goto LA190;
			LOC192 = 0;
			LOC192 = nimIntToStr(hrs);
			LOC193 = 0;
			{
				if (!(hrs < ((NI) 0))) goto LA196;
				LOC193 = ((NI) 1);
			}
			goto LA194;
			LA196: ;
			{
				LOC193 = ((NI) 0);
			}
			LA194: ;
			atindex = (NI)(((*buf) ? (*buf)->Sup.len : 0) - (NI)((LOC192 ? LOC192->Sup.len : 0) - LOC193));
			insert_92601(buf, ((NimStringDesc*) &TMP378), ((NI) (atindex)));
		}
		LA190: ;
	}
	goto LA30;
	LA26: ;
	{
		NI hrs;
		NimStringDesc* LOC200;
		NimStringDesc* LOC201;
		hrs = (NI)((NI)((*info).timezone / ((NI) 60)) / ((NI) 60));
		LOC200 = 0;
		LOC201 = 0;
		LOC201 = nimIntToStr(hrs);
		LOC200 = rawNewString(LOC201->Sup.len + 3);
appendString(LOC200, LOC201);
appendString(LOC200, ((NimStringDesc*) &TMP381));
		(*buf) = resizeString((*buf), LOC200->Sup.len + 0);
appendString((*buf), LOC200);
		{
			NI atindex;
			NimStringDesc* LOC206;
			NimStringDesc* LOC207;
			NI LOC208;
			if (!((hrs > 0? (hrs) : -(hrs)) < ((NI) 10))) goto LA204;
			LOC206 = 0;
			LOC207 = 0;
			LOC207 = nimIntToStr(hrs);
			LOC206 = rawNewString(LOC207->Sup.len + 3);
appendString(LOC206, LOC207);
appendString(LOC206, ((NimStringDesc*) &TMP381));
			LOC208 = 0;
			{
				if (!(hrs < ((NI) 0))) goto LA211;
				LOC208 = ((NI) 1);
			}
			goto LA209;
			LA211: ;
			{
				LOC208 = ((NI) 0);
			}
			LA209: ;
			atindex = (NI)(((*buf) ? (*buf)->Sup.len : 0) - (NI)((LOC206 ? LOC206->Sup.len : 0) - LOC208));
			insert_92601(buf, ((NimStringDesc*) &TMP378), ((NI) (atindex)));
		}
		LA204: ;
	}
	goto LA30;
	LA27: ;
	{
		(*buf) = resizeString((*buf), (*info).tzname->Sup.len + 0);
appendString((*buf), (*info).tzname);
	}
	goto LA30;
	LA28: ;
	{
	}
	goto LA30;
	LA29: ;
	{
		Valueerror4049* e_113971;
		NimStringDesc* LOC217;
		e_113971 = 0;
		e_113971 = (Valueerror4049*) newObj((&NTI25428), sizeof(Valueerror4049));
		(*e_113971).Sup.Sup.m_type = (&NTI4049);
		LOC217 = 0;
		LOC217 = rawNewString(token->Sup.len + 23);
appendString(LOC217, ((NimStringDesc*) &TMP382));
appendString(LOC217, token);
		asgnRefNoCycle((void**) (&(*e_113971).Sup.message), LOC217);
		raiseException((Exception*)e_113971, "ValueError");
	}
	LA30: ;
}

N_NIMCALL(NimStringDesc*, format_113990)(Timeinfo111810* info, NimStringDesc* f) {
	NimStringDesc* result;
	NI i;
	NimStringDesc* currentf;
	result = 0;
	result = copyString(((NimStringDesc*) &TMP331));
	i = ((NI) 0);
	currentf = copyString(((NimStringDesc*) &TMP331));
	{
		while (1) {
			switch (((NU8)(f->data[i]))) {
			case 32:
			case 45:
			case 47:
			case 58:
			case 39:
			case 0:
			case 40:
			case 41:
			case 91:
			case 93:
			case 44:
			{
				formattoken_113866(info, currentf, (&result));
				currentf = copyString(((NimStringDesc*) &TMP331));
				{
					if (!((NU8)(f->data[i]) == (NU8)(0))) goto LA6;
					goto LA1;
				}
				LA6: ;
				{
					if (!((NU8)(f->data[i]) == (NU8)(39))) goto LA10;
					i += ((NI) 1);
					{
						while (1) {
							NIM_BOOL LOC14;
							LOC14 = 0;
							LOC14 = !(((NU8)(f->data[i]) == (NU8)(39)));
							if (!(LOC14)) goto LA15;
							LOC14 = (i < (NI)((f ? f->Sup.len : 0) - ((NI) 1)));
							LA15: ;
							if (!LOC14) goto LA13;
							result = addChar(result, f->data[i]);
							i += ((NI) 1);
						} LA13: ;
					}
				}
				goto LA8;
				LA10: ;
				{
					result = addChar(result, f->data[i]);
				}
				LA8: ;
			}
			break;
			default:
			{
				{
					NIM_BOOL LOC20;
					LOC20 = 0;
					LOC20 = ((currentf ? currentf->Sup.len : 0) < ((NI) 1));
					if (LOC20) goto LA21;
					LOC20 = ((NU8)(currentf->data[(currentf ? (currentf->Sup.len-1) : -1)]) == (NU8)(f->data[i]));
					LA21: ;
					if (!LOC20) goto LA22;
					currentf = addChar(currentf, f->data[i]);
				}
				goto LA18;
				LA22: ;
				{
					formattoken_113866(info, currentf, (&result));
					i -= ((NI) 1);
					currentf = copyString(((NimStringDesc*) &TMP331));
				}
				LA18: ;
			}
			break;
			}
			i += ((NI) 1);
		}
	} LA1: ;
	return result;
}

N_NIMCALL(void, parsetoken_114058)(Timeinfo111810* info, NimStringDesc* token, NimStringDesc* value, NI* j) {
	NI sv;
	sv = 0;
	switch (hashString(token) & 31) {
	case 1: 
if (eqStrings(token, ((NimStringDesc*) &TMP360))) goto LA8;
break;
	case 5: 
if (eqStrings(token, ((NimStringDesc*) &TMP351))) goto LA1;
break;
	case 6: 
if (eqStrings(token, ((NimStringDesc*) &TMP368))) goto LA16;
break;
	case 7: 
if (eqStrings(token, ((NimStringDesc*) &TMP377))) goto LA22;
break;
	case 10: 
if (eqStrings(token, ((NimStringDesc*) &TMP355))) goto LA5;
if (eqStrings(token, ((NimStringDesc*) &TMP361))) goto LA9;
if (eqStrings(token, ((NimStringDesc*) &TMP362))) goto LA10;
if (eqStrings(token, ((NimStringDesc*) &TMP366))) goto LA14;
if (eqStrings(token, ((NimStringDesc*) &TMP370))) goto LA17;
break;
	case 12: 
if (eqStrings(token, ((NimStringDesc*) &TMP363))) goto LA11;
break;
	case 14: 
if (eqStrings(token, ((NimStringDesc*) &TMP376))) goto LA21;
break;
	case 15: 
if (eqStrings(token, ((NimStringDesc*) &TMP354))) goto LA4;
if (eqStrings(token, ((NimStringDesc*) &TMP367))) goto LA15;
break;
	case 21: 
if (eqStrings(token, ((NimStringDesc*) &TMP352))) goto LA2;
if (eqStrings(token, ((NimStringDesc*) &TMP359))) goto LA7;
break;
	case 22: 
if (eqStrings(token, ((NimStringDesc*) &TMP365))) goto LA13;
if (eqStrings(token, ((NimStringDesc*) &TMP375))) goto LA20;
break;
	case 24: 
if (eqStrings(token, ((NimStringDesc*) &TMP357))) goto LA5;
break;
	case 25: 
if (eqStrings(token, ((NimStringDesc*) &TMP358))) goto LA6;
break;
	case 28: 
if (eqStrings(token, ((NimStringDesc*) &TMP364))) goto LA12;
break;
	case 30: 
if (eqStrings(token, ((NimStringDesc*) &TMP374))) goto LA19;
break;
	case 31: 
if (eqStrings(token, ((NimStringDesc*) &TMP353))) goto LA3;
if (eqStrings(token, ((NimStringDesc*) &TMP356))) goto LA6;
if (eqStrings(token, ((NimStringDesc*) &TMP372))) goto LA18;
break;
	}
	goto LA23;
	LA1: ;
	{
		NI pd;
		Slice90919 LOC26;
		NimStringDesc* LOC27;
		LOC26 = HEX2EHEX2E_104291((*j), (NI)((*j) + ((NI) 1)));
		LOC27 = 0;
		LOC27 = HEX5BHEX5D_90912(value, LOC26);
		pd = npuParseInt(LOC27, (&sv), ((NI) 0));
		(*info).monthday = ((NI) (sv));
		(*j) += pd;
	}
	goto LA24;
	LA2: ;
	{
		Slice90919 LOC29;
		NimStringDesc* LOC30;
		NI LOC31;
		LOC29 = HEX2EHEX2E_104291((*j), (NI)((*j) + ((NI) 1)));
		LOC30 = 0;
		LOC30 = HEX5BHEX5D_90912(value, LOC29);
		LOC31 = 0;
		LOC31 = nsuParseInt(LOC30);
		(*info).monthday = ((NI) (LOC31));
		(*j) += ((NI) 2);
	}
	goto LA24;
	LA3: ;
	{
		Slice90919 LOC33;
		NimStringDesc* LOC34;
		NimStringDesc* LOC35;
		LOC33 = HEX2EHEX2E_104291((*j), (NI)((*j) + ((NI) 2)));
		LOC34 = 0;
		LOC34 = HEX5BHEX5D_90912(value, LOC33);
		LOC35 = 0;
		LOC35 = nsuToLowerStr(LOC34);
		if (eqStrings(LOC35, ((NimStringDesc*) &TMP403))) goto LA36;
		if (eqStrings(LOC35, ((NimStringDesc*) &TMP404))) goto LA37;
		if (eqStrings(LOC35, ((NimStringDesc*) &TMP405))) goto LA38;
		if (eqStrings(LOC35, ((NimStringDesc*) &TMP406))) goto LA39;
		if (eqStrings(LOC35, ((NimStringDesc*) &TMP407))) goto LA40;
		if (eqStrings(LOC35, ((NimStringDesc*) &TMP408))) goto LA41;
		if (eqStrings(LOC35, ((NimStringDesc*) &TMP409))) goto LA42;
		goto LA43;
		LA36: ;
		{
			(*info).weekday = ((NU8) 6);
		}
		goto LA44;
		LA37: ;
		{
			(*info).weekday = ((NU8) 0);
		}
		goto LA44;
		LA38: ;
		{
			(*info).weekday = ((NU8) 1);
		}
		goto LA44;
		LA39: ;
		{
			(*info).weekday = ((NU8) 2);
		}
		goto LA44;
		LA40: ;
		{
			(*info).weekday = ((NU8) 3);
		}
		goto LA44;
		LA41: ;
		{
			(*info).weekday = ((NU8) 4);
		}
		goto LA44;
		LA42: ;
		{
			(*info).weekday = ((NU8) 5);
		}
		goto LA44;
		LA43: ;
		{
			Valueerror4049* e_114130;
			NimStringDesc* LOC53;
			Slice90919 LOC54;
			NimStringDesc* LOC55;
			e_114130 = 0;
			e_114130 = (Valueerror4049*) newObj((&NTI25428), sizeof(Valueerror4049));
			(*e_114130).Sup.Sup.m_type = (&NTI4049);
			LOC53 = 0;
			LOC54 = HEX2EHEX2E_104291((*j), (NI)((*j) + ((NI) 2)));
			LOC55 = 0;
			LOC55 = HEX5BHEX5D_90912(value, LOC54);
			LOC53 = rawNewString(LOC55->Sup.len + 39);
appendString(LOC53, ((NimStringDesc*) &TMP410));
appendString(LOC53, LOC55);
			asgnRefNoCycle((void**) (&(*e_114130).Sup.message), LOC53);
			raiseException((Exception*)e_114130, "ValueError");
		}
		LA44: ;
		(*j) += ((NI) 3);
	}
	goto LA24;
	LA4: ;
	{
		{
			NIM_BOOL LOC59;
			Slice90919 LOC61;
			NimStringDesc* LOC62;
			NI LOC63;
			LOC59 = 0;
			LOC59 = ((NI)((*j) + ((NI) 6)) <= (value ? value->Sup.len : 0));
			if (!(LOC59)) goto LA60;
			LOC61 = HEX2EHEX2E_104291((*j), (NI)((*j) + ((NI) 5)));
			LOC62 = 0;
			LOC62 = HEX5BHEX5D_90912(value, LOC61);
			LOC63 = 0;
			LOC63 = nsuCmpIgnoreCase(LOC62, ((NimStringDesc*) &TMP414));
			LOC59 = (LOC63 == ((NI) 0));
			LA60: ;
			if (!LOC59) goto LA64;
			(*info).weekday = ((NU8) 6);
			(*j) += ((NI) 6);
		}
		goto LA57;
		LA64: ;
		{
			NIM_BOOL LOC67;
			Slice90919 LOC69;
			NimStringDesc* LOC70;
			NI LOC71;
			LOC67 = 0;
			LOC67 = ((NI)((*j) + ((NI) 6)) <= (value ? value->Sup.len : 0));
			if (!(LOC67)) goto LA68;
			LOC69 = HEX2EHEX2E_104291((*j), (NI)((*j) + ((NI) 5)));
			LOC70 = 0;
			LOC70 = HEX5BHEX5D_90912(value, LOC69);
			LOC71 = 0;
			LOC71 = nsuCmpIgnoreCase(LOC70, ((NimStringDesc*) &TMP415));
			LOC67 = (LOC71 == ((NI) 0));
			LA68: ;
			if (!LOC67) goto LA72;
			(*info).weekday = ((NU8) 0);
			(*j) += ((NI) 6);
		}
		goto LA57;
		LA72: ;
		{
			NIM_BOOL LOC75;
			Slice90919 LOC77;
			NimStringDesc* LOC78;
			NI LOC79;
			LOC75 = 0;
			LOC75 = ((NI)((*j) + ((NI) 7)) <= (value ? value->Sup.len : 0));
			if (!(LOC75)) goto LA76;
			LOC77 = HEX2EHEX2E_104291((*j), (NI)((*j) + ((NI) 6)));
			LOC78 = 0;
			LOC78 = HEX5BHEX5D_90912(value, LOC77);
			LOC79 = 0;
			LOC79 = nsuCmpIgnoreCase(LOC78, ((NimStringDesc*) &TMP416));
			LOC75 = (LOC79 == ((NI) 0));
			LA76: ;
			if (!LOC75) goto LA80;
			(*info).weekday = ((NU8) 1);
			(*j) += ((NI) 7);
		}
		goto LA57;
		LA80: ;
		{
			NIM_BOOL LOC83;
			Slice90919 LOC85;
			NimStringDesc* LOC86;
			NI LOC87;
			LOC83 = 0;
			LOC83 = ((NI)((*j) + ((NI) 9)) <= (value ? value->Sup.len : 0));
			if (!(LOC83)) goto LA84;
			LOC85 = HEX2EHEX2E_104291((*j), (NI)((*j) + ((NI) 8)));
			LOC86 = 0;
			LOC86 = HEX5BHEX5D_90912(value, LOC85);
			LOC87 = 0;
			LOC87 = nsuCmpIgnoreCase(LOC86, ((NimStringDesc*) &TMP417));
			LOC83 = (LOC87 == ((NI) 0));
			LA84: ;
			if (!LOC83) goto LA88;
			(*info).weekday = ((NU8) 2);
			(*j) += ((NI) 9);
		}
		goto LA57;
		LA88: ;
		{
			NIM_BOOL LOC91;
			Slice90919 LOC93;
			NimStringDesc* LOC94;
			NI LOC95;
			LOC91 = 0;
			LOC91 = ((NI)((*j) + ((NI) 8)) <= (value ? value->Sup.len : 0));
			if (!(LOC91)) goto LA92;
			LOC93 = HEX2EHEX2E_104291((*j), (NI)((*j) + ((NI) 7)));
			LOC94 = 0;
			LOC94 = HEX5BHEX5D_90912(value, LOC93);
			LOC95 = 0;
			LOC95 = nsuCmpIgnoreCase(LOC94, ((NimStringDesc*) &TMP418));
			LOC91 = (LOC95 == ((NI) 0));
			LA92: ;
			if (!LOC91) goto LA96;
			(*info).weekday = ((NU8) 3);
			(*j) += ((NI) 8);
		}
		goto LA57;
		LA96: ;
		{
			NIM_BOOL LOC99;
			Slice90919 LOC101;
			NimStringDesc* LOC102;
			NI LOC103;
			LOC99 = 0;
			LOC99 = ((NI)((*j) + ((NI) 6)) <= (value ? value->Sup.len : 0));
			if (!(LOC99)) goto LA100;
			LOC101 = HEX2EHEX2E_104291((*j), (NI)((*j) + ((NI) 5)));
			LOC102 = 0;
			LOC102 = HEX5BHEX5D_90912(value, LOC101);
			LOC103 = 0;
			LOC103 = nsuCmpIgnoreCase(LOC102, ((NimStringDesc*) &TMP419));
			LOC99 = (LOC103 == ((NI) 0));
			LA100: ;
			if (!LOC99) goto LA104;
			(*info).weekday = ((NU8) 4);
			(*j) += ((NI) 6);
		}
		goto LA57;
		LA104: ;
		{
			NIM_BOOL LOC107;
			Slice90919 LOC109;
			NimStringDesc* LOC110;
			NI LOC111;
			LOC107 = 0;
			LOC107 = ((NI)((*j) + ((NI) 8)) <= (value ? value->Sup.len : 0));
			if (!(LOC107)) goto LA108;
			LOC109 = HEX2EHEX2E_104291((*j), (NI)((*j) + ((NI) 7)));
			LOC110 = 0;
			LOC110 = HEX5BHEX5D_90912(value, LOC109);
			LOC111 = 0;
			LOC111 = nsuCmpIgnoreCase(LOC110, ((NimStringDesc*) &TMP420));
			LOC107 = (LOC111 == ((NI) 0));
			LA108: ;
			if (!LOC107) goto LA112;
			(*info).weekday = ((NU8) 5);
			(*j) += ((NI) 8);
		}
		goto LA57;
		LA112: ;
		{
			Valueerror4049* e_114285;
			NimStringDesc* LOC115;
			e_114285 = 0;
			e_114285 = (Valueerror4049*) newObj((&NTI25428), sizeof(Valueerror4049));
			(*e_114285).Sup.Sup.m_type = (&NTI4049);
			LOC115 = 0;
			LOC115 = rawNewString(value->Sup.len + 40);
appendString(LOC115, ((NimStringDesc*) &TMP421));
appendString(LOC115, value);
			asgnRefNoCycle((void**) (&(*e_114285).Sup.message), LOC115);
			raiseException((Exception*)e_114285, "ValueError");
		}
		LA57: ;
	}
	goto LA24;
	LA5: ;
	{
		NI pd;
		Slice90919 LOC117;
		NimStringDesc* LOC118;
		LOC117 = HEX2EHEX2E_104291((*j), (NI)((*j) + ((NI) 1)));
		LOC118 = 0;
		LOC118 = HEX5BHEX5D_90912(value, LOC117);
		pd = npuParseInt(LOC118, (&sv), ((NI) 0));
		(*info).hour = ((NI) (sv));
		(*j) += pd;
	}
	goto LA24;
	LA6: ;
	{
		Slice90919 LOC120;
		NimStringDesc* LOC121;
		NI LOC122;
		LOC120 = HEX2EHEX2E_104291((*j), (NI)((*j) + ((NI) 1)));
		LOC121 = 0;
		LOC121 = HEX5BHEX5D_90912(value, LOC120);
		LOC122 = 0;
		LOC122 = nsuParseInt(LOC121);
		(*info).hour = ((NI) (LOC122));
		(*j) += ((NI) 2);
	}
	goto LA24;
	LA7: ;
	{
		NI pd;
		Slice90919 LOC124;
		NimStringDesc* LOC125;
		LOC124 = HEX2EHEX2E_104291((*j), (NI)((*j) + ((NI) 1)));
		LOC125 = 0;
		LOC125 = HEX5BHEX5D_90912(value, LOC124);
		pd = npuParseInt(LOC125, (&sv), ((NI) 0));
		(*info).minute = ((NI) (sv));
		(*j) += pd;
	}
	goto LA24;
	LA8: ;
	{
		Slice90919 LOC127;
		NimStringDesc* LOC128;
		NI LOC129;
		LOC127 = HEX2EHEX2E_104291((*j), (NI)((*j) + ((NI) 1)));
		LOC128 = 0;
		LOC128 = HEX5BHEX5D_90912(value, LOC127);
		LOC129 = 0;
		LOC129 = nsuParseInt(LOC128);
		(*info).minute = ((NI) (LOC129));
		(*j) += ((NI) 2);
	}
	goto LA24;
	LA9: ;
	{
		NI pd;
		Slice90919 LOC131;
		NimStringDesc* LOC132;
		LOC131 = HEX2EHEX2E_104291((*j), (NI)((*j) + ((NI) 1)));
		LOC132 = 0;
		LOC132 = HEX5BHEX5D_90912(value, LOC131);
		pd = npuParseInt(LOC132, (&sv), ((NI) 0));
		(*info).month = ((NU8) ((NI)(sv - ((NI) 1))));
		(*info).monthday = ((NI) (sv));
		(*j) += pd;
	}
	goto LA24;
	LA10: ;
	{
		NI month;
		Slice90919 LOC134;
		NimStringDesc* LOC135;
		LOC134 = HEX2EHEX2E_104291((*j), (NI)((*j) + ((NI) 1)));
		LOC135 = 0;
		LOC135 = HEX5BHEX5D_90912(value, LOC134);
		month = nsuParseInt(LOC135);
		(*j) += ((NI) 2);
		(*info).month = ((NU8) ((NI)(month - ((NI) 1))));
	}
	goto LA24;
	LA11: ;
	{
		Slice90919 LOC137;
		NimStringDesc* LOC138;
		NimStringDesc* LOC139;
		LOC137 = HEX2EHEX2E_104291((*j), (NI)((*j) + ((NI) 2)));
		LOC138 = 0;
		LOC138 = HEX5BHEX5D_90912(value, LOC137);
		LOC139 = 0;
		LOC139 = nsuToLowerStr(LOC138);
		switch (hashString(LOC139) & 15) {
		case 0: 
if (eqStrings(LOC139, ((NimStringDesc*) &TMP423))) goto LA141;
break;
		case 3: 
if (eqStrings(LOC139, ((NimStringDesc*) &TMP424))) goto LA142;
if (eqStrings(LOC139, ((NimStringDesc*) &TMP426))) goto LA144;
break;
		case 5: 
if (eqStrings(LOC139, ((NimStringDesc*) &TMP433))) goto LA151;
break;
		case 8: 
if (eqStrings(LOC139, ((NimStringDesc*) &TMP422))) goto LA140;
break;
		case 9: 
if (eqStrings(LOC139, ((NimStringDesc*) &TMP429))) goto LA147;
if (eqStrings(LOC139, ((NimStringDesc*) &TMP430))) goto LA148;
break;
		case 11: 
if (eqStrings(LOC139, ((NimStringDesc*) &TMP427))) goto LA145;
break;
		case 14: 
if (eqStrings(LOC139, ((NimStringDesc*) &TMP425))) goto LA143;
if (eqStrings(LOC139, ((NimStringDesc*) &TMP432))) goto LA150;
break;
		case 15: 
if (eqStrings(LOC139, ((NimStringDesc*) &TMP428))) goto LA146;
if (eqStrings(LOC139, ((NimStringDesc*) &TMP431))) goto LA149;
break;
		}
		goto LA152;
		LA140: ;
		{
			(*info).month = ((NU8) 0);
		}
		goto LA153;
		LA141: ;
		{
			(*info).month = ((NU8) 1);
		}
		goto LA153;
		LA142: ;
		{
			(*info).month = ((NU8) 2);
		}
		goto LA153;
		LA143: ;
		{
			(*info).month = ((NU8) 3);
		}
		goto LA153;
		LA144: ;
		{
			(*info).month = ((NU8) 4);
		}
		goto LA153;
		LA145: ;
		{
			(*info).month = ((NU8) 5);
		}
		goto LA153;
		LA146: ;
		{
			(*info).month = ((NU8) 6);
		}
		goto LA153;
		LA147: ;
		{
			(*info).month = ((NU8) 7);
		}
		goto LA153;
		LA148: ;
		{
			(*info).month = ((NU8) 8);
		}
		goto LA153;
		LA149: ;
		{
			(*info).month = ((NU8) 9);
		}
		goto LA153;
		LA150: ;
		{
			(*info).month = ((NU8) 10);
		}
		goto LA153;
		LA151: ;
		{
			(*info).month = ((NU8) 11);
		}
		goto LA153;
		LA152: ;
		{
			Valueerror4049* e_114429;
			NimStringDesc* LOC167;
			e_114429 = 0;
			e_114429 = (Valueerror4049*) newObj((&NTI25428), sizeof(Valueerror4049));
			(*e_114429).Sup.Sup.m_type = (&NTI4049);
			LOC167 = 0;
			LOC167 = rawNewString(value->Sup.len + 33);
appendString(LOC167, ((NimStringDesc*) &TMP434));
appendString(LOC167, value);
			asgnRefNoCycle((void**) (&(*e_114429).Sup.message), LOC167);
			raiseException((Exception*)e_114429, "ValueError");
		}
		LA153: ;
		(*j) += ((NI) 3);
	}
	goto LA24;
	LA12: ;
	{
		{
			NIM_BOOL LOC171;
			Slice90919 LOC173;
			NimStringDesc* LOC174;
			NI LOC175;
			LOC171 = 0;
			LOC171 = ((NI)((*j) + ((NI) 7)) <= (value ? value->Sup.len : 0));
			if (!(LOC171)) goto LA172;
			LOC173 = HEX2EHEX2E_104291((*j), (NI)((*j) + ((NI) 6)));
			LOC174 = 0;
			LOC174 = HEX5BHEX5D_90912(value, LOC173);
			LOC175 = 0;
			LOC175 = nsuCmpIgnoreCase(LOC174, ((NimStringDesc*) &TMP435));
			LOC171 = (LOC175 == ((NI) 0));
			LA172: ;
			if (!LOC171) goto LA176;
			(*info).month = ((NU8) 0);
			(*j) += ((NI) 7);
		}
		goto LA169;
		LA176: ;
		{
			NIM_BOOL LOC179;
			Slice90919 LOC181;
			NimStringDesc* LOC182;
			NI LOC183;
			LOC179 = 0;
			LOC179 = ((NI)((*j) + ((NI) 8)) <= (value ? value->Sup.len : 0));
			if (!(LOC179)) goto LA180;
			LOC181 = HEX2EHEX2E_104291((*j), (NI)((*j) + ((NI) 7)));
			LOC182 = 0;
			LOC182 = HEX5BHEX5D_90912(value, LOC181);
			LOC183 = 0;
			LOC183 = nsuCmpIgnoreCase(LOC182, ((NimStringDesc*) &TMP436));
			LOC179 = (LOC183 == ((NI) 0));
			LA180: ;
			if (!LOC179) goto LA184;
			(*info).month = ((NU8) 1);
			(*j) += ((NI) 8);
		}
		goto LA169;
		LA184: ;
		{
			NIM_BOOL LOC187;
			Slice90919 LOC189;
			NimStringDesc* LOC190;
			NI LOC191;
			LOC187 = 0;
			LOC187 = ((NI)((*j) + ((NI) 5)) <= (value ? value->Sup.len : 0));
			if (!(LOC187)) goto LA188;
			LOC189 = HEX2EHEX2E_104291((*j), (NI)((*j) + ((NI) 4)));
			LOC190 = 0;
			LOC190 = HEX5BHEX5D_90912(value, LOC189);
			LOC191 = 0;
			LOC191 = nsuCmpIgnoreCase(LOC190, ((NimStringDesc*) &TMP437));
			LOC187 = (LOC191 == ((NI) 0));
			LA188: ;
			if (!LOC187) goto LA192;
			(*info).month = ((NU8) 2);
			(*j) += ((NI) 5);
		}
		goto LA169;
		LA192: ;
		{
			NIM_BOOL LOC195;
			Slice90919 LOC197;
			NimStringDesc* LOC198;
			NI LOC199;
			LOC195 = 0;
			LOC195 = ((NI)((*j) + ((NI) 5)) <= (value ? value->Sup.len : 0));
			if (!(LOC195)) goto LA196;
			LOC197 = HEX2EHEX2E_104291((*j), (NI)((*j) + ((NI) 4)));
			LOC198 = 0;
			LOC198 = HEX5BHEX5D_90912(value, LOC197);
			LOC199 = 0;
			LOC199 = nsuCmpIgnoreCase(LOC198, ((NimStringDesc*) &TMP438));
			LOC195 = (LOC199 == ((NI) 0));
			LA196: ;
			if (!LOC195) goto LA200;
			(*info).month = ((NU8) 3);
			(*j) += ((NI) 5);
		}
		goto LA169;
		LA200: ;
		{
			NIM_BOOL LOC203;
			Slice90919 LOC205;
			NimStringDesc* LOC206;
			NI LOC207;
			LOC203 = 0;
			LOC203 = ((NI)((*j) + ((NI) 3)) <= (value ? value->Sup.len : 0));
			if (!(LOC203)) goto LA204;
			LOC205 = HEX2EHEX2E_104291((*j), (NI)((*j) + ((NI) 2)));
			LOC206 = 0;
			LOC206 = HEX5BHEX5D_90912(value, LOC205);
			LOC207 = 0;
			LOC207 = nsuCmpIgnoreCase(LOC206, ((NimStringDesc*) &TMP426));
			LOC203 = (LOC207 == ((NI) 0));
			LA204: ;
			if (!LOC203) goto LA208;
			(*info).month = ((NU8) 4);
			(*j) += ((NI) 3);
		}
		goto LA169;
		LA208: ;
		{
			NIM_BOOL LOC211;
			Slice90919 LOC213;
			NimStringDesc* LOC214;
			NI LOC215;
			LOC211 = 0;
			LOC211 = ((NI)((*j) + ((NI) 4)) <= (value ? value->Sup.len : 0));
			if (!(LOC211)) goto LA212;
			LOC213 = HEX2EHEX2E_104291((*j), (NI)((*j) + ((NI) 3)));
			LOC214 = 0;
			LOC214 = HEX5BHEX5D_90912(value, LOC213);
			LOC215 = 0;
			LOC215 = nsuCmpIgnoreCase(LOC214, ((NimStringDesc*) &TMP439));
			LOC211 = (LOC215 == ((NI) 0));
			LA212: ;
			if (!LOC211) goto LA216;
			(*info).month = ((NU8) 5);
			(*j) += ((NI) 4);
		}
		goto LA169;
		LA216: ;
		{
			NIM_BOOL LOC219;
			Slice90919 LOC221;
			NimStringDesc* LOC222;
			NI LOC223;
			LOC219 = 0;
			LOC219 = ((NI)((*j) + ((NI) 4)) <= (value ? value->Sup.len : 0));
			if (!(LOC219)) goto LA220;
			LOC221 = HEX2EHEX2E_104291((*j), (NI)((*j) + ((NI) 3)));
			LOC222 = 0;
			LOC222 = HEX5BHEX5D_90912(value, LOC221);
			LOC223 = 0;
			LOC223 = nsuCmpIgnoreCase(LOC222, ((NimStringDesc*) &TMP440));
			LOC219 = (LOC223 == ((NI) 0));
			LA220: ;
			if (!LOC219) goto LA224;
			(*info).month = ((NU8) 6);
			(*j) += ((NI) 4);
		}
		goto LA169;
		LA224: ;
		{
			NIM_BOOL LOC227;
			Slice90919 LOC229;
			NimStringDesc* LOC230;
			NI LOC231;
			LOC227 = 0;
			LOC227 = ((NI)((*j) + ((NI) 6)) <= (value ? value->Sup.len : 0));
			if (!(LOC227)) goto LA228;
			LOC229 = HEX2EHEX2E_104291((*j), (NI)((*j) + ((NI) 5)));
			LOC230 = 0;
			LOC230 = HEX5BHEX5D_90912(value, LOC229);
			LOC231 = 0;
			LOC231 = nsuCmpIgnoreCase(LOC230, ((NimStringDesc*) &TMP441));
			LOC227 = (LOC231 == ((NI) 0));
			LA228: ;
			if (!LOC227) goto LA232;
			(*info).month = ((NU8) 7);
			(*j) += ((NI) 6);
		}
		goto LA169;
		LA232: ;
		{
			NIM_BOOL LOC235;
			Slice90919 LOC237;
			NimStringDesc* LOC238;
			NI LOC239;
			LOC235 = 0;
			LOC235 = ((NI)((*j) + ((NI) 9)) <= (value ? value->Sup.len : 0));
			if (!(LOC235)) goto LA236;
			LOC237 = HEX2EHEX2E_104291((*j), (NI)((*j) + ((NI) 8)));
			LOC238 = 0;
			LOC238 = HEX5BHEX5D_90912(value, LOC237);
			LOC239 = 0;
			LOC239 = nsuCmpIgnoreCase(LOC238, ((NimStringDesc*) &TMP442));
			LOC235 = (LOC239 == ((NI) 0));
			LA236: ;
			if (!LOC235) goto LA240;
			(*info).month = ((NU8) 8);
			(*j) += ((NI) 9);
		}
		goto LA169;
		LA240: ;
		{
			NIM_BOOL LOC243;
			Slice90919 LOC245;
			NimStringDesc* LOC246;
			NI LOC247;
			LOC243 = 0;
			LOC243 = ((NI)((*j) + ((NI) 7)) <= (value ? value->Sup.len : 0));
			if (!(LOC243)) goto LA244;
			LOC245 = HEX2EHEX2E_104291((*j), (NI)((*j) + ((NI) 6)));
			LOC246 = 0;
			LOC246 = HEX5BHEX5D_90912(value, LOC245);
			LOC247 = 0;
			LOC247 = nsuCmpIgnoreCase(LOC246, ((NimStringDesc*) &TMP443));
			LOC243 = (LOC247 == ((NI) 0));
			LA244: ;
			if (!LOC243) goto LA248;
			(*info).month = ((NU8) 9);
			(*j) += ((NI) 7);
		}
		goto LA169;
		LA248: ;
		{
			NIM_BOOL LOC251;
			Slice90919 LOC253;
			NimStringDesc* LOC254;
			NI LOC255;
			LOC251 = 0;
			LOC251 = ((NI)((*j) + ((NI) 8)) <= (value ? value->Sup.len : 0));
			if (!(LOC251)) goto LA252;
			LOC253 = HEX2EHEX2E_104291((*j), (NI)((*j) + ((NI) 7)));
			LOC254 = 0;
			LOC254 = HEX5BHEX5D_90912(value, LOC253);
			LOC255 = 0;
			LOC255 = nsuCmpIgnoreCase(LOC254, ((NimStringDesc*) &TMP444));
			LOC251 = (LOC255 == ((NI) 0));
			LA252: ;
			if (!LOC251) goto LA256;
			(*info).month = ((NU8) 10);
			(*j) += ((NI) 8);
		}
		goto LA169;
		LA256: ;
		{
			NIM_BOOL LOC259;
			Slice90919 LOC261;
			NimStringDesc* LOC262;
			NI LOC263;
			LOC259 = 0;
			LOC259 = ((NI)((*j) + ((NI) 8)) <= (value ? value->Sup.len : 0));
			if (!(LOC259)) goto LA260;
			LOC261 = HEX2EHEX2E_104291((*j), (NI)((*j) + ((NI) 7)));
			LOC262 = 0;
			LOC262 = HEX5BHEX5D_90912(value, LOC261);
			LOC263 = 0;
			LOC263 = nsuCmpIgnoreCase(LOC262, ((NimStringDesc*) &TMP445));
			LOC259 = (LOC263 == ((NI) 0));
			LA260: ;
			if (!LOC259) goto LA264;
			(*info).month = ((NU8) 11);
			(*j) += ((NI) 8);
		}
		goto LA169;
		LA264: ;
		{
			Valueerror4049* e_114679;
			NimStringDesc* LOC267;
			e_114679 = 0;
			e_114679 = (Valueerror4049*) newObj((&NTI25428), sizeof(Valueerror4049));
			(*e_114679).Sup.Sup.m_type = (&NTI4049);
			LOC267 = 0;
			LOC267 = rawNewString(value->Sup.len + 34);
appendString(LOC267, ((NimStringDesc*) &TMP446));
appendString(LOC267, value);
			asgnRefNoCycle((void**) (&(*e_114679).Sup.message), LOC267);
			raiseException((Exception*)e_114679, "ValueError");
		}
		LA169: ;
	}
	goto LA24;
	LA13: ;
	{
		NI pd;
		Slice90919 LOC269;
		NimStringDesc* LOC270;
		LOC269 = HEX2EHEX2E_104291((*j), (NI)((*j) + ((NI) 1)));
		LOC270 = 0;
		LOC270 = HEX5BHEX5D_90912(value, LOC269);
		pd = npuParseInt(LOC270, (&sv), ((NI) 0));
		(*info).second = ((NI) (sv));
		(*j) += pd;
	}
	goto LA24;
	LA14: ;
	{
		Slice90919 LOC272;
		NimStringDesc* LOC273;
		NI LOC274;
		LOC272 = HEX2EHEX2E_104291((*j), (NI)((*j) + ((NI) 1)));
		LOC273 = 0;
		LOC273 = HEX5BHEX5D_90912(value, LOC272);
		LOC274 = 0;
		LOC274 = nsuParseInt(LOC273);
		(*info).second = ((NI) (LOC274));
		(*j) += ((NI) 2);
	}
	goto LA24;
	LA15: ;
	{
		{
			NIM_BOOL LOC278;
			NIM_BOOL LOC279;
			LOC278 = 0;
			LOC279 = 0;
			LOC279 = ((NU8)(value->data[(*j)]) == (NU8)(80));
			if (!(LOC279)) goto LA280;
			LOC279 = (((NI) 0) < ((NI) ((*info).hour)));
			LA280: ;
			LOC278 = LOC279;
			if (!(LOC278)) goto LA281;
			LOC278 = (((NI) ((*info).hour)) < ((NI) 12));
			LA281: ;
			if (!LOC278) goto LA282;
			(*info).hour += ((NI) 12);
		}
		LA282: ;
		(*j) += ((NI) 1);
	}
	goto LA24;
	LA16: ;
	{
		{
			NIM_BOOL LOC287;
			NIM_BOOL LOC288;
			Slice90919 LOC289;
			NimStringDesc* LOC290;
			LOC287 = 0;
			LOC288 = 0;
			LOC289 = HEX2EHEX2E_104291((*j), (NI)((*j) + ((NI) 1)));
			LOC290 = 0;
			LOC290 = HEX5BHEX5D_90912(value, LOC289);
			LOC288 = eqStrings(LOC290, ((NimStringDesc*) &TMP379));
			if (!(LOC288)) goto LA291;
			LOC288 = (((NI) 0) < ((NI) ((*info).hour)));
			LA291: ;
			LOC287 = LOC288;
			if (!(LOC287)) goto LA292;
			LOC287 = (((NI) ((*info).hour)) < ((NI) 12));
			LA292: ;
			if (!LOC287) goto LA293;
			(*info).hour += ((NI) 12);
		}
		LA293: ;
		(*j) += ((NI) 2);
	}
	goto LA24;
	LA17: ;
	{
		NI year;
		Slice90919 LOC296;
		NimStringDesc* LOC297;
		NI thiscen;
		time_t LOC298;
		Timeinfo111810 LOC299;
		LOC296 = HEX2EHEX2E_104291((*j), (NI)((*j) + ((NI) 1)));
		LOC297 = 0;
		LOC297 = HEX5BHEX5D_90912(value, LOC296);
		year = nsuParseInt(LOC297);
		LOC298 = 0;
		LOC298 = gettime_111872();
		memset((void*)(&LOC299), 0, sizeof(LOC299));
		LOC299.Sup.m_type = (&NTI111810);
		getlocaltime_111877(LOC298, (&LOC299));
		thiscen = (NI)(LOC299.year / ((NI) 100));
		(*info).year = (NI)((NI)(thiscen * ((NI) 100)) + year);
		(*j) += ((NI) 2);
	}
	goto LA24;
	LA18: ;
	{
		Slice90919 LOC301;
		NimStringDesc* LOC302;
		LOC301 = HEX2EHEX2E_104291((*j), (NI)((*j) + ((NI) 3)));
		LOC302 = 0;
		LOC302 = HEX5BHEX5D_90912(value, LOC301);
		(*info).year = nsuParseInt(LOC302);
		(*j) += ((NI) 4);
	}
	goto LA24;
	LA19: ;
	{
		{
			NimStringDesc* LOC308;
			if (!((NU8)(value->data[(*j)]) == (NU8)(43))) goto LA306;
			LOC308 = 0;
			LOC308 = nimCharToStr(value->data[(NI)((*j) + ((NI) 1))]);
			(*info).timezone = nsuParseInt(LOC308);
		}
		goto LA304;
		LA306: ;
		{
			NimStringDesc* LOC312;
			NI LOC313;
			if (!((NU8)(value->data[(*j)]) == (NU8)(45))) goto LA310;
			LOC312 = 0;
			LOC312 = nimCharToStr(value->data[(NI)((*j) + ((NI) 1))]);
			LOC313 = 0;
			LOC313 = nsuParseInt(LOC312);
			(*info).timezone = (NI)(((NI) 0) - LOC313);
		}
		goto LA304;
		LA310: ;
		{
			Valueerror4049* e_114820;
			NimStringDesc* LOC315;
			e_114820 = 0;
			e_114820 = (Valueerror4049*) newObj((&NTI25428), sizeof(Valueerror4049));
			(*e_114820).Sup.Sup.m_type = (&NTI4049);
			LOC315 = 0;
			LOC315 = rawNewString(42);
appendString(LOC315, ((NimStringDesc*) &TMP447));
appendChar(LOC315, value->data[(*j)]);
			asgnRefNoCycle((void**) (&(*e_114820).Sup.message), LOC315);
			raiseException((Exception*)e_114820, "ValueError");
		}
		LA304: ;
		(*j) += ((NI) 2);
	}
	goto LA24;
	LA20: ;
	{
		{
			Slice90919 LOC321;
			NimStringDesc* LOC322;
			if (!((NU8)(value->data[(*j)]) == (NU8)(43))) goto LA319;
			LOC321 = HEX2EHEX2E_104291((NI)((*j) + ((NI) 1)), (NI)((*j) + ((NI) 2)));
			LOC322 = 0;
			LOC322 = HEX5BHEX5D_90912(value, LOC321);
			(*info).timezone = nsuParseInt(LOC322);
		}
		goto LA317;
		LA319: ;
		{
			Slice90919 LOC326;
			NimStringDesc* LOC327;
			NI LOC328;
			if (!((NU8)(value->data[(*j)]) == (NU8)(45))) goto LA324;
			LOC326 = HEX2EHEX2E_104291((NI)((*j) + ((NI) 1)), (NI)((*j) + ((NI) 2)));
			LOC327 = 0;
			LOC327 = HEX5BHEX5D_90912(value, LOC326);
			LOC328 = 0;
			LOC328 = nsuParseInt(LOC327);
			(*info).timezone = (NI)(((NI) 0) - LOC328);
		}
		goto LA317;
		LA324: ;
		{
			Valueerror4049* e_114862;
			NimStringDesc* LOC330;
			e_114862 = 0;
			e_114862 = (Valueerror4049*) newObj((&NTI25428), sizeof(Valueerror4049));
			(*e_114862).Sup.Sup.m_type = (&NTI4049);
			LOC330 = 0;
			LOC330 = rawNewString(43);
appendString(LOC330, ((NimStringDesc*) &TMP448));
appendChar(LOC330, value->data[(*j)]);
			asgnRefNoCycle((void**) (&(*e_114862).Sup.message), LOC330);
			raiseException((Exception*)e_114862, "ValueError");
		}
		LA317: ;
		(*j) += ((NI) 3);
	}
	goto LA24;
	LA21: ;
	{
		{
			Slice90919 LOC336;
			NimStringDesc* LOC337;
			if (!((NU8)(value->data[(*j)]) == (NU8)(43))) goto LA334;
			LOC336 = HEX2EHEX2E_104291((NI)((*j) + ((NI) 1)), (NI)((*j) + ((NI) 2)));
			LOC337 = 0;
			LOC337 = HEX5BHEX5D_90912(value, LOC336);
			(*info).timezone = nsuParseInt(LOC337);
		}
		goto LA332;
		LA334: ;
		{
			Slice90919 LOC341;
			NimStringDesc* LOC342;
			NI LOC343;
			if (!((NU8)(value->data[(*j)]) == (NU8)(45))) goto LA339;
			LOC341 = HEX2EHEX2E_104291((NI)((*j) + ((NI) 1)), (NI)((*j) + ((NI) 2)));
			LOC342 = 0;
			LOC342 = HEX5BHEX5D_90912(value, LOC341);
			LOC343 = 0;
			LOC343 = nsuParseInt(LOC342);
			(*info).timezone = (NI)(((NI) 0) - LOC343);
		}
		goto LA332;
		LA339: ;
		{
			Valueerror4049* e_114904;
			NimStringDesc* LOC345;
			e_114904 = 0;
			e_114904 = (Valueerror4049*) newObj((&NTI25428), sizeof(Valueerror4049));
			(*e_114904).Sup.Sup.m_type = (&NTI4049);
			LOC345 = 0;
			LOC345 = rawNewString(44);
appendString(LOC345, ((NimStringDesc*) &TMP449));
appendChar(LOC345, value->data[(*j)]);
			asgnRefNoCycle((void**) (&(*e_114904).Sup.message), LOC345);
			raiseException((Exception*)e_114904, "ValueError");
		}
		LA332: ;
		(*j) += ((NI) 6);
	}
	goto LA24;
	LA22: ;
	{
		Slice90919 LOC347;
		NimStringDesc* LOC348;
		LOC347 = HEX2EHEX2E_104291((*j), (NI)((*j) + ((NI) 2)));
		LOC348 = 0;
		LOC348 = HEX5BHEX5D_90912(value, LOC347);
		unsureAsgnRef((void**) (&(*info).tzname), nsuToUpperStr(LOC348));
		(*j) += ((NI) 3);
	}
	goto LA24;
	LA23: ;
	{
		(*j) += (token ? token->Sup.len : 0);
	}
	LA24: ;
}

N_NIMCALL(void, parse_114965)(NimStringDesc* value, NimStringDesc* layout, Timeinfo111810* Result) {
	NI i;
	NI j;
	NimStringDesc* token;
	Timeinfo111810 info;
	time_t LOC1;
	time_t LOC30;
	Timeinfo111810 LOC31;
{	i = ((NI) 0);
	j = ((NI) 0);
	token = copyString(((NimStringDesc*) &TMP331));
	memset((void*)(&info), 0, sizeof(info));
	info.Sup.m_type = (&NTI111810);
	LOC1 = 0;
	LOC1 = gettime_111872();
	memset((void*)(&info), 0, sizeof(info));
	info.Sup.m_type = (&NTI111810);
	getlocaltime_111877(LOC1, (&info));
	info.hour = ((NI) 0);
	info.minute = ((NI) 0);
	info.second = ((NI) 0);
	{
		while (1) {
			switch (((NU8)(layout->data[i]))) {
			case 32:
			case 45:
			case 47:
			case 58:
			case 39:
			case 0:
			case 40:
			case 41:
			case 91:
			case 93:
			case 44:
			{
				{
					if (!(((NI) 0) < (token ? token->Sup.len : 0))) goto LA7;
					parsetoken_114058((&info), token, value, (&j));
				}
				LA7: ;
				token = copyString(((NimStringDesc*) &TMP331));
				{
					if (!((NU8)(layout->data[i]) == (NU8)(0))) goto LA11;
					goto LA2;
				}
				LA11: ;
				{
					if (!((NU8)(layout->data[i]) == (NU8)(39))) goto LA15;
					i += ((NI) 1);
					{
						while (1) {
							NIM_BOOL LOC19;
							LOC19 = 0;
							LOC19 = !(((NU8)(layout->data[i]) == (NU8)(39)));
							if (!(LOC19)) goto LA20;
							LOC19 = (i < (NI)((layout ? layout->Sup.len : 0) - ((NI) 1)));
							LA20: ;
							if (!LOC19) goto LA18;
							i += ((NI) 1);
							j += ((NI) 1);
						} LA18: ;
					}
					i += ((NI) 1);
				}
				goto LA13;
				LA15: ;
				{
					i += ((NI) 1);
					j += ((NI) 1);
				}
				LA13: ;
			}
			break;
			default:
			{
				{
					NIM_BOOL LOC25;
					LOC25 = 0;
					LOC25 = ((token ? token->Sup.len : 0) < ((NI) 1));
					if (LOC25) goto LA26;
					LOC25 = ((NU8)(token->data[(token ? (token->Sup.len-1) : -1)]) == (NU8)(layout->data[i]));
					LA26: ;
					if (!LOC25) goto LA27;
					token = addChar(token, layout->data[i]);
					i += ((NI) 1);
				}
				goto LA23;
				LA27: ;
				{
					parsetoken_114058((&info), token, value, (&j));
					token = copyString(((NimStringDesc*) &TMP331));
				}
				LA23: ;
			}
			break;
			}
		}
	} LA2: ;
	LOC30 = 0;
	LOC30 = timeinfototime_111889((&info));
	memset((void*)(&LOC31), 0, sizeof(LOC31));
	LOC31.Sup.m_type = (&NTI111810);
	getlocaltime_111877(LOC30, (&LOC31));
	info.weekday = LOC31.weekday;
	genericAssign((void*)Result, (void*)(&info), (&NTI111810));
	goto BeforeRet;
	}BeforeRet: ;
}

N_NIMCALL(NI, countleapyears_115061)(NI yearspan) {
	NI result;
	NF LOC1;
	NF LOC2;
	NF LOC3;
	result = 0;
	LOC1 = 0;
	LOC1 = HEX2F_90866((NI)(yearspan - ((NI) 1)), ((NI) 4));
	LOC2 = 0;
	LOC2 = HEX2F_90866((NI)(yearspan - ((NI) 1)), ((NI) 100));
	LOC3 = 0;
	LOC3 = HEX2F_90866((NI)(yearspan - ((NI) 1)), ((NI) 400));
	result = ((NI) (((NF)(((NF)(LOC1) - (NF)(LOC2))) + (NF)(LOC3))));
	return result;
}

N_NIMCALL(NI, countdays_115074)(NI yearspan) {
	NI result;
	NI LOC1;
	result = 0;
	LOC1 = 0;
	LOC1 = countleapyears_115061(yearspan);
	result = (NI)((NI)((NI)(yearspan - ((NI) 1)) * ((NI) 365)) + LOC1);
	return result;
}

N_NIMCALL(NI, countyears_115085)(NI dayspan) {
	NI result;
	NI LOC1;
	result = 0;
	LOC1 = 0;
	LOC1 = countleapyears_115061((NI)(dayspan / ((NI) 365)));
	result = (NI)((NI)(dayspan - LOC1) / ((NI) 365));
	return result;
}

N_NIMCALL(TY115100, countyearsanddays_115097)(NI dayspan) {
	TY115100 result;
	NI days;
	NI LOC1;
	memset((void*)(&result), 0, sizeof(result));
	LOC1 = 0;
	LOC1 = countleapyears_115061((NI)(dayspan / ((NI) 365)));
	days = (NI)(dayspan - LOC1);
	result.Field0 = (NI)(days / ((NI) 365));
	result.Field1 = ((NI) ((NI)(days % ((NI) 365))));
	return result;
}

N_NIMCALL(NU8, getdayofweek_115126)(NI day, NI month, NI year) {
	NU8 result;
	NI a;
	NI y;
	NI m;
	NI d;
{	result = 0;
	a = (NI)((NI)(((NI) 14) - month) / ((NI) 12));
	y = (NI)(year - a);
	m = (NI)((NI)(month + (NI)(((NI) 12) * a)) - ((NI) 2));
	d = (NI)((NI)((NI)((NI)((NI)((NI)(day + y) + (NI)(y / ((NI) 4))) - (NI)(y / ((NI) 100))) + (NI)(y / ((NI) 400))) + (NI)((NI)(((NI) 31) * m) / ((NI) 12))) % ((NI) 7));
	{
		if (!(((NI) (d)) == ((NI) 0))) goto LA3;
		result = ((NU8) 6);
		goto BeforeRet;
	}
	LA3: ;
	result = ((NU8) ((NI)(((NI) (d)) - ((NI) 1))));
	}BeforeRet: ;
	return result;
}

N_NIMCALL(NU8, getdayofweekjulian_115147)(NI day, NI month, NI year) {
	NU8 result;
	NI a;
	NI y;
	NI m;
	NI d;
	result = 0;
	a = (NI)((NI)(((NI) 14) - month) / ((NI) 12));
	y = (NI)(year - a);
	m = (NI)((NI)(month + (NI)(((NI) 12) * a)) - ((NI) 2));
	d = (NI)((NI)((NI)((NI)((NI)(((NI) 5) + day) + y) + (NI)(y / ((NI) 4))) + (NI)((NI)(((NI) 31) * m) / ((NI) 12))) % ((NI) 7));
	result = ((NU8) (d));
	return result;
}

N_NIMCALL(void, timetotimeinfo_115164)(time_t t, Timeinfo111810* Result) {
	NI secs;
	NF LOC1;
	NI dayssinceepoch;
	TY115100 LOC2;
	NI yearssinceepoch;
	NI daysremaining;
	NI dayseconds;
	NI y;
	NU8 mon;
	NI days;
	NI daysinmonth;
	NI yd;
	NU8 m;
	NI md;
	NU8 wd;
	NI h;
	NI mi;
	NI s;
	Timeinfo111810 LOC7;
	LOC1 = 0;
	LOC1 = toseconds_111912(t);
	secs = ((NI) (LOC1));
	dayssinceepoch = (NI)(secs / ((NI) 86400));
	LOC2 = countyearsanddays_115097(dayssinceepoch);
	yearssinceepoch = LOC2.Field0;
	daysremaining = LOC2.Field1;
	dayseconds = (NI)(secs % ((NI) 86400));
	y = (NI)(yearssinceepoch + ((NI) 1970));
	mon = ((NU8) 0);
	days = daysremaining;
	daysinmonth = getdaysinmonth_112045(mon, y);
	{
		while (1) {
			NIM_BOOL LOC5;
			LOC5 = 0;
			LOC5 = (daysinmonth < days);
			if (!(LOC5)) goto LA6;
			LOC5 = (mon <= ((NU8) 11));
			LA6: ;
			if (!LOC5) goto LA4;
			days -= daysinmonth;
			mon += ((NI) 1);
			daysinmonth = getdaysinmonth_112045(mon, y);
		} LA4: ;
	}
	yd = daysremaining;
	m = mon;
	md = days;
	wd = getdayofweek_115126(days, (NI)(((NI) (mon)) + ((NI) 1)), y);
	h = (NI)(((NI) ((NI)(((NI) (dayseconds)) / ((NI) 3600)))) + ((NI) 1));
	mi = (NI)(((NI) ((NI)(((NI) (dayseconds)) % ((NI) 3600)))) / ((NI) 60));
	s = (NI)(((NI) (dayseconds)) % ((NI) 60));
	memset((void*)(&LOC7), 0, sizeof(LOC7));
	LOC7.Sup.m_type = (&NTI111810);
	memset((void*)(&LOC7), 0, sizeof(LOC7));
	LOC7.Sup.m_type = (&NTI111810);
	LOC7.year = y;
	LOC7.yearday = ((NI) (yd));
	LOC7.month = m;
	LOC7.monthday = ((NI) (md));
	LOC7.weekday = wd;
	LOC7.hour = ((NI) (h));
	LOC7.minute = ((NI) (mi));
	LOC7.second = ((NI) (s));
	genericShallowAssign((void*)Result, (void*)(&LOC7), (&NTI111810));
}

N_NIMCALL(Timeinterval111812, timetotimeinterval_115234)(time_t t) {
	Timeinterval111812 result;
	NI secs;
	NF LOC1;
	NI dayssinceepoch;
	TY115100 LOC2;
	NI yearssinceepoch;
	NI daysremaining;
	NI dayseconds;
	NU8 mon;
	NI days;
	NI daysinmonth;
	memset((void*)(&result), 0, sizeof(result));
	LOC1 = 0;
	LOC1 = toseconds_111912(t);
	secs = ((NI) (LOC1));
	dayssinceepoch = (NI)(secs / ((NI) 86400));
	LOC2 = countyearsanddays_115097(dayssinceepoch);
	yearssinceepoch = LOC2.Field0;
	daysremaining = LOC2.Field1;
	dayseconds = (NI)(secs % ((NI) 86400));
	result.years = (NI)(yearssinceepoch + ((NI) 1970));
	mon = ((NU8) 0);
	days = daysremaining;
	daysinmonth = getdaysinmonth_112045(mon, result.years);
	{
		while (1) {
			NIM_BOOL LOC5;
			LOC5 = 0;
			LOC5 = (daysinmonth < days);
			if (!(LOC5)) goto LA6;
			LOC5 = (mon <= ((NU8) 11));
			LA6: ;
			if (!LOC5) goto LA4;
			days -= daysinmonth;
			mon += ((NI) 1);
			daysinmonth = getdaysinmonth_112045(mon, result.years);
		} LA4: ;
	}
	result.months = (NI)(((NI) (mon)) + ((NI) 1));
	result.days = days;
	result.hours = ((NI) ((NI)(((NI) ((NI)(((NI) (dayseconds)) / ((NI) 3600)))) + ((NI) 1))));
	result.minutes = ((NI) ((NI)(((NI) ((NI)(((NI) (dayseconds)) % ((NI) 3600)))) / ((NI) 60))));
	result.seconds = ((NI) ((NI)(((NI) (dayseconds)) % ((NI) 60))));
	return result;
}
NIM_EXTERNC N_NOINLINE(void, HEX00_timesInit000)(void) {
	tzset();
}

NIM_EXTERNC N_NOINLINE(void, HEX00_timesDatInit000)(void) {
static TNimNode* TMP323[11];
static TNimNode* TMP324[12];
NI TMP326;
static char* NIM_CONST TMP325[12] = {
"mJan", 
"mFeb", 
"mMar", 
"mApr", 
"mMay", 
"mJun", 
"mJul", 
"mAug", 
"mSep", 
"mOct", 
"mNov", 
"mDec"};
static TNimNode* TMP327[7];
NI TMP329;
static char* NIM_CONST TMP328[7] = {
"dMon", 
"dTue", 
"dWed", 
"dThu", 
"dFri", 
"dSat", 
"dSun"};
static TNimNode TMP321[33];
NTI111810.size = sizeof(Timeinfo111810);
NTI111810.kind = 17;
NTI111810.base = (&NTI4011);
TMP323[0] = &TMP321[1];
NTI111813.size = sizeof(NI);
NTI111813.kind = 20;
NTI111813.base = (&NTI108);
NTI111813.flags = 3;
TMP321[1].kind = 1;
TMP321[1].offset = offsetof(Timeinfo111810, second);
TMP321[1].typ = (&NTI111813);
TMP321[1].name = "second";
TMP323[1] = &TMP321[2];
NTI111816.size = sizeof(NI);
NTI111816.kind = 20;
NTI111816.base = (&NTI108);
NTI111816.flags = 3;
TMP321[2].kind = 1;
TMP321[2].offset = offsetof(Timeinfo111810, minute);
TMP321[2].typ = (&NTI111816);
TMP321[2].name = "minute";
TMP323[2] = &TMP321[3];
NTI111818.size = sizeof(NI);
NTI111818.kind = 20;
NTI111818.base = (&NTI108);
NTI111818.flags = 3;
TMP321[3].kind = 1;
TMP321[3].offset = offsetof(Timeinfo111810, hour);
TMP321[3].typ = (&NTI111818);
TMP321[3].name = "hour";
TMP323[3] = &TMP321[4];
NTI111821.size = sizeof(NI);
NTI111821.kind = 20;
NTI111821.base = (&NTI108);
NTI111821.flags = 3;
TMP321[4].kind = 1;
TMP321[4].offset = offsetof(Timeinfo111810, monthday);
TMP321[4].typ = (&NTI111821);
TMP321[4].name = "monthday";
TMP323[4] = &TMP321[5];
NTI111606.size = sizeof(NU8);
NTI111606.kind = 14;
NTI111606.base = 0;
NTI111606.flags = 3;
for (TMP326 = 0; TMP326 < 12; TMP326++) {
TMP321[TMP326+6].kind = 1;
TMP321[TMP326+6].offset = TMP326;
TMP321[TMP326+6].name = TMP325[TMP326];
TMP324[TMP326] = &TMP321[TMP326+6];
}
TMP321[18].len = 12; TMP321[18].kind = 2; TMP321[18].sons = &TMP324[0];
NTI111606.node = &TMP321[18];
TMP321[5].kind = 1;
TMP321[5].offset = offsetof(Timeinfo111810, month);
TMP321[5].typ = (&NTI111606);
TMP321[5].name = "month";
TMP323[5] = &TMP321[19];
TMP321[19].kind = 1;
TMP321[19].offset = offsetof(Timeinfo111810, year);
TMP321[19].typ = (&NTI108);
TMP321[19].name = "year";
TMP323[6] = &TMP321[20];
NTI111608.size = sizeof(NU8);
NTI111608.kind = 14;
NTI111608.base = 0;
NTI111608.flags = 3;
for (TMP329 = 0; TMP329 < 7; TMP329++) {
TMP321[TMP329+21].kind = 1;
TMP321[TMP329+21].offset = TMP329;
TMP321[TMP329+21].name = TMP328[TMP329];
TMP327[TMP329] = &TMP321[TMP329+21];
}
TMP321[28].len = 7; TMP321[28].kind = 2; TMP321[28].sons = &TMP327[0];
NTI111608.node = &TMP321[28];
TMP321[20].kind = 1;
TMP321[20].offset = offsetof(Timeinfo111810, weekday);
TMP321[20].typ = (&NTI111608);
TMP321[20].name = "weekday";
TMP323[7] = &TMP321[29];
NTI111827.size = sizeof(NI);
NTI111827.kind = 20;
NTI111827.base = (&NTI108);
NTI111827.flags = 3;
TMP321[29].kind = 1;
TMP321[29].offset = offsetof(Timeinfo111810, yearday);
TMP321[29].typ = (&NTI111827);
TMP321[29].name = "yearday";
TMP323[8] = &TMP321[30];
TMP321[30].kind = 1;
TMP321[30].offset = offsetof(Timeinfo111810, isdst);
TMP321[30].typ = (&NTI138);
TMP321[30].name = "isDST";
TMP323[9] = &TMP321[31];
TMP321[31].kind = 1;
TMP321[31].offset = offsetof(Timeinfo111810, tzname);
TMP321[31].typ = (&NTI149);
TMP321[31].name = "tzname";
TMP323[10] = &TMP321[32];
TMP321[32].kind = 1;
TMP321[32].offset = offsetof(Timeinfo111810, timezone);
TMP321[32].typ = (&NTI108);
TMP321[32].name = "timezone";
TMP321[0].len = 11; TMP321[0].kind = 2; TMP321[0].sons = &TMP323[0];
NTI111810.node = &TMP321[0];
}

